# Generated by Django 5.0.4 on 2024-06-04 11:00

import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "time_resolution",
                    models.CharField(
                        choices=[("yearly", "Yearly")],
                        help_text="Time resolution of the time stamps of data points in this dataset",
                        max_length=16,
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=100, verbose_name="unit"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["unit"], required_languages=(), virtual_fields=True
                    ),
                ),
            ],
            options={
                "verbose_name": "dataset",
                "verbose_name_plural": "datasets",
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["name"], required_languages=(), virtual_fields=True
                    ),
                ),
            ],
            options={
                "verbose_name": "dimension",
                "verbose_name_plural": "dimensions",
            },
        ),
        migrations.CreateModel(
            name="DatasetScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_id", models.PositiveIntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="budget.dataset",
                    ),
                ),
                (
                    "scope_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimensionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["label"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "dimension",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="budget.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "dimension category",
                "verbose_name_plural": "dimension categories",
            },
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of this data point in context of the dataset's time resolution",
                        verbose_name="date",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="value"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="budget.dataset",
                        verbose_name="dataset",
                    ),
                ),
                (
                    "dimension_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="data_points",
                        to="budget.dimensioncategory",
                        verbose_name="dimension categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "data point",
                "verbose_name_plural": "data points",
            },
        ),
        migrations.CreateModel(
            name="DimensionScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("scope_id", models.PositiveIntegerField()),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="budget.dimension",
                    ),
                ),
                (
                    "scope_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
