# Generated by Django 5.0.4 on 2024-07-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_datapoint_options_alter_dataset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetschema',
            name='dimension_categories',
        ),
        migrations.AlterField(
            model_name='datasetschemascope',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='budget.datasetschema'),
        ),
        migrations.AlterField(
            model_name='dimensionscope',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='budget.dimension'),
        ),
        migrations.CreateModel(
            name='DatasetSchemaDimensionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemas', to='budget.dimensioncategory')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimension_categories', to='budget.datasetschema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
