# Generated by Django 5.0.4 on 2024-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_datasetschema_dimension_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='value'),
        ),
    ]
