# Generated by Django 5.0.6 on 2024-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_datapoint_options_alter_dataset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetschema',
            name='start_date',
            field=models.DateField(blank=True, help_text='First applicable date for datapoints in these datasets', null=True, verbose_name='start date'),
        ),
    ]
