# Generated by Django 3.2.16 on 2024-03-08 07:10

from django.db import migrations


def add_defaults(apps, schema_editor):
    ReportActionPrintLayoutCustomization = apps.get_model('reports', 'ReportActionPrintLayoutCustomization')
    ReportActionPrintLayoutCustomization.objects.get_or_create(
        plan=None,
        defaults=dict(
            max_columns=4,
            width_needed=[
                [30, 1],
                [100, 2],
                [1000, 4],
                [5000, 4],
                [1000000, 4]
            ],
            approximate_chars_per_line=90,
            approximate_lines_per_page=50,
            min_split_chars=500
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportactionprintlayoutcustomization'),
    ]

    operations = [
        migrations.RunPython(add_defaults, migrations.RunPython.noop)
    ]
