# Generated by Django 5.0.6 on 2024-09-02 12:04

import actions.blocks.choosers
import django.db.models.deletion
import reports.blocks.action_content
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0130_alter_attributetype_other_languages_and_more'),
        ('reports', '0008_default_report_print_layout_customizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fields',
            field=wagtail.fields.StreamField([('implementation_phase', reports.blocks.action_content.ActionImplementationPhaseReportFieldBlock()), ('attribute_type', wagtail.blocks.StructBlock([('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock(required=True))])), ('responsible_party', wagtail.blocks.StructBlock([('target_ancestor_depth', wagtail.blocks.IntegerBlock(help_text="In addition to the organization itself, an organizational unit containing the organization is included in the report. Counting from the top-level root organisation at level 1, which level in the organizational hierarchy should be used to find this containing organization? If left empty, don't add the containing organization to the report.", label='Level of containing organization', max_value=10, min_value=1, required=False))])), ('category', wagtail.blocks.StructBlock([('category_type', actions.blocks.choosers.CategoryTypeChooserBlock(required=True)), ('category_level', actions.blocks.choosers.CategoryLevelChooserBlock(required=False))])), ('status', reports.blocks.action_content.ActionStatusReportFieldBlock()), ('manual_status_reason', wagtail.blocks.StructBlock([('field_label', wagtail.blocks.CharBlock(default='', help_text='Heading to show instead of the default', label='Field label', required=False)), ('field_help_text', wagtail.blocks.CharBlock(default='', help_text='Help text for the field to be shown in the UI', label='Help text', required=False))])), ('description', wagtail.blocks.StructBlock([('field_label', wagtail.blocks.CharBlock(default='', help_text='Heading to show instead of the default', label='Field label', required=False)), ('field_help_text', wagtail.blocks.CharBlock(default='', help_text='Help text for the field to be shown in the UI', label='Help text', required=False))])), ('tasks', wagtail.blocks.StructBlock([('field_label', wagtail.blocks.CharBlock(default='', help_text='Heading to show instead of the default', label='Field label', required=False)), ('field_help_text', wagtail.blocks.CharBlock(default='', help_text='Help text for the field to be shown in the UI', label='Help text', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportactionprintlayoutcustomization',
            name='approximate_chars_per_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportactionprintlayoutcustomization',
            name='approximate_lines_per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportactionprintlayoutcustomization',
            name='max_columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportactionprintlayoutcustomization',
            name='min_split_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportactionprintlayoutcustomization',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actions.plan'),
        ),
        migrations.AlterField(
            model_name='reportactionprintlayoutcustomization',
            name='width_needed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='fields',
            field=wagtail.fields.StreamField([('implementation_phase', reports.blocks.action_content.ActionImplementationPhaseReportFieldBlock()), ('attribute_type', wagtail.blocks.StructBlock([('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock(required=True))])), ('responsible_party', wagtail.blocks.StructBlock([('target_ancestor_depth', wagtail.blocks.IntegerBlock(help_text="In addition to the organization itself, an organizational unit containing the organization is included in the report. Counting from the top-level root organisation at level 1, which level in the organizational hierarchy should be used to find this containing organization? If left empty, don't add the containing organization to the report.", label='Level of containing organization', max_value=10, min_value=1, required=False))])), ('category', wagtail.blocks.StructBlock([('category_type', actions.blocks.choosers.CategoryTypeChooserBlock(required=True)), ('category_level', actions.blocks.choosers.CategoryLevelChooserBlock(required=False))])), ('status', reports.blocks.action_content.ActionStatusReportFieldBlock()), ('manual_status_reason', wagtail.blocks.StructBlock([('field_label', wagtail.blocks.CharBlock(default='', help_text='Heading to show instead of the default', label='Field label', required=False)), ('field_help_text', wagtail.blocks.CharBlock(default='', help_text='Help text for the field to be shown in the UI', label='Help text', required=False))])), ('description', wagtail.blocks.StructBlock([('field_label', wagtail.blocks.CharBlock(default='', help_text='Heading to show instead of the default', label='Field label', required=False)), ('field_help_text', wagtail.blocks.CharBlock(default='', help_text='Help text for the field to be shown in the UI', label='Help text', required=False))])), ('tasks', wagtail.blocks.StructBlock([('field_label', wagtail.blocks.CharBlock(default='', help_text='Heading to show instead of the default', label='Field label', required=False)), ('field_help_text', wagtail.blocks.CharBlock(default='', help_text='Help text for the field to be shown in the UI', label='Help text', required=False))]))], blank=True, null=True),
        ),
    ]
