# Generated by Django 5.2 on 2026-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_report_latest_revision_reporttype_latest_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="show_in_reporting_tab",
            field=models.BooleanField(
                default=True,
                help_text="Set if values from this report should be shown in reporting tab when editing the action",
                verbose_name="Show in reporting tab",
            ),
        ),
    ]
