# Generated by Django 6.0.2 on 2026-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0016_report_show_in_reporting_tab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="show_in_reporting_tab",
            field=models.BooleanField(
                default=True,
                help_text="Set if the values from this report should be shown in the reporting tab when editing the action. The values are shown only if this report has been marked as complete.",
                verbose_name="Show in reporting tab",
            ),
        ),
    ]
