# Generated by Django 6.1 on 2026-10-02 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('indicators', '0052_alter_indicatorlevel_level'),
        ('reports', '0017_alter_report_show_in_reporting_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_explicitly', models.BooleanField(default=True)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'indicator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='indicators.indicator'
                    ),
                ),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='indicator_snapshots', to='reports.report'
                    ),
                ),
            ],
            options={
                'verbose_name': 'indicator snapshot',
                'verbose_name_plural': 'indicator snapshots',
                'constraints': [
                    models.UniqueConstraint(fields=('report', 'indicator'), name='unique_indicator_snapshot_per_report')
                ],
            },
        ),
    ]
