# Generated by Django 6.1 on 2026-10-05 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0200_action_version'),
        ('indicators', '0052_alter_indicatorlevel_level'),
        ('reports', '0017_alter_report_show_in_reporting_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'action',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report_indicator_snapshots',
                        to='actions.action',
                    ),
                ),
                (
                    'indicator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='indicators.indicator'
                    ),
                ),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='indicator_snapshots', to='reports.report'
                    ),
                ),
            ],
            options={
                'verbose_name': 'indicator snapshot',
                'verbose_name_plural': 'indicator snapshots',
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('action__isnull', False)),
                        fields=('report', 'indicator', 'action'),
                        name='unique_indicator_snapshot_per_action',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('action__isnull', True)),
                        fields=('report', 'indicator'),
                        name='unique_indicator_snapshot_per_report_completion',
                    ),
                ],
            },
        ),
    ]
