# Generated by Django 3.2.12 on 2022-03-14 14:20

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title',), required_languages=(), virtual_fields=True),
        ),
    ]
