# Generated by Django 6.0.2 on 2026-03-16 08:24

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0017_allow_blank_participated_in_training"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image_cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "1280x720",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="image cropping",
            ),
        ),
    ]
