# Generated by Django 2.2.4 on 2019-10-04 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0007_add_abbreviation_field'),
        ('users', '0002_add_selected_admin_plan_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplans_admin_users', to='django_orghierarchy.Organization', verbose_name='organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_orgs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'organization')},
                'verbose_name': 'admin for organization',
                'verbose_name_plural': 'admins for organization'
            },
        ),
    ]
