# Generated by Django 3.1.5 on 2021-09-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_wagtail_editing'),
        ('users', '0005_new_organization_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationadmin',
            name='organization',
        ),
        migrations.RenameField(
            model_name='organizationadmin',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='organizationadmin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplans_admin_users', to='orgs.organization', verbose_name='organization'),
        ),
    ]
