# Generated by Django 3.2.16 on 2024-05-03 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_deactivated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deactivated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
