# Generated by Django 3.2.9 on 2022-01-17 12:37

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_add_common_indicator_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name'], required_languages=(), virtual_fields=True),
        ),
    ]
