# Generated by Django 3.2.12 on 2022-02-19 13:34

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_rename_organizationadmin_organizationplanadmin'),
        ('actions', '0009_update_languages'),
        ('indicators', '0004_add_quantity_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='identifier',
            field=aplans.utils.IdentifierField(default='', max_length=50, unique=True, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commonindicator',
            name='identifier',
            field=aplans.utils.IdentifierField(blank=True, max_length=50, null=True, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('common', 'organization')},
        ),
        migrations.CreateModel(
            name='PlanCommonIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indicators.commonindicator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actions.plan')),
            ],
        ),
        migrations.AddField(
            model_name='commonindicator',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='common_indicators', through='indicators.PlanCommonIndicator', to='actions.Plan'),
        ),
        migrations.CreateModel(
            name='RelatedCommonIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('increases', 'increases'), ('decreases', 'decreases'), ('part_of', 'is a part of')], help_text='What type of causal effect is there between the indicators', max_length=40, verbose_name='effect type')),
                ('causal_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_effects', to='indicators.commonindicator', verbose_name='causal indicator')),
                ('effect_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_causes', to='indicators.commonindicator', verbose_name='effect indicator')),
            ],
            options={
                'verbose_name': 'related indicator',
                'verbose_name_plural': 'related indicators',
                'unique_together': {('causal_indicator', 'effect_indicator')},
            },
        ),
    ]
