# Generated by Django 3.2.12 on 2022-03-24 19:37

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_add_common_indicator_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name', 'description'], required_languages=(), virtual_fields=True),
        ),
    ]
