# Generated by Django 3.2.12 on 2022-04-21 14:32

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_make_unit_translatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonindicator',
            name='normalize_by_label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='normalize by label'),
        ),
        migrations.AlterField(
            model_name='commonindicator',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name', 'description', 'normalize_by_label'], required_languages=(), virtual_fields=True),
        ),
        migrations.CreateModel(
            name='CommonIndicatorNormalizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_multiplier', models.FloatField()),
                ('normalizable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalizations', to='indicators.commonindicator')),
                ('normalizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indicators.commonindicator')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indicators.unit')),
            ],
            options={
                'unique_together': {('normalizable', 'normalizer')},
            },
        ),
        migrations.AddField(
            model_name='commonindicator',
            name='normalization_indicators',
            field=models.ManyToManyField(blank=True, related_name='normalizable_indicators', through='indicators.CommonIndicatorNormalizator', to='indicators.CommonIndicator'),
        ),
    ]
