# Generated by Django 3.2.12 on 2022-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_add_indicator_normalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='normalized_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
