# Generated by Django 3.2.13 on 2022-08-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0011_extract_unit_and_quantity_modification_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators_created_indicator', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators_updated_indicator', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
