# Generated by Django 3.2.13 on 2022-09-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0037_add_category_type_short_description_field'),
        ('indicators', '0012_add_modification_tracking_to_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorgoal',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_goals', to='actions.plan', verbose_name='plan'),
        ),
    ]
