# Generated by Django 3.2.13 on 2022-09-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_remove_plan_value_from_indicatorgoal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorgoal',
            unique_together={('indicator', 'date')},
        ),
        migrations.RemoveField(
            model_name='indicatorgoal',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='indicatorgoal',
            name='scenario',
        ),
    ]
