# Generated by Django 3.2.13 on 2023-08-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0019_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorgoal',
            name='normalized_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
