# Generated by Django 3.2.16 on 2023-11-30 13:31

import aplans.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_make_common_indicator_identifier_longer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkindicator',
            name='identifier',
            field=aplans.utils.IdentifierField(blank=True, max_length=70, null=True, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='identifier',
            field=aplans.utils.IdentifierField(blank=True, max_length=70, null=True, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
    ]
