# Generated by Django 5.0.6 on 2024-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_alter_actionindicator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='show_trendline',
            field=models.BooleanField(default=True, verbose_name='show trendline'),
        ),
    ]
