# Generated by Django 5.2 on 2025-04-28 14:20

import aplans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0031_indicator_data_categories_are_stackable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensioncategory',
            name='default_color',
            field=models.CharField(blank=True, help_text='Default color for this dimension category in charts', max_length=50, validators=[aplans.utils.validate_css_color], verbose_name='default color'),
        ),
    ]
