# Generated by Django 5.2 on 2025-07-01 17:59

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0032_dimensioncategory_default_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensioncategory',
            name='default_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', help_text='Default color for this dimension category in charts', max_length=50, verbose_name='default color'),
        ),
    ]
