# Generated by Django 5.2 on 2025-07-08 10:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models

def create_plan_dimensions(apps, schema_editor):
    IndicatorLevel = apps.get_model('indicators', 'IndicatorLevel')
    IndicatorDimension = apps.get_model('indicators', 'IndicatorDimension')
    PlanDimension = apps.get_model('indicators', 'PlanDimension')

    plan_dimension_combinations = set()

    for indicator_level in IndicatorLevel.objects.select_related('indicator', 'plan'):
        indicator = indicator_level.indicator
        plan = indicator_level.plan
        indicator_dimensions = IndicatorDimension.objects.filter(indicator=indicator)

        for indicator_dimension in indicator_dimensions:
            dimension = indicator_dimension.dimension
            plan_dimension_combinations.add((plan.id, dimension.id))

    # Create PlanDimension objects for each unique combination
    created_count = 0
    for plan_id, dimension_id in plan_dimension_combinations:
        _plan_dimension, created = PlanDimension.objects.get_or_create(
            plan_id=plan_id,
            dimension_id=dimension_id
        )
        if created:
            created_count += 1

    print(f"Created {created_count} PlanDimension objects from existing indicator relationships")


def reverse_create_plan_dimensions(apps, schema_editor):
    PlanDimension = apps.get_model('indicators', 'PlanDimension')
    deleted_count = PlanDimension.objects.count()
    PlanDimension.objects.all().delete()
    print(f"Deleted {deleted_count} PlanDimension objects")


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0140_alter_actionimplementationphase_color_and_more'),
        ('indicators', '0033_alter_dimensioncategory_default_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Used in visualizations as the Y axis maximum', null=True, verbose_name='maximum value'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Used in visualizations as the Y axis minimum', null=True, verbose_name='minimum value'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='show_total_line',
            field=models.BooleanField(default=True, help_text='Data categories can be summed to form total for the indicator (draw stacked chart as default)', verbose_name='show total line'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='show_trendline',
            field=models.BooleanField(default=True, help_text="Automatically create a trend line for the indicator's total value", verbose_name='show trend line'),
        ),
        migrations.CreateModel(
            name='PlanDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='indicators.dimension')),
                ('plan', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='actions.plan')),
            ],
            options={
                'verbose_name': 'plan dimension',
                'verbose_name_plural': 'plan dimensions',
                'unique_together': {('plan', 'dimension')},
            },
        ),
        migrations.RunPython(
            create_plan_dimensions,
            reverse_create_plan_dimensions,
    ),
    ]
