# Generated by Django 5.2 on 2025-11-07 09:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "indicators",
            "0034_alter_indicator_max_value_alter_indicator_min_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="visualizations",
            field=wagtail.fields.StreamField(
                [("raw_visualization", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.TextBlock", (), {})},
                null=True,
                verbose_name="visualizations",
            ),
        ),
    ]
