# Generated by Django 5.2 on 2025-11-12 15:23

import aplans.utils
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0035_indicator_visualizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='reference_value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_for_indicator', to='indicators.indicatorvalue', verbose_name='reference value'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='visualizations',
            field=wagtail.fields.StreamField([('raw_visualization', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'validators': (aplans.utils.validate_json,)})}, null=True, verbose_name='visualizations'),
        ),
    ]
