# Generated by Django 5.2 on 2025-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0037_alter_indicator_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='non_quantified_goal',
            field=models.CharField(blank=True, choices=[('increase', 'Increase'), ('decrease', 'Decrease')], null=True, verbose_name='non-quantified goal'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='non_quantified_goal_date',
            field=models.DateField(blank=True, null=True, verbose_name='non-quantified goal date'),
        ),
    ]
