# Generated by Django 5.2 on 2025-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0039_indicator_kausal_paths_node_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="goal_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="goal description"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="sort_key",
            field=models.CharField(
                blank=True,
                help_text="If set, this will be used as the primary criterion for sorting indicators.",
                max_length=200,
                null=True,
                verbose_name="sort key",
            ),
        ),
    ]
