# Generated by Django 5.2 on 2025-12-10 22:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0040_indicator_goal_description_indicator_sort_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="reference",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="What is the reference or source for this indicator?",
                max_length=4000,
                null=True,
                verbose_name="reference",
            ),
        ),
    ]
