# Generated by Django 5.2 on 2026-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0044_alter_plancommonindicator_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="hide_indicator_graph",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="indicator",
            name="hide_indicator_table",
            field=models.BooleanField(default=False),
        ),
    ]
