# Generated by Django 6.0.2 on 2026-05-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0049_remove_dataset_datasetlicense"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="bar_type",
            field=models.CharField(
                blank=True,
                choices=[("stacked", "Stacked bars"), ("grouped", "Grouped bars")],
                default="",
                help_text="Bar chart sub-type (only meaningful when visualization type is bar chart)",
                max_length=20,
                verbose_name="bar type",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="grouping_dimension",
            field=models.ForeignKey(
                blank=True,
                help_text="Dimension used for grouping in the default visualization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="indicators.dimension",
                verbose_name="grouping dimension",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="pie_chart_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year to display in pie chart visualization",
                null=True,
                verbose_name="pie chart year",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="visualization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bar_chart", "Bar chart"),
                    ("line_chart", "Line chart"),
                    ("area_chart", "Area chart"),
                    ("pie_chart", "Pie chart"),
                    ("summary", "Summary"),
                ],
                default="",
                help_text="Default visualization type for this indicator on dashboards",
                max_length=20,
                verbose_name="default visualization type",
            ),
        ),
    ]
