# Generated by Django 6.0.2 on 2026-05-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0050_indicator_bar_type_indicator_grouping_dimension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="bar_type",
            field=models.CharField(
                blank=True,
                choices=[("stacked", "Stacked bars"), ("grouped", "Grouped bars")],
                default="",
                help_text="Kind of bar chart (only meaningful when visualization type is bar chart)",
                max_length=20,
                verbose_name="bar type",
            ),
        ),
    ]
