# Generated by Django 3.1.5 on 2021-09-28 21:37

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email From name')),
                ('from_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email From address')),
                ('reply_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Reply-To address')),
                ('brand_dark_color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Brand dark color')),
                ('font_family', models.CharField(blank=True, max_length=200, null=True, verbose_name='Font family')),
                ('font_css_url', models.URLField(blank=True, null=True, verbose_name='Font CSS style URL')),
                ('i18n', modeltrans.fields.TranslationField(fields=['from_name'], required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'base template',
                'verbose_name_plural': 'base templates',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('content', models.TextField(help_text='HTML content for the block', verbose_name='content')),
                ('identifier', models.CharField(choices=[('intro', 'Introduction block'), ('motivation', 'Motivation block'), ('outro', 'Contact information block')], max_length=50, verbose_name='identifier')),
                ('i18n', modeltrans.fields.TranslationField(fields=['name', 'content'], required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'content block',
                'verbose_name_plural': 'content blocks',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject for email notifications', max_length=200, verbose_name='subject')),
                ('type', models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon')], max_length=100, verbose_name='type')),
                ('i18n', modeltrans.fields.TranslationField(fields=['subject'], required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon')], max_length=100, verbose_name='type')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
