# Generated by Django 3.2.12 on 2022-02-17 12:11

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210929_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='name',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['content'], required_languages=(), virtual_fields=True),
        ),
    ]
