# Generated by Django 3.2.13 on 2022-08-12 06:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='base',
            field=modelcluster.fields.ParentalKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='content_blocks', to='notifications.basetemplate'),
        ),
    ]
