# Generated by Django 3.2.13 on 2022-12-19 15:04

from django.db import migrations, models
import django.db.models.deletion


def create_notification_preferences(apps, schema_editor):
    GeneralPlanAdmin = apps.get_model('actions', 'GeneralPlanAdmin')
    GeneralPlanAdminNotificationPreferences = apps.get_model('notifications', 'GeneralPlanAdminNotificationPreferences')
    ActionContactPerson = apps.get_model('actions', 'ActionContactPerson')
    ActionContactPersonNotificationPreferences = apps.get_model('notifications', 'ActionContactPersonNotificationPreferences')
    for gpa in GeneralPlanAdmin.objects.all():
        GeneralPlanAdminNotificationPreferences.objects.create(general_plan_admin=gpa)
    for acp in ActionContactPerson.objects.all():
        ActionContactPersonNotificationPreferences.objects.create(action_contact_person=acp)


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0061_plan_version_name'),
        ('notifications', '0008_alter_basetemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon'), ('user_feedback_received', 'User feedback received')], max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon'), ('user_feedback_received', 'User feedback received')], max_length=100, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='GeneralPlanAdminNotificationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_feedback_notifications', models.BooleanField(default=True, verbose_name='receive feedback notifications')),
                ('general_plan_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='actions.generalplanadmin')),
            ],
        ),
        migrations.CreateModel(
            name='ActionContactPersonNotificationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_general_action_notifications', models.BooleanField(default=True, verbose_name='receive general action notifications')),
                ('receive_action_feedback_notifications', models.BooleanField(default=True, verbose_name='receive action feedback notifications')),
                ('action_contact_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='actions.actioncontactperson')),
            ],
        ),
        migrations.RunPython(create_notification_preferences),
    ]
