# Generated by Django 3.2.16 on 2024-02-28 14:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_custom_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='base',
            field=modelcluster.fields.ParentalKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='notifications.basetemplate'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Do not set if content block is used in multiple templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='notifications.notificationtemplate', verbose_name='template'),
        ),
    ]
