# Generated by Django 5.0.6 on 2024-09-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_rename_notificationtemplate_automaticnotificationtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentnotification',
            options={'default_manager_name': 'objects'},
        ),
    ]
