# Generated by Django 5.2 on 2025-07-01 17:59

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_sentnotification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetemplate',
            name='brand_dark_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', max_length=30, verbose_name='Brand dark color'),
        ),
    ]
