# Generated by Django 6.1 on 2026-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_pledge_participant_signup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticnotificationtemplate',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon'), ('user_feedback_received', 'User feedback received'), ('pledge_participant_signup', 'Pledge participant signed up'), ('access_requests_received', 'Access requests received')], max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon'), ('user_feedback_received', 'User feedback received'), ('pledge_participant_signup', 'Pledge participant signed up'), ('access_requests_received', 'Access requests received'), ('manually_scheduled', 'Manually scheduled notification')], max_length=100, verbose_name='type'),
        ),
    ]
