projects:
  mcp_server:
    schema: schema.graphql
    documents: mcp_server/queries.graphql
    extensions:
      turms: # path for configuration for turms
        out_dir: mcp_server/__generated__
        options:
          allow_population_by_field_name: true
        object_bases:
          - mcp_server.generated_base.ObjectBaseModel
        plugins: # path for plugin configuration
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
            inputtype_bases:
              - mcp_server.generated_base.InputTypeModel
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
            arguments_allow_population_by_field_name: true
            arguments_bases:
              - mcp_server.generated_base.ArgumentsModel
            query_bases:
              - mcp_server.generated_base.QueryModel
            mutation_bases:
              - mcp_server.generated_base.MutationModel
          - type: turms.plugins.funcs.FuncsPlugin
        stylers:
          - type: turms.stylers.snake_case.SnakeCaseStyler
          - type: mcp_server.turms_plugins.RenamerStyler
        # processors:
        #   - type: turms.processors.black.BlackProcessor
        #   - type: turms.processors.isort.IsortProcessor
        scalar_definitions:
          UUID: str
          Date: str
