# Generated by Django 3.1.5 on 2021-09-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGeneralContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=150, verbose_name='site title')),
                ('site_description', models.CharField(blank=True, max_length=150, verbose_name='site description')),
                ('owner_url', models.URLField(blank=True, verbose_name='URL for the owner of the site')),
                ('owner_name', models.CharField(blank=True, max_length=150, verbose_name='Name of the owner of the site')),
                ('official_name_description', models.CharField(blank=True, help_text='The text to show when displaying official content', max_length=200, verbose_name='official name description')),
                ('copyright_text', models.CharField(blank=True, max_length=150, verbose_name='copyright text')),
                ('creative_commons_license', models.CharField(blank=True, default='CC BY 4.0', help_text='If the site is under a Creative Commons license, which CC license it is', max_length=150, verbose_name='creative commons license')),
                ('github_api_repository', models.URLField(blank=True, verbose_name='Link to GitHub repository for API')),
                ('github_ui_repository', models.URLField(blank=True, verbose_name='Link to GitHub repository for UI')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_content', to='actions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'site general content',
                'verbose_name_plural': 'site general contents',
            },
        ),
    ]
