# Generated by Django 3.2.12 on 2022-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='accessibility_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Accessibility contact email'),
        ),
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='accessibility_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Accessibility contact name'),
        ),
    ]
