# Generated by Django 3.2.12 on 2022-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_accessibility_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='accessibility_contact_name',
        ),
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='accessibility_responsible_body',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Body responsible for site accessibility'),
        ),
    ]
