# Generated by Django 3.2.13 on 2022-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_field_to_accessibility_responsible_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='action_term',
            field=models.CharField(choices=[('action', 'Action'), ('strategy', 'Strategy')], default='action', max_length=30, verbose_name="Term to use for 'action'"),
        ),
        migrations.AlterField(
            model_name='sitegeneralcontent',
            name='accessibility_responsible_body',
            field=models.CharField(blank=True, help_text='Set if different from the owner of the site', max_length=200, null=True, verbose_name='Body responsible for site accessibility'),
        ),
    ]
