# Generated by Django 3.2.13 on 2022-10-04 09:45

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_accessibility_contact_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['site_title', 'site_description', 'official_name_description', 'copyright_text', 'creative_commons_license', 'owner_name'], required_languages=(), virtual_fields=True),
        ),
    ]
