# Generated by Django 3.2.16 on 2023-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_sitegeneralcontent_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegeneralcontent',
            name='action_term',
            field=models.CharField(choices=[('action', 'Action'), ('strategy', 'Strategy'), ('case_study', 'Case study')], default='action', max_length=30, verbose_name="Term to use for 'action'"),
        ),
    ]
