# Generated by Django 6.0.2 on 2026-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_sitegeneralcontent_latest_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitegeneralcontent",
            name="indicator_term",
            field=models.CharField(
                choices=[("indicator", "Indicator"), ("measure", "Measure")],
                default="indicator",
                max_length=30,
                verbose_name="Term to use for 'indicator'",
            ),
        ),
    ]
