# Generated by Django 5.0.6 on 2024-07-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_userfeedback_type_and_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedbacks', to='actions.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'General'), ('accessibility', 'Accessibility'), ('action', 'Action'), ('category', 'Category')], max_length=30, verbose_name='type'),
        ),
    ]
