# Generated by Django 5.0.6 on 2024-08-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_category_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='additional_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
