# Generated by Django 5.0.6 on 2024-09-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_userfeedback_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
