# Generated by Django 5.0.6 on 2024-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_userfeedback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
