# Generated by Django 5.2 on 2026-02-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0160_add_pledgecommitment_model"),
        ("feedback", "0010_alter_userfeedback_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedback",
            name="pledge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_feedbacks",
                to="actions.pledge",
                verbose_name="pledge",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "General"),
                    ("accessibility", "Accessibility"),
                    ("action", "Action"),
                    ("category", "Category"),
                    ("pledge", "Pledge"),
                ],
                max_length=30,
                verbose_name="type",
            ),
        ),
    ]
