# Generated by Django 5.0.6 on 2024-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_datasetschema_dimension_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetschema',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
