# Generated by Django 5.0.6 on 2024-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_datasetschema_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='value'),
        ),
    ]
