# Generated by Django 3.1 on 2020-08-16 10:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Image to use in the header for this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.aplansimage', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='lead_paragraph',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Lead paragraph right under the heading', null=True, verbose_name='Lead paragraph'),
        ),
        migrations.AlterField(
            model_name='planrootpage',
            name='i18n',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', label='Heading')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraph')), ('qa_section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='title', heading='Title')), ('questions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(heading='Question')), ('answer', wagtail.core.blocks.CharBlock(heading='Answer'))]), heading='Questions'))], icon='help', label='Questions & Answers'))]),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='i18n',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
