# Generated by Django 3.1.3 on 2021-01-17 15:27

import actions.blocks
from django.db import migrations, models
import django.db.models.deletion
import indicators.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('actions', '0065_add_unique_together_constraint_to_action'),
        ('pages', '0003_add_root_page_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('i18n', models.JSONField(blank=True, null=True)),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraph')), ('indicator', wagtail.core.blocks.StructBlock([('indicator', indicators.blocks.IndicatorChooserBlock())])), ('action_list', wagtail.core.blocks.StructBlock([('category_filter', actions.blocks.CategoryChooserBlock())]))])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
