# Generated by Django 3.1.5 on 2021-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0066_add_category_level_and_category_color'),
        ('pages', '0005_add_empty_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='category_page', to='actions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Heading')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraph')), ('qa_section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='title', heading='Title', required=False)), ('questions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(heading='Question')), ('answer', wagtail.core.blocks.RichTextBlock(heading='Answer'))])))], icon='help', label='Questions & Answers'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='lead_paragraph',
            field=models.TextField(blank=True, help_text='Lead paragraph right under the heading', null=True, verbose_name='Lead paragraph'),
        ),
    ]
