# Generated by Django 3.1.5 on 2021-02-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_page_category_into_onetoone'),
        ('pages', '0006_add_show_in_footer_field'),
    ]

    operations = [
    ]
