# Generated by Django 3.2.13 on 2022-12-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_legacy_plan_root_page_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilitystatementpage',
            options={'verbose_name': 'Accessibility statement page', 'verbose_name_plural': 'Accessibility statement pages'},
        ),
        migrations.AlterModelOptions(
            name='actionlistpage',
            options={'verbose_name': 'Action list page', 'verbose_name_plural': 'Action list pages'},
        ),
        migrations.AlterModelOptions(
            name='categorytypepage',
            options={'verbose_name': 'Category type page', 'verbose_name_plural': 'Category type pages'},
        ),
        migrations.AlterModelOptions(
            name='impactgrouppage',
            options={'verbose_name': 'Impact group page', 'verbose_name_plural': 'Impact group pages'},
        ),
        migrations.AlterModelOptions(
            name='indicatorlistpage',
            options={'verbose_name': 'Indicator list page', 'verbose_name_plural': 'Indicator list pages'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicypage',
            options={'verbose_name': 'Privacy policy page', 'verbose_name_plural': 'Privacy policy pages'},
        ),
    ]
