# Generated by Django 3.2.13 on 2022-12-19 18:23

import actions.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_add_action_list_page_heading_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlistpage',
            name='advanced_filters',
            field=wagtail.core.fields.StreamField([('responsible_party', actions.blocks.ResponsiblePartyFilterBlock()), ('primary_org', actions.blocks.PrimaryOrganizationFilterBlock()), ('implementation_phase', actions.blocks.ActionImplementationPhaseFilterBlock()), ('schedule', actions.blocks.ActionScheduleFilterBlock()), ('attribute', wagtail.core.blocks.StructBlock([('attribute_type', actions.blocks.ActionAttributeTypeChooserBlock(label='Attribute type', required=True)), ('show_all_label', wagtail.core.blocks.CharBlock(label="Label for 'show all'", required=False))])), ('category', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('dropdown', 'Dropdown'), ('buttons', 'Buttons')], label='Style')), ('show_all_label', wagtail.core.blocks.CharBlock(label="Label for 'show all'", required=False)), ('category_type', actions.blocks.CategoryTypeChooserBlock(label='Category type', required=True)), ('depth', wagtail.core.blocks.IntegerBlock(help_text='How many levels of category hierarchy to show', min_value=1, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlistpage',
            name='main_filters',
            field=wagtail.core.fields.StreamField([('responsible_party', actions.blocks.ResponsiblePartyFilterBlock()), ('primary_org', actions.blocks.PrimaryOrganizationFilterBlock()), ('implementation_phase', actions.blocks.ActionImplementationPhaseFilterBlock()), ('schedule', actions.blocks.ActionScheduleFilterBlock()), ('attribute', wagtail.core.blocks.StructBlock([('attribute_type', actions.blocks.ActionAttributeTypeChooserBlock(label='Attribute type', required=True)), ('show_all_label', wagtail.core.blocks.CharBlock(label="Label for 'show all'", required=False))])), ('category', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('dropdown', 'Dropdown'), ('buttons', 'Buttons')], label='Style')), ('show_all_label', wagtail.core.blocks.CharBlock(label="Label for 'show all'", required=False)), ('category_type', actions.blocks.CategoryTypeChooserBlock(label='Category type', required=True)), ('depth', wagtail.core.blocks.IntegerBlock(help_text='How many levels of category hierarchy to show', min_value=1, required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlistpage',
            name='primary_filters',
            field=wagtail.core.fields.StreamField([('responsible_party', actions.blocks.ResponsiblePartyFilterBlock()), ('primary_org', actions.blocks.PrimaryOrganizationFilterBlock()), ('implementation_phase', actions.blocks.ActionImplementationPhaseFilterBlock()), ('schedule', actions.blocks.ActionScheduleFilterBlock()), ('attribute', wagtail.core.blocks.StructBlock([('attribute_type', actions.blocks.ActionAttributeTypeChooserBlock(label='Attribute type', required=True)), ('show_all_label', wagtail.core.blocks.CharBlock(label="Label for 'show all'", required=False))])), ('category', wagtail.core.blocks.StructBlock([('style', wagtail.core.blocks.ChoiceBlock(choices=[('dropdown', 'Dropdown'), ('buttons', 'Buttons')], label='Style')), ('show_all_label', wagtail.core.blocks.CharBlock(label="Label for 'show all'", required=False)), ('category_type', actions.blocks.CategoryTypeChooserBlock(label='Category type', required=True)), ('depth', wagtail.core.blocks.IntegerBlock(help_text='How many levels of category hierarchy to show', min_value=1, required=False))]))], blank=True, null=True),
        ),
    ]
