# Generated by Django 3.2.13 on 2023-03-24 13:26

import actions.blocks.choosers
from django.db import migrations, models
import kausal_watch_extensions.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_modify_page_streamfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlistpage',
            name='include_related_plans',
            field=models.BooleanField(default=False, help_text='Enable to make this page include actions from related plans.', verbose_name='Include related plans'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraph')), ('qa_section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='title', heading='Title', required=False)), ('questions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(heading='Question')), ('answer', wagtail.core.blocks.RichTextBlock(heading='Answer'))])))], icon='help', label='Questions & Answers')), ('category_list', wagtail.core.blocks.StructBlock([('category_type', actions.blocks.choosers.CategoryTypeChooserBlock(label='Category type', required=False)), ('category', actions.blocks.choosers.CategoryChooserBlock(label='Category', required=False)), ('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Heading', required=False)), ('lead', wagtail.core.blocks.RichTextBlock(label='Lead', required=False)), ('style', wagtail.core.blocks.ChoiceBlock(choices=[('cards', 'Cards'), ('table', 'Table')]))], label='Category list')), ('category_tree_map', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', label='Heading', required=False)), ('lead', wagtail.core.blocks.RichTextBlock(label='Lead', required=False)), ('category_type', actions.blocks.choosers.CategoryTypeChooserBlock(label='Category type', required=True)), ('value_attribute', actions.blocks.choosers.CategoryAttributeTypeChooserBlock(label='Value attribute', required=True))], label='Category tree map')), ('cartography_visualisation_block', wagtail.core.blocks.StructBlock([('account', kausal_watch_extensions.blocks.CartographyProviderCredentialsChooserBlock(label='Map Provider Credentials')), ('style', wagtail.core.blocks.CharBlock(choices=[], label='Map style', required=True, validators=[])), ('style_overrides', wagtail.core.blocks.TextBlock(label='Map labels', required=False))], label='Map Visualisation'))], blank=True, null=True),
        ),
    ]
