# Generated by Django 3.2.16 on 2023-09-22 19:36

import actions.blocks.choosers
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_category_page_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytypepagelevellayout',
            name='icon_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=4, verbose_name='icon size'),
        ),
        migrations.AlterField(
            model_name='categorytypepagelevellayout',
            name='layout_main_bottom',
            field=wagtail.fields.StreamField([('attribute', wagtail.blocks.StructBlock([('attribute_type', actions.blocks.choosers.CategoryAttributeTypeChooserBlock(required=True))])), ('body', wagtail.blocks.StructBlock([])), ('category_list', wagtail.blocks.StructBlock([])), ('contact_form', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
