# Generated by Django 3.2.16 on 2023-10-30 23:09

from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation


class TransformIndicatorGroupBlock(BaseBlockOperation):
    def apply(self, block_value):
        return {
            'title': '',
            'indicators': block_value,
        }

    @property
    def operation_name_fragment(self):
        return 'migrate_indicator_group_block_to_struct_block'


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_action_dashboard_columns'),
    ]

    operations = [
        MigrateStreamData(
            app_name='pages',
            model_name='PlanRootPage',
            field_name='body',
            operations_and_block_paths=[
                (TransformIndicatorGroupBlock(), 'indicator_group'),
            ],
        ),
        MigrateStreamData(
            app_name='pages',
            model_name='CategoryPage',
            field_name='body',
            operations_and_block_paths=[
                (TransformIndicatorGroupBlock(), 'indicator_group'),
            ],
        ),
    ]
