# Generated by Django 5.0.6 on 2024-10-25 15:02

import actions.blocks.choosers
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_indicatorlistpage_display_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlistpage',
            name='include_related_plans',
            field=models.BooleanField(default=False, help_text='Enable to make this page include indicators from related plans.', verbose_name='Include related plans'),
        ),
        migrations.AlterField(
            model_name='actionlistpage',
            name='dashboard_columns',
            field=wagtail.fields.StreamField([('identifier', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('name', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('implementation_phase', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('status', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('tasks', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('responsible_parties', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('indicators', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('updated_at', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('start_date', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('end_date', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('organization', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('imact', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False))])), ('field', wagtail.blocks.StructBlock([('column_label', wagtail.blocks.CharBlock(help_text='Label for the column to be used instead of the default', label='Label', required=False)), ('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock())]))], blank=True, null=True),
        ),
    ]
