# Generated by Django 5.0.6 on 2024-12-01 13:35

import datetime
from django.db import migrations

from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import RenameStreamChildrenOperation


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0043_alter_actionlistpage_dashboard_columns"),
    ]

    operations = [
        MigrateStreamData(
            app_name='pages',
            model_name='ActionListPage',
            field_name='dashboard_columns',
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(old_name='imact', new_name='impact'), ''),
                (RenameStreamChildrenOperation(old_name='field', new_name='attribute'), ''),
                (RenameStreamChildrenOperation(old_name='indicators', new_name='related_indicators'), ''),
                (RenameStreamChildrenOperation(old_name='organization', new_name='primary_org'), ''),
            ],
            revisions_from=datetime.datetime.fromisoformat('2023-10-06 09:19:24.970584+03'),
        )
    ]
