# Generated by Django 5.2 on 2025-12-29 13:00

import reports.report_formatters
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0050_planlink_latest_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_aside",
            field=wagtail.fields.StreamField(
                [
                    ("change_log_message", 2),
                    ("schedule", 3),
                    ("contact_persons", 4),
                    ("responsible_parties", 6),
                    ("attribute", 8),
                    ("categories", 10),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "schedule"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "contact_persons"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1), ("heading", 5)]],
                        {
                            "field_name": "responsible_parties",
                            "report_value_formatter_class": reports.report_formatters.ActionResponsiblePartyReportFieldFormatter,
                        },
                    ),
                    7: (
                        "actions.blocks.choosers.ActionAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("attribute_type", 7),
                            ]
                        ],
                        {
                            "field_name": "attribute",
                            "report_value_formatter_class": reports.report_formatters.ActionAttributeTypeReportFieldFormatter,
                        },
                    ),
                    9: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("category_type", 9),
                            ]
                        ],
                        {
                            "field_name": "categories",
                            "report_value_formatter_class": reports.report_formatters.ActionCategoryReportFieldFormatter,
                        },
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_main_bottom",
            field=wagtail.fields.StreamField(
                [
                    ("section", 10),
                    ("contact_form", 26),
                    ("report_comparison", 29),
                    ("indicator_causal_chain", 30),
                    ("datasets", 34),
                    ("change_log_message", 35),
                    ("lead_paragraph", 36),
                    ("description", 37),
                    ("official_name", 40),
                    ("attribute", 41),
                    ("categories", 42),
                    ("links", 43),
                    ("tasks", 44),
                    ("merged_actions", 45),
                    ("related_actions", 46),
                    ("dependencies", 47),
                    ("related_indicators", 48),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("full-width", "Full width"), ("grid", "Grid")]},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    5: (
                        "actions.blocks.choosers.ActionAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("attribute", 6), ("categories", 8)]],
                        {"label": "Blocks"},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("heading", 1),
                                ("help_text", 2),
                                ("blocks", 9),
                            ]
                        ],
                        {"required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Heading", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Description", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the feedback field.",
                            "label": "Feedback field visible",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the feedback field required when visible.",
                            "label": "Feedback required",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the email field.",
                            "label": "Email field visible",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the email field required when visible.",
                            "label": "Email required",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Field Label", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("checkbox", "Checkbox"),
                                ("dropdown", "Dropdown"),
                            ],
                            "label": "Field Type",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Label", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Value", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("choice_label", 20), ("choice_value", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("choice_field", 22)]],
                        {"label": "Choices", "min_num": 0, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 17),
                                ("field_type", 18),
                                ("field_required", 19),
                                ("choices", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [[("form_field", 24)]],
                        {
                            "help_text": "Form fields to be shown in addition to Name, Email and Comment fields",
                            "label": "Additional form fields",
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("description", 12),
                                ("feedback_visible", 13),
                                ("feedback_required", 14),
                                ("email_visible", 15),
                                ("email_required", 16),
                                ("fields", 25),
                            ]
                        ],
                        {"required": True},
                    ),
                    27: (
                        "reports.blocks.choosers.ReportTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "reports.blocks.choosers.ReportTypeFieldChooserBlock",
                        (),
                        {"label": "UUID of report field", "required": True},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("report_type", 27), ("report_field", 28)]],
                        {},
                    ),
                    30: (
                        "actions.blocks.action_content_blocks.IndicatorCausalChainBlock",
                        (),
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the dataset?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Dataset to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    33: (
                        "actions.blocks.choosers.PlanDatasetSchemaChooserBlock",
                        (),
                        {"required": True},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("help_text", 32), ("dataset_schema", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "lead_paragraph"},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "description"},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What label should be used in the public UI for the official name?",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Description to show after the field content",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 38),
                                ("field_help_text", 4),
                                ("caption", 39),
                            ]
                        ],
                        {"field_name": "official_name"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {
                            "field_name": "attribute",
                            "report_value_formatter_class": reports.report_formatters.ActionAttributeTypeReportFieldFormatter,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {
                            "field_name": "categories",
                            "report_value_formatter_class": reports.report_formatters.ActionCategoryReportFieldFormatter,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "links"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "tasks",
                            "report_value_formatter_class": reports.report_formatters.ActionTasksFormatter,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "merged_actions"},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "related_actions"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "dependencies"},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "related_indicators",
                            "report_value_formatter_class": reports.report_formatters.ActionIndicatorsFormatter,
                        },
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_main_top",
            field=wagtail.fields.StreamField(
                [
                    ("section", 10),
                    ("contact_form", 26),
                    ("report_comparison", 29),
                    ("indicator_causal_chain", 30),
                    ("datasets", 34),
                    ("change_log_message", 35),
                    ("lead_paragraph", 36),
                    ("description", 37),
                    ("official_name", 40),
                    ("attribute", 41),
                    ("categories", 42),
                    ("links", 43),
                    ("tasks", 44),
                    ("merged_actions", 45),
                    ("related_actions", 46),
                    ("dependencies", 47),
                    ("related_indicators", 48),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("full-width", "Full width"), ("grid", "Grid")]},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    5: (
                        "actions.blocks.choosers.ActionAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("attribute", 6), ("categories", 8)]],
                        {"label": "Blocks"},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("heading", 1),
                                ("help_text", 2),
                                ("blocks", 9),
                            ]
                        ],
                        {"required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Heading", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Description", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the feedback field.",
                            "label": "Feedback field visible",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the feedback field required when visible.",
                            "label": "Feedback required",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the email field.",
                            "label": "Email field visible",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the email field required when visible.",
                            "label": "Email required",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Field Label", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("checkbox", "Checkbox"),
                                ("dropdown", "Dropdown"),
                            ],
                            "label": "Field Type",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Label", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Value", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("choice_label", 20), ("choice_value", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("choice_field", 22)]],
                        {"label": "Choices", "min_num": 0, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 17),
                                ("field_type", 18),
                                ("field_required", 19),
                                ("choices", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [[("form_field", 24)]],
                        {
                            "help_text": "Form fields to be shown in addition to Name, Email and Comment fields",
                            "label": "Additional form fields",
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("description", 12),
                                ("feedback_visible", 13),
                                ("feedback_required", 14),
                                ("email_visible", 15),
                                ("email_required", 16),
                                ("fields", 25),
                            ]
                        ],
                        {"required": True},
                    ),
                    27: (
                        "reports.blocks.choosers.ReportTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "reports.blocks.choosers.ReportTypeFieldChooserBlock",
                        (),
                        {"label": "UUID of report field", "required": True},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("report_type", 27), ("report_field", 28)]],
                        {},
                    ),
                    30: (
                        "actions.blocks.action_content_blocks.IndicatorCausalChainBlock",
                        (),
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the dataset?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Dataset to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    33: (
                        "actions.blocks.choosers.PlanDatasetSchemaChooserBlock",
                        (),
                        {"required": True},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("help_text", 32), ("dataset_schema", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "lead_paragraph"},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "description"},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What label should be used in the public UI for the official name?",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Description to show after the field content",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 38),
                                ("field_help_text", 4),
                                ("caption", 39),
                            ]
                        ],
                        {"field_name": "official_name"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {
                            "field_name": "attribute",
                            "report_value_formatter_class": reports.report_formatters.ActionAttributeTypeReportFieldFormatter,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {
                            "field_name": "categories",
                            "report_value_formatter_class": reports.report_formatters.ActionCategoryReportFieldFormatter,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "links"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "tasks",
                            "report_value_formatter_class": reports.report_formatters.ActionTasksFormatter,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "merged_actions"},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "related_actions"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "dependencies"},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "related_indicators",
                            "report_value_formatter_class": reports.report_formatters.ActionIndicatorsFormatter,
                        },
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("qa_section", 6),
                    ("indicator_group", 12),
                    ("related_indicators", 13),
                    ("category_list", 19),
                    ("action_list", 24),
                    ("embed", 29),
                    ("raw_visualization", 30),
                    ("change_log_message", 33),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 8), ("style", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("indicators", 11)]],
                        {},
                    ),
                    13: ("indicators.blocks.RelatedIndicatorsBlock", (), {}),
                    14: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 14),
                                ("category", 15),
                                ("heading", 16),
                                ("lead", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Action list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Action list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    22: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"label": "Filter on category"},
                    ),
                    23: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 20),
                                ("help_text", 21),
                                ("category_filter", 22),
                                ("group_by_category_level", 23),
                            ]
                        ],
                        {},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 25), ("height", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 27), ("full_width", 28)]],
                        {},
                    ),
                    30: ("pages.blocks.RawVisualizationBlock", (), {}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 31), ("field_help_text", 32)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorytypepagelevellayout",
            name="layout_main_bottom",
            field=wagtail.fields.StreamField(
                [
                    ("attribute", 1),
                    ("body", 2),
                    ("category_list", 2),
                    ("contact_form", 18),
                    ("datasets", 22),
                    ("change_log_message", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("attribute_type", 0)]], {}),
                    2: ("wagtail.blocks.StructBlock", [[]], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Heading", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Description", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the feedback field.",
                            "label": "Feedback field visible",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the feedback field required when visible.",
                            "label": "Feedback required",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the email field.",
                            "label": "Email field visible",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the email field required when visible.",
                            "label": "Email required",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Field Label", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("checkbox", "Checkbox"),
                                ("dropdown", "Dropdown"),
                            ],
                            "label": "Field Type",
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Label", "required": True},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Value", "required": True},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("choice_label", 12), ("choice_value", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [[("choice_field", 14)]],
                        {"label": "Choices", "min_num": 0, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 9),
                                ("field_type", 10),
                                ("field_required", 11),
                                ("choices", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("form_field", 16)]],
                        {
                            "help_text": "Form fields to be shown in addition to Name, Email and Comment fields",
                            "label": "Additional form fields",
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 3),
                                ("description", 4),
                                ("feedback_visible", 5),
                                ("feedback_required", 6),
                                ("email_visible", 7),
                                ("email_required", 8),
                                ("fields", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the dataset?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Dataset to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    21: (
                        "actions.blocks.choosers.CategoryTypeDatasetSchemaChooserBlock",
                        (),
                        {"required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 19), ("help_text", 20), ("dataset_schema", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 23), ("field_help_text", 24)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="layout main bottom",
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("qa_section", 6),
                    ("category_list", 12),
                    ("category_level_list", 19),
                    ("paths_outcome", 23),
                    ("indicator_group", 29),
                    ("dashboard_row", 42),
                    ("embed", 47),
                    ("category_tree_map", 49),
                    ("large_image", 52),
                    ("raw_visualization", 53),
                    ("change_log_message", 56),
                    ("cartography_visualisation_block", 60),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Paragraph"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    8: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 7),
                                ("category", 8),
                                ("heading", 9),
                                ("lead", 10),
                                ("style", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Category level list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Category level list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    15: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    16: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {"label": "Filter by level", "required": True},
                    ),
                    17: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths target node ID used to calculate action impacts. If not set, the default outcome node will be used.",
                            "max_length": 200,
                            "required": False,
                            "verbose_name": "Kausal Paths target node ID",
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("help_text", 14),
                                ("category_type", 15),
                                ("category_level", 16),
                                ("group_by_category_level", 17),
                                ("paths_target_node_id", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 20), ("help_text", 21), ("outcome_node_id", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    25: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 25), ("style", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.ListBlock", (27,), {}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 24), ("indicators", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    31: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    32: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("bar_type", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("show_total_line", 35),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("year", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("indicator", 31)]], {}),
                    40: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    41: ("wagtail.blocks.StructBlock", [[("text", 40)]], {}),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 34),
                                ("line_chart", 36),
                                ("area_chart", 36),
                                ("pie_chart", 38),
                                ("indicator_summary", 39),
                                ("paragraph", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 43), ("height", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 45), ("full_width", 46)]],
                        {},
                    ),
                    48: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 9),
                                ("lead", 10),
                                ("category_type", 15),
                                ("value_attribute", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 50), ("width", 51)]],
                        {},
                    ),
                    53: ("pages.blocks.RawVisualizationBlock", (), {}),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 54), ("field_help_text", 55)]],
                        {},
                    ),
                    57: (
                        "kausal_watch_extensions.blocks.CartographyProviderCredentialsChooserBlock",
                        (),
                        {"label": "Map provider credentials"},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "choices": [],
                            "label": "Map style",
                            "required": True,
                            "validators": [],
                        },
                    ),
                    59: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Map labels", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("account", 57), ("style", 58), ("style_overrides", 59)]],
                        {"label": "Map visualization"},
                    ),
                },
                null=True,
            ),
        ),
    ]
