# Generated by Django 5.2 on 2026-01-15 09:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0053_alter_categorypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 4),
                    ("category_list", 8),
                    ("indicator_group", 14),
                    ("indicator_highlights", 15),
                    ("indicator_showcase", 20),
                    ("dashboard_row", 33),
                    ("action_highlights", 34),
                    ("related_plans", 35),
                    ("cards", 40),
                    ("action_links", 46),
                    ("text", 47),
                    ("action_status_graphs", 48),
                    ("category_tree_map", 51),
                    ("large_image", 53),
                    ("embed", 57),
                    ("paths_outcome", 61),
                    ("raw_visualization", 62),
                    ("change_log_message", 65),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Big image"),
                                ("small_image", "Small image"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("layout", 0), ("image", 1), ("heading", 2), ("lead", 3)]],
                        {},
                    ),
                    5: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 5),
                                ("category", 6),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    10: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 10), ("style", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("indicators", 13)]],
                        {},
                    ),
                    15: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("page", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("body", 16),
                                ("indicator", 10),
                                ("link_button", 18),
                                ("indicator_is_normalized", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    22: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    23: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 21),
                                ("indicator", 22),
                                ("dimension", 23),
                                ("bar_type", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 21),
                                ("indicator", 22),
                                ("dimension", 23),
                                ("show_total_line", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 21),
                                ("indicator", 22),
                                ("dimension", 23),
                                ("year", 28),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("indicator", 22)]], {}),
                    31: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    32: ("wagtail.blocks.StructBlock", [[("text", 31)]], {}),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 25),
                                ("line_chart", 27),
                                ("area_chart", 27),
                                ("pie_chart", 29),
                                ("indicator_summary", 30),
                                ("paragraph", 32),
                            ]
                        ],
                        {},
                    ),
                    34: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    35: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    36: ("wagtail.blocks.CharBlock", (), {}),
                    37: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 37), ("heading", 36), ("content", 9), ("link", 9)]],
                        {},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 36), ("lead", 9), ("cards", 39)]],
                        {},
                    ),
                    41: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    42: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    43: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("lead", 42), ("category", 43)]],
                        {},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {"label": "Links"}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 45)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    47: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    48: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    49: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    50: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 49),
                                ("value_attribute", 50),
                            ]
                        ],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 52)]],
                        {},
                    ),
                    54: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 54), ("height", 55)]],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 56), ("full_width", 19)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 58), ("help_text", 59), ("outcome_node_id", 60)]],
                        {},
                    ),
                    62: ("pages.blocks.RawVisualizationBlock", (), {}),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 63), ("field_help_text", 64)]],
                        {},
                    ),
                },
            ),
        ),
    ]
