# Generated by Django 5.2 on 2026-01-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0154_add_plan_to_changelogmessages"),
        ("pages", "0054_alter_planrootpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagechangelogmessage",
            name="plan",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="actions.plan",
            ),
        ),
    ]
