# Generated by Django 5.2 on 2026-01-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0156_make_plan_non_nullable_in_changelogmessages"),
        ("pages", "0056_populate_plan_in_changelogmessages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagechangelogmessage",
            name="plan",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="actions.plan",
            ),
        ),
    ]
