# Generated by Django 5.2 on 2026-01-23 13:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0057_make_plan_non_nullable_in_changelogmessages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 4),
                    ("category_list", 8),
                    ("indicator_group", 14),
                    ("indicator_highlights", 15),
                    ("indicator_showcase", 21),
                    ("dashboard_row", 34),
                    ("action_highlights", 35),
                    ("related_plans", 36),
                    ("cards", 41),
                    ("action_links", 47),
                    ("text", 48),
                    ("action_status_graphs", 49),
                    ("category_tree_map", 52),
                    ("large_image", 54),
                    ("embed", 58),
                    ("paths_outcome", 62),
                    ("raw_visualization", 63),
                    ("change_log_message", 66),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Big image"),
                                ("small_image", "Small image"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("layout", 0), ("image", 1), ("heading", 2), ("lead", 3)]],
                        {},
                    ),
                    5: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 5),
                                ("category", 6),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    10: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 10), ("style", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("indicators", 13)]],
                        {},
                    ),
                    15: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("page", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "How many significants digits to use for the values displayed",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("body", 16),
                                ("indicator", 10),
                                ("link_button", 18),
                                ("significant_digits", 19),
                                ("indicator_is_normalized", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    23: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    24: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 22),
                                ("indicator", 23),
                                ("dimension", 24),
                                ("bar_type", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 22),
                                ("indicator", 23),
                                ("dimension", 24),
                                ("show_total_line", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 22),
                                ("indicator", 23),
                                ("dimension", 24),
                                ("year", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.StructBlock", [[("indicator", 23)]], {}),
                    32: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    33: ("wagtail.blocks.StructBlock", [[("text", 32)]], {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 26),
                                ("line_chart", 28),
                                ("area_chart", 28),
                                ("pie_chart", 30),
                                ("indicator_summary", 31),
                                ("paragraph", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    36: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    37: ("wagtail.blocks.CharBlock", (), {}),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 38), ("heading", 37), ("content", 9), ("link", 9)]],
                        {},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 37), ("lead", 9), ("cards", 40)]],
                        {},
                    ),
                    42: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    43: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    44: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("lead", 43), ("category", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {"label": "Links"}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 46)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    48: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    49: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    50: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    51: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 50),
                                ("value_attribute", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 53)]],
                        {},
                    ),
                    55: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 55), ("height", 56)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 57), ("full_width", 20)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 59), ("help_text", 60), ("outcome_node_id", 61)]],
                        {},
                    ),
                    63: ("pages.blocks.RawVisualizationBlock", (), {}),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 64), ("field_help_text", 65)]],
                        {},
                    ),
                },
            ),
        ),
    ]
