# Generated by Django 5.2 on 2026-02-06 11:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0060_add_pledge_list_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("qa_section", 6),
                    ("indicator_group", 12),
                    ("related_indicators", 13),
                    ("dashboard_row", 26),
                    ("category_list", 32),
                    ("action_list", 37),
                    ("embed", 42),
                    ("change_log_message", 45),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 8), ("style", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("indicators", 11)]],
                        {},
                    ),
                    13: ("indicators.blocks.RelatedIndicatorsBlock", (), {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    15: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    16: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 14),
                                ("indicator", 15),
                                ("dimension", 16),
                                ("bar_type", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 14),
                                ("indicator", 15),
                                ("dimension", 16),
                                ("show_total_line", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 14),
                                ("indicator", 15),
                                ("dimension", 16),
                                ("year", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.StructBlock", [[("indicator", 15)]], {}),
                    24: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    25: ("wagtail.blocks.StructBlock", [[("text", 24)]], {}),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 18),
                                ("line_chart", 20),
                                ("area_chart", 20),
                                ("pie_chart", 22),
                                ("indicator_summary", 23),
                                ("paragraph", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    28: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 27),
                                ("category", 28),
                                ("heading", 29),
                                ("lead", 30),
                                ("style", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Action list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Action list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    35: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"label": "Filter on category"},
                    ),
                    36: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 33),
                                ("help_text", 34),
                                ("category_filter", 35),
                                ("group_by_category_level", 36),
                            ]
                        ],
                        {},
                    ),
                    38: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 38), ("height", 39)]],
                        {},
                    ),
                    41: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 40), ("full_width", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 43), ("field_help_text", 44)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 4),
                    ("category_list", 8),
                    ("indicator_group", 14),
                    ("indicator_highlights", 15),
                    ("indicator_showcase", 21),
                    ("dashboard_row", 34),
                    ("action_highlights", 35),
                    ("related_plans", 36),
                    ("cards", 41),
                    ("action_links", 47),
                    ("text", 48),
                    ("action_status_graphs", 49),
                    ("category_tree_map", 52),
                    ("large_image", 54),
                    ("embed", 58),
                    ("paths_outcome", 62),
                    ("change_log_message", 65),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Big image"),
                                ("small_image", "Small image"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("layout", 0), ("image", 1), ("heading", 2), ("lead", 3)]],
                        {},
                    ),
                    5: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 5),
                                ("category", 6),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    10: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 10), ("style", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("indicators", 13)]],
                        {},
                    ),
                    15: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("page", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "How many significants digits to use for the values displayed",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("body", 16),
                                ("indicator", 10),
                                ("link_button", 18),
                                ("significant_digits", 19),
                                ("indicator_is_normalized", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    23: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    24: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 22),
                                ("indicator", 23),
                                ("dimension", 24),
                                ("bar_type", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 22),
                                ("indicator", 23),
                                ("dimension", 24),
                                ("show_total_line", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 22),
                                ("indicator", 23),
                                ("dimension", 24),
                                ("year", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.StructBlock", [[("indicator", 23)]], {}),
                    32: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    33: ("wagtail.blocks.StructBlock", [[("text", 32)]], {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 26),
                                ("line_chart", 28),
                                ("area_chart", 28),
                                ("pie_chart", 30),
                                ("indicator_summary", 31),
                                ("paragraph", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    36: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    37: ("wagtail.blocks.CharBlock", (), {}),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 38), ("heading", 37), ("content", 9), ("link", 9)]],
                        {},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 37), ("lead", 9), ("cards", 40)]],
                        {},
                    ),
                    42: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    43: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    44: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("lead", 43), ("category", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {"label": "Links"}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 46)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    48: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    49: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    50: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    51: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 50),
                                ("value_attribute", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 53)]],
                        {},
                    ),
                    55: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 55), ("height", 56)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 57), ("full_width", 20)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 59), ("help_text", 60), ("outcome_node_id", 61)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 63), ("field_help_text", 64)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("qa_section", 6),
                    ("category_list", 12),
                    ("category_level_list", 19),
                    ("paths_outcome", 23),
                    ("indicator_group", 29),
                    ("dashboard_row", 42),
                    ("embed", 47),
                    ("category_tree_map", 49),
                    ("large_image", 52),
                    ("change_log_message", 55),
                    ("cartography_visualisation_block", 59),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Paragraph"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    8: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 7),
                                ("category", 8),
                                ("heading", 9),
                                ("lead", 10),
                                ("style", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Category level list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Category level list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    15: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    16: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {"label": "Filter by level", "required": True},
                    ),
                    17: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths target node ID used to calculate action impacts. If not set, the default outcome node will be used.",
                            "max_length": 200,
                            "required": False,
                            "verbose_name": "Kausal Paths target node ID",
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("help_text", 14),
                                ("category_type", 15),
                                ("category_level", 16),
                                ("group_by_category_level", 17),
                                ("paths_target_node_id", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 20), ("help_text", 21), ("outcome_node_id", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    25: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 25), ("style", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.ListBlock", (27,), {}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 24), ("indicators", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    31: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    32: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("bar_type", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("show_total_line", 35),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("year", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("indicator", 31)]], {}),
                    40: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    41: ("wagtail.blocks.StructBlock", [[("text", 40)]], {}),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 34),
                                ("line_chart", 36),
                                ("area_chart", 36),
                                ("pie_chart", 38),
                                ("indicator_summary", 39),
                                ("paragraph", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 43), ("height", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 45), ("full_width", 46)]],
                        {},
                    ),
                    48: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 9),
                                ("lead", 10),
                                ("category_type", 15),
                                ("value_attribute", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 50), ("width", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 53), ("field_help_text", 54)]],
                        {},
                    ),
                    56: (
                        "pages.blocks.CartographyProviderCredentialsChooserBlock",
                        (),
                        {"label": "Map provider credentials"},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "choices": [],
                            "label": "Map style",
                            "required": True,
                            "validators": [],
                        },
                    ),
                    58: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Map labels", "required": False},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("account", 56), ("style", 57), ("style_overrides", 58)]],
                        {"label": "Map visualization"},
                    ),
                },
                null=True,
            ),
        ),
    ]
