# Generated by Django 6.0.2 on 2026-04-08 15:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0064_remove_aside_visualization_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytypepagelevellayout",
            name="layout_main_top",
            field=wagtail.fields.StreamField(
                [("attribute", 1), ("progress", 3), ("paths_node_summary", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("attribute_type", 0)]], {}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("implementation_phase", "Implementation phase"),
                                ("status", "Status"),
                            ],
                            "label": "Basis",
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("basis", 2)]], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Paths node summary?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths target node ID used to calculate action impacts. If not set, the default outcome node will be used.",
                            "max_length": 200,
                            "required": False,
                            "verbose_name": "Kausal Paths target node ID",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("paths_target_node_id", 5)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="layout main top",
            ),
        ),
    ]
