# Generated by Django 6.0.2 on 2026-05-29 12:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0067_alter_categorypage_body_alter_planrootpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 8),
                    ("category_list", 12),
                    ("indicator_group", 18),
                    ("indicator_highlights", 19),
                    ("indicator_showcase", 25),
                    ("dashboard_row", 38),
                    ("action_highlights", 39),
                    ("related_plans", 40),
                    ("cards", 45),
                    ("action_links", 51),
                    ("text", 52),
                    ("action_status_graphs", 53),
                    ("category_tree_map", 56),
                    ("large_image", 58),
                    ("embed", 64),
                    ("paths_outcome", 68),
                    ("change_log_message", 71),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Big image"),
                                ("small_image", "Small image"),
                                (
                                    "side_by_side",
                                    "Side-by-side: image left, content right",
                                ),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CSS colour value, e.g. #FFFFFF or rgb(255, 255, 255)",
                            "label": "Background colour",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show the image at its exact scaled dimensions; it will never be cropped",
                            "label": "Fit image without clipping",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Display a brand color accent bar below the image",
                            "label": "Show image accent",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_colour", 4),
                                ("fit_image", 5),
                                ("show_image_accent", 6),
                            ]
                        ],
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("image", 1),
                                ("heading", 2),
                                ("lead", 3),
                                ("additional_settings", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 9),
                                ("category", 10),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 14), ("style", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("indicators", 17)]],
                        {},
                    ),
                    19: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    20: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("page", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "How many significants digits to use for the values displayed",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    24: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 13),
                                ("body", 20),
                                ("indicator", 14),
                                ("link_button", 22),
                                ("significant_digits", 23),
                                ("indicator_is_normalized", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    27: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    28: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 26),
                                ("indicator", 27),
                                ("dimension", 28),
                                ("bar_type", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 26),
                                ("indicator", 27),
                                ("dimension", 28),
                                ("show_total_line", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 26),
                                ("indicator", 27),
                                ("dimension", 28),
                                ("year", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("wagtail.blocks.StructBlock", [[("indicator", 27)]], {}),
                    36: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    37: ("wagtail.blocks.StructBlock", [[("text", 36)]], {}),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 30),
                                ("line_chart", 32),
                                ("area_chart", 32),
                                ("pie_chart", 34),
                                ("indicator_summary", 35),
                                ("paragraph", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    40: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    41: ("wagtail.blocks.CharBlock", (), {}),
                    42: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 42),
                                ("heading", 41),
                                ("content", 13),
                                ("link", 13),
                            ]
                        ],
                        {},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("lead", 13), ("cards", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    47: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    48: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 46), ("lead", 47), ("category", 48)]],
                        {},
                    ),
                    50: ("wagtail.blocks.ListBlock", (49,), {"label": "Links"}),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 50)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    52: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    53: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    54: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    55: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 54),
                                ("value_attribute", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 57)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers describe this embedded content",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers understand what this embed shows",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    61: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    62: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 61), ("height", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 59),
                                ("description", 60),
                                ("embed", 63),
                                ("full_width", 24),
                            ]
                        ],
                        {},
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 65), ("help_text", 66), ("outcome_node_id", 67)]],
                        {},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 69), ("field_help_text", 70)]],
                        {},
                    ),
                },
            ),
        ),
    ]
