# Generated by Django 6.0.2 on 2026-05-25 13:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0067_alter_categorypage_body_alter_planrootpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 7),
                    ("category_list", 11),
                    ("indicator_group", 17),
                    ("indicator_highlights", 18),
                    ("indicator_showcase", 24),
                    ("dashboard_row", 37),
                    ("action_highlights", 38),
                    ("related_plans", 39),
                    ("cards", 44),
                    ("action_links", 50),
                    ("text", 51),
                    ("action_status_graphs", 52),
                    ("category_tree_map", 55),
                    ("large_image", 57),
                    ("embed", 63),
                    ("paths_outcome", 67),
                    ("change_log_message", 70),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Big image"),
                                ("small_image", "Small image"),
                                (
                                    "side_by_side",
                                    "Side-by-side: image left, content right",
                                ),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CSS colour value, e.g. #ffffff or rgb(255,255,255)",
                            "label": "Background colour",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show the image at its exact scaled dimensions; it will never be cropped",
                            "label": "Fit image without clipping",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("background_colour", 4), ("fit_image", 5)]],
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("image", 1),
                                ("heading", 2),
                                ("lead", 3),
                                ("additional_settings", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 8),
                                ("category", 9),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 13), ("style", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("indicators", 16)]],
                        {},
                    ),
                    18: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    19: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    20: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 12), ("page", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "How many significants digits to use for the values displayed",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    23: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 12),
                                ("body", 19),
                                ("indicator", 13),
                                ("link_button", 21),
                                ("significant_digits", 22),
                                ("indicator_is_normalized", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    26: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    27: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 25),
                                ("indicator", 26),
                                ("dimension", 27),
                                ("bar_type", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 25),
                                ("indicator", 26),
                                ("dimension", 27),
                                ("show_total_line", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 25),
                                ("indicator", 26),
                                ("dimension", 27),
                                ("year", 32),
                            ]
                        ],
                        {},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("indicator", 26)]], {}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: ("wagtail.blocks.StructBlock", [[("text", 35)]], {}),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 29),
                                ("line_chart", 31),
                                ("area_chart", 31),
                                ("pie_chart", 33),
                                ("indicator_summary", 34),
                                ("paragraph", 36),
                            ]
                        ],
                        {},
                    ),
                    38: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    39: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    40: ("wagtail.blocks.CharBlock", (), {}),
                    41: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 41),
                                ("heading", 40),
                                ("content", 12),
                                ("link", 12),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 40), ("lead", 12), ("cards", 43)]],
                        {},
                    ),
                    45: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    46: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    47: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 45), ("lead", 46), ("category", 47)]],
                        {},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {"label": "Links"}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 49)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    51: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    52: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    53: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    54: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 53),
                                ("value_attribute", 54),
                            ]
                        ],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 56)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers describe this embedded content",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers understand what this embed shows",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    60: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 60), ("height", 61)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 58),
                                ("description", 59),
                                ("embed", 62),
                                ("full_width", 23),
                            ]
                        ],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 64), ("help_text", 65), ("outcome_node_id", 66)]],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 68), ("field_help_text", 69)]],
                        {},
                    ),
                },
            ),
        ),
    ]
