# Generated by Django 6.0.2 on 2026-06-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0068_alter_categorypage_body_alter_planrootpage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorytypepagelevellayout",
            name="layout_aside",
        ),
    ]
