# Generated by Django 6.0.2 on 2026-06-03 10:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0068_alter_categorypage_body_alter_planrootpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 8),
                    ("category_list", 12),
                    ("indicator_group", 18),
                    ("indicator_highlights", 19),
                    ("indicator_showcase", 25),
                    ("dashboard_row", 40),
                    ("action_highlights", 41),
                    ("related_plans", 42),
                    ("cards", 47),
                    ("action_links", 53),
                    ("text", 54),
                    ("action_status_graphs", 55),
                    ("category_tree_map", 58),
                    ("large_image", 60),
                    ("embed", 66),
                    ("paths_outcome", 70),
                    ("change_log_message", 73),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Full-width: content over image"),
                                (
                                    "small_image",
                                    "Large image: image above, content below",
                                ),
                                (
                                    "side_by_side",
                                    "Side-by-side: image left, content right",
                                ),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CSS colour value, e.g. #FFFFFF or rgb(255, 255, 255)",
                            "label": "Background colour",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show the image at its exact scaled dimensions; it will never be cropped",
                            "label": "Fit image without clipping",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Display a brand color accent bar below the image",
                            "label": "Show image accent",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_colour", 4),
                                ("fit_image", 5),
                                ("show_image_accent", 6),
                            ]
                        ],
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("image", 1),
                                ("heading", 2),
                                ("lead", 3),
                                ("additional_settings", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 9),
                                ("category", 10),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 14), ("style", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("indicators", 17)]],
                        {},
                    ),
                    19: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    20: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    21: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("page", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "How many significants digits to use for the values displayed",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    24: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 13),
                                ("body", 20),
                                ("indicator", 14),
                                ("link_button", 22),
                                ("significant_digits", 23),
                                ("indicator_is_normalized", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    27: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    28: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 26),
                                ("indicator", 27),
                                ("dimension", 28),
                                ("bar_type", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 26),
                                ("indicator", 27),
                                ("dimension", 28),
                                ("show_total_line", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 26),
                                ("indicator", 27),
                                ("dimension", 28),
                                ("year", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("wagtail.blocks.StructBlock", [[("indicator", 27)]], {}),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("text", 36)]], {}),
                    38: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    39: ("wagtail.blocks.StructBlock", [[("text", 38)]], {}),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 30),
                                ("line_chart", 32),
                                ("area_chart", 32),
                                ("pie_chart", 34),
                                ("indicator_summary", 35),
                                ("header", 37),
                                ("paragraph", 39),
                            ]
                        ],
                        {},
                    ),
                    41: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    42: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    43: ("wagtail.blocks.CharBlock", (), {}),
                    44: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 44),
                                ("heading", 43),
                                ("content", 13),
                                ("link", 13),
                            ]
                        ],
                        {},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 43), ("lead", 13), ("cards", 46)]],
                        {},
                    ),
                    48: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    49: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    50: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 48), ("lead", 49), ("category", 50)]],
                        {},
                    ),
                    52: ("wagtail.blocks.ListBlock", (51,), {"label": "Links"}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 52)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    54: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    55: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    56: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    57: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 56),
                                ("value_attribute", 57),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 59)]],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers describe this embedded content",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers understand what this embed shows",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    63: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 63), ("height", 64)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 61),
                                ("description", 62),
                                ("embed", 65),
                                ("full_width", 24),
                            ]
                        ],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 67), ("help_text", 68), ("outcome_node_id", 69)]],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 71), ("field_help_text", 72)]],
                        {},
                    ),
                },
            ),
        ),
    ]
