# Generated by Django 6.0.2 on 2026-06-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0071_preserve_indicator_value_highlight_goal_met"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorytypepagelevellayout",
            name="layout_aside",
        ),
    ]
