# Generated by Django 3.1.5 on 2021-09-21 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='A primary name, e.g. a legally recognized name', max_length=255)),
                ('abbreviation', models.CharField(blank=True, help_text='A commonly used abbreviation', max_length=50)),
                ('distinct_name', models.CharField(editable=False, help_text='A distinct name for this organization (generated automatically)', max_length=400, null=True)),
                ('founding_date', models.DateField(blank=True, help_text='A date of founding', null=True)),
                ('dissolution_date', models.DateField(blank=True, help_text='A date of dissolution', null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('last_modified_time', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('last_modified_time', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=255)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.namespace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='An organization category, e.g. committee', null=True, on_delete=django.db.models.deletion.PROTECT, to='orgs.organizationclass'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_organizations_new', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationidentifier',
            constraint=models.UniqueConstraint(fields=('namespace', 'identifier'), name='unique_identifier_in_namespace'),
        ),
    ]
