# Generated by Django 3.1.5 on 2021-09-21 15:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationidentifier',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationidentifier',
            name='organization',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='orgs.organization'),
        ),
    ]
