# Generated by Django 3.1.13 on 2021-11-11 15:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_user'),
        ('actions', '0005_add_action_primary_org'),
        ('orgs', '0003_auto_20210929_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admins', to='orgs.organization', verbose_name='organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admins', to='people.person', verbose_name='person')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admins', to='actions.plan', verbose_name='plan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organizationadmin',
            constraint=models.UniqueConstraint(fields=('organization', 'plan', 'person'), name='unique_organization_admin'),
        ),
    ]
