# Generated by Django 3.2.12 on 2022-03-21 16:45

import aplans.fields
from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_organization_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_language',
            field=aplans.fields.LanguageChoiceField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=aplans.fields.get_default_language, max_length=8),
        ),
        migrations.AlterField(
            model_name='organization',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name', 'abbreviation'), required_languages=(), virtual_fields=True),
        ),
    ]
