# Generated by Django 3.2.12 on 2022-04-26 15:58

import kausal_common.i18n.helpers
from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_organization_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=kausal_common.i18n.helpers.get_default_language, max_length=8),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
    ]
