# Generated by Django 3.2.13 on 2022-08-08 17:42

import aplans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_add_organization_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default=aplans.utils.get_default_language, max_length=8),
        ),
    ]
