# Generated by Django 3.2.13 on 2022-08-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_add_internal_abbreviation_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='A simplified short version of name for the general public', max_length=50, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='internal_abbreviation',
            field=models.CharField(blank=True, help_text='An internally used abbreviation', max_length=50, verbose_name='Internal abbreviation'),
        ),
    ]
