# Generated by Django 3.2.13 on 2023-06-14 10:57

import aplans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-GB', 'English (United Kingdom)'), ('en-AU', 'English (Australia)'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('es-US', 'Spanish (United States)'), ('es', 'Spanish')], default=aplans.utils.get_default_language, max_length=8),
        ),
    ]
