# Generated by Django 3.2.16 on 2024-03-21 11:29

import aplans.utils
from django.db import migrations, models


def set_default_language_lowercase(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    for instance in Organization.objects.all():
        instance.primary_language_lowercase = instance.primary_language.lower()
        instance.save(update_fields=['primary_language_lowercase'])


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_alter_organization_primary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_language_lowercase',
            field=models.CharField(default=aplans.utils.get_default_language_lowercase, max_length=8),
        ),
        migrations.RunPython(set_default_language_lowercase, migrations.RunPython.noop)
    ]
