# Generated by Django 2.1.3 on 2018-11-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_orghierarchy', '0007_auto_20181111_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('official_name', models.CharField(blank=True, help_text='The name as approved by an official party', max_length=100, null=True, verbose_name='official name')),
                ('identifier', models.CharField(help_text='The identifier for this action (e.g. number)', max_length=50, verbose_name='identifier')),
                ('description', models.TextField(blank=True, null=True)),
                ('impact', models.IntegerField(blank=True, help_text='The impact this action has in measurable quantity (e.g. t CO₂e)', null=True, verbose_name='impact')),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
                'ordering': ('plan', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ActionResponsibleParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_orghierarchy.Organization')),
            ],
            options={
                'ordering': ['action', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ActionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('begins_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('plan', 'order'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='identifier')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
            },
        ),
        migrations.AddField(
            model_name='actionschedule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Plan'),
        ),
        migrations.AddField(
            model_name='action',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Plan'),
        ),
        migrations.AddField(
            model_name='action',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, through='actions.ActionResponsibleParty', to='django_orghierarchy.Organization', verbose_name='responsible parties'),
        ),
        migrations.AddField(
            model_name='action',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='actions.ActionSchedule'),
        ),
        migrations.AlterIndexTogether(
            name='actionschedule',
            index_together={('plan', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='actionresponsibleparty',
            index_together={('action', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='action',
            index_together={('plan', 'order')},
        ),
    ]
