# Generated by Django 2.1.3 on 2018-11-13 14:50

import actions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_orghierarchy', '0007_auto_20181111_2316'),
        ('indicators', '0001_initial'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='indicators.Indicator', verbose_name='indicators'),
        ),
        migrations.AddField(
            model_name='action',
            name='plan',
            field=models.ForeignKey(default=actions.models.latest_plan, on_delete=django.db.models.deletion.CASCADE, to='actions.Plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='action',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, through='actions.ActionResponsibleParty', to='django_orghierarchy.Organization', verbose_name='responsible parties'),
        ),
        migrations.AddField(
            model_name='action',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='actions.ActionSchedule', verbose_name='schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('plan', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytype',
            unique_together={('plan', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('type', 'identifier')},
        ),
        migrations.AlterIndexTogether(
            name='actionschedule',
            index_together={('plan', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='actionresponsibleparty',
            index_together={('action', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='action',
            index_together={('plan', 'order')},
        ),
    ]
