# Generated by Django 2.1.3 on 2018-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20181114_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'get_latest_by': 'created_at', 'ordering': ('created_at',), 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='actionschedule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
