# Generated by Django 2.1.3 on 2018-12-12 17:06

import aplans.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0003_increase_action_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('identifier', aplans.utils.IdentifierField(max_length=20, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
            ],
            options={
                'verbose_name': 'action status',
                'verbose_name_plural': 'action statuses',
            },
        ),
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('state', models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], max_length=20, verbose_name='state')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'action task',
                'verbose_name_plural': 'action tasks',
                'ordering': ('action', 'due_at'),
            },
        ),
        migrations.AddField(
            model_name='action',
            name='completion',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='The completion percentage for this action', null=True, verbose_name='completion'),
        ),
        migrations.AlterField(
            model_name='action',
            name='identifier',
            field=aplans.utils.IdentifierField(help_text='The identifier for this action (e.g. number)', max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='category',
            name='identifier',
            field=aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='actions.Category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='actions.CategoryType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='identifier',
            field=aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='identifier',
            field=aplans.utils.IdentifierField(max_length=50, unique=True, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='identifier',
            field=aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='actions.Plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='actiontask',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='actions.Action', verbose_name='action'),
        ),
        migrations.AddField(
            model_name='actiontask',
            name='completed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='completed by'),
        ),
        migrations.AddField(
            model_name='actionstatus',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_statuses', to='actions.Plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.ActionStatus', verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='actionstatus',
            unique_together={('plan', 'identifier')},
        ),
    ]
