# Generated by Django 2.1.3 on 2018-12-14 18:38

import actions.models
import aplans.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('actions', '0004_add_action_tasks_and_state_and_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDecisionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('identifier', aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_decision_levels', to='actions.Plan', verbose_name='plan')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to='people.Person', verbose_name='contact persons'),
        ),
        migrations.AlterField(
            model_name='action',
            name='plan',
            field=models.ForeignKey(default=actions.models.latest_plan, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='actions.Plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='actionschedule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_schedules', to='actions.Plan'),
        ),
        migrations.AddField(
            model_name='action',
            name='decision_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='actions.ActionDecisionLevel', verbose_name='decision-making level'),
        ),
        migrations.AlterUniqueTogether(
            name='actiondecisionlevel',
            unique_together={('plan', 'identifier')},
        ),
    ]
