# Generated by Django 3.1.5 on 2021-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_add_action_primary_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='schedule_continuous',
            field=models.BooleanField(default=False, help_text='Set if the action does not have a start or an end date', verbose_name='continuous action'),
        ),
    ]
