# Generated by Django 2.1.3 on 2019-01-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_alter_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionresponsibleparty',
            options={'ordering': ['action', 'order'], 'verbose_name': 'action responsible party', 'verbose_name_plural': 'action responsible parties'},
        ),
        migrations.AddField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='org',
            field=models.ForeignKey(limit_choices_to=models.Q(dissolution_date=None), on_delete=django.db.models.deletion.CASCADE, to='django_orghierarchy.Organization', verbose_name='organization'),
        ),
    ]
