# Generated by Django 3.1.13 on 2021-11-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_add_action_continuous_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='select_widget',
            field=models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], default='multiple', max_length=30),
            preserve_default=False,
        ),
    ]
