# Generated by Django 2.1.3 on 2019-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_add_action_indicator_model'),
        ('actions', '0007_add_action_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='indicators_new',
            field=models.ManyToManyField(blank=True, related_name='actions', through='indicators.ActionIndicator', to='indicators.Indicator', verbose_name='indicators'),
        ),
    ]
