# Generated by Django 2.1.3 on 2019-01-15 10:01

from django.db import migrations


def migrate_indicators(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    ActionIndicator = apps.get_model('indicators', 'ActionIndicator')
    for action in Action.objects.filter(indicators__isnull=False).distinct():
        indicators = action.indicators.all()
        for ind in indicators:
            ActionIndicator.objects.create(action=action, indicator=ind, effect_type='increases')


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0008_add_action_indicator_model'),
    ]

    operations = [
        migrations.RunPython(migrate_indicators),
    ]
