# Generated by Django 3.2.9 on 2022-02-17 11:36

import actions.models.plan
import aplans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_add_plan_domain_base_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=actions.models.plan.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=actions.models.plan.get_default_language, max_length=8),
        ),
    ]
