# Generated by Django 3.2.12 on 2022-02-21 05:07

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_add_related_plans_field_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name', 'short_name'], required_languages=(), virtual_fields=True),
        ),
    ]
