# Generated by Django 2.1.5 on 2019-01-18 13:04

import aplans.utils
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_rename_indicators_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, upload_to=aplans.utils.image_upload_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1280x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=aplans.utils.image_upload_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1280x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, upload_to=aplans.utils.image_upload_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1280x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
    ]
