# Generated by Django 3.2.12 on 2022-02-23 18:48

from django.db import migrations, models


def migrate_general_plan_admins(apps, schema_editor):
    Plan = apps.get_model('actions', 'Plan')
    for row in Plan.general_admins.through.objects.all():
        user = row.user
        try:
            person = user.person
        except user._meta.model.person.RelatedObjectDoesNotExist:
            print(f"User with email {user.email} has no person and will lose general plan admin status.")
        else:
            Plan.general_admin_persons.through.objects.create(person=person, plan=row.plan)


def migrate_general_plan_admins_reverse(apps, schema_editor):
    Plan = apps.get_model('actions', 'Plan')
    for row in Plan.general_admin_persons.through.objects.all():
        Plan.general_admins.through.objects.create(user=row.person.user, plan=row.plan)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_user'),
        ('actions', '0011_add_plan_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='general_admin_persons',
            field=models.ManyToManyField(blank=True, help_text='Persons that can modify everything related to the action plan', related_name='general_admin_plans', to='people.Person', verbose_name='general administrators'),
        ),
        migrations.RunPython(migrate_general_plan_admins, migrate_general_plan_admins_reverse),
        migrations.RemoveField(
            model_name='plan',
            name='general_admins',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='general_admin_persons',
            new_name='general_admins',
        ),
    ]
