# Generated by Django 2.1.5 on 2019-01-21 14:20

import aplans.model_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_add_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=aplans.model_images.image_upload_path, verbose_name='image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=aplans.model_images.image_upload_path, verbose_name='image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=aplans.model_images.image_upload_path, verbose_name='image', width_field='image_width'),
        ),
    ]
