# Generated by Django 2.1.5 on 2019-01-23 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0013_add_image_height_and_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('plan', 'order'), 'permissions': (('admin_task', 'Can administrate all actions'),), 'verbose_name': 'action', 'verbose_name_plural': 'actions'},
        ),
        migrations.AddField(
            model_name='plan',
            name='general_admins',
            field=models.ManyToManyField(blank=True, help_text='Users that can modify everything related to the action plan', related_name='general_admin_plans', to=settings.AUTH_USER_MODEL, verbose_name='general administrators'),
        ),
        migrations.AlterField(
            model_name='action',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, related_name='contact_for_actions', to='people.Person', verbose_name='contact persons'),
        ),
    ]
