# Generated by Django 2.1.5 on 2019-01-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_add_plan_general_admins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('plan', 'order'), 'permissions': (('admin_action', 'Can administrate all actions'),), 'verbose_name': 'action', 'verbose_name_plural': 'actions'},
        ),
    ]
