# Generated by Django 2.1.7 on 2019-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_fix_perm_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='actions_locked',
            field=models.BooleanField(default=False, help_text='Can actions be added and the official metadata edited?', verbose_name='actions locked'),
        ),
    ]
