# Generated by Django 2.1.7 on 2019-04-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_add_plan_actions_locked_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionschedule',
            options={'ordering': ('plan', 'begins_at'), 'verbose_name': 'action schedule', 'verbose_name_plural': 'action schedules'},
        ),
        migrations.AlterIndexTogether(
            name='actionschedule',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='actionschedule',
            name='order',
        ),
    ]
