# Generated by Django 2.2 on 2019-04-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_remove_ordering_from_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='responsible_parties',
            field=models.ManyToManyField(blank=True, related_name='responsible_actions', through='actions.ActionResponsibleParty', to='django_orghierarchy.Organization', verbose_name='responsible parties'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_types', to='actions.Plan'),
        ),
    ]
