# Generated by Django 2.2.4 on 2019-08-12 07:22

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_alter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('identifier', aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_impacts', to='actions.Plan', verbose_name='plan')),
            ],
            options={
                'ordering': ('plan', 'order'),
                'unique_together': {('plan', 'identifier')},
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='impact',
        ),
        migrations.AddField(
            model_name='action',
            name='impact',
            field=models.ForeignKey(blank=True, help_text='The impact of this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='actions.ActionImpact', verbose_name='impact'),
        ),
    ]
