# Generated by Django 3.2.12 on 2022-03-21 19:31

import aplans.fields
import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_i18n'),
        ('actions', '0018_migrate_plan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name', 'official_name', 'description', 'manual_status_reason'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='actiondecisionlevel',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='actionimpact',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='actionimplementationphase',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_actions', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='actionschedule',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='actionstatus',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name', 'comment'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name', 'short_description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='impactgroup',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='monitoringqualitypoint',
            name='i18n',
            field=i18n.fields.TranslationField(fields=('name', 'description_yes', 'description_no'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='i18n',
            field=i18n.fields.TranslationField(fields=['name', 'short_name'], required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=aplans.fields.LanguageChoiceField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=aplans.fields.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_language',
            field=aplans.fields.LanguageChoiceField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=aplans.fields.get_default_language, max_length=8),
        ),
    ]
