# Generated by Django 2.2.4 on 2019-08-13 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_add_action_impact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='internal_priority',
            field=models.PositiveIntegerField(null=True, verbose_name='internal priority'),
        ),
        migrations.AddField(
            model_name='action',
            name='internal_priority_comment',
            field=models.TextField(blank=True, null=True, verbose_name='internal priority comment'),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
    ]
