# Generated by Django 2.2.4 on 2019-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_add_action_internal_priority_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionimpact',
            options={'ordering': ('plan', 'order'), 'verbose_name': 'action impact class', 'verbose_name_plural': 'action impact classes'},
        ),
        migrations.AlterField(
            model_name='action',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='actionimpact',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
