# Generated by Django 3.2.12 on 2022-04-11 12:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_organization_i18n'),
        ('actions', '0021_add_plan_theme_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionattributetypechoiceoption',
            options={
                'ordering': ('type', 'order'),
                'verbose_name': 'action attribute choice option',
                'verbose_name_plural': 'action attribute choice options',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryattributetype',
            options={'verbose_name': 'category attribute', 'verbose_name_plural': 'category attributes'},
        ),
        migrations.AlterModelOptions(
            name='categoryattributetypechoiceoption',
            options={
                'ordering': ('type', 'order'),
                'verbose_name': 'category attribute choice option',
                'verbose_name_plural': 'category attribute choice options',
            },
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='responsible_actions',
                to='orgs.organization',
                verbose_name='organization',
            ),
        ),
        migrations.AlterField(
            model_name='categoryattributechoice',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='choice_attributes',
                to='actions.categoryattributetype',
            ),
        ),
        migrations.AlterField(
            model_name='categoryattributetype',
            name='format',
            field=models.CharField(
                choices=[
                    ('ordered_choice', 'Ordered choice'),
                    ('optional_choice', 'Optional choice with optional text'),
                    ('rich_text', 'Rich text'),
                    ('numeric', 'Numeric'),
                ],
                max_length=50,
                verbose_name='Format',
            ),
        ),
        migrations.AlterField(
            model_name='categoryattributetypechoiceoption',
            name='type',
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='choice_options',
                to='actions.categoryattributetype',
            ),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='allow_images_for_actions',
            field=models.BooleanField(
                default=True,
                help_text='Should custom images for individual actions be allowed',
                verbose_name='Allow images for actions',
            ),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='has_action_identifiers',
            field=models.BooleanField(
                default=True,
                help_text='Set if the plan uses meaningful action identifiers',
                verbose_name='Has action identifiers',
            ),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='has_action_lead_paragraph',
            field=models.BooleanField(
                default=True,
                help_text='Set if the plan uses the lead paragraph field',
                verbose_name='Has action lead paragraph',
            ),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='has_action_official_name',
            field=models.BooleanField(
                default=False,
                help_text='Set if the plan uses the official name field',
                verbose_name='Has action official name field',
            ),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='show_admin_link',
            field=models.BooleanField(
                default=False,
                help_text='Should the public website contain a link to the admin login?',
                verbose_name='Show admin link',
            ),
        ),
        migrations.CreateModel(
            name='CategoryAttributeChoiceWithText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Text')),
                ('category', modelcluster.fields.ParentalKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='choice_with_text_attributes',
                    to='actions.category'),
                 ),
                ('choice', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='choice_with_text_attributes',
                    to='actions.categoryattributetypechoiceoption'),
                 ),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='choice_with_text_attributes',
                    to='actions.categoryattributetype'),
                 ),
            ],
            options={
                'unique_together': {('category', 'type')},
            },
        ),
    ]
