# Generated by Django 2.2.4 on 2019-09-12 15:03

from django.db import migrations


def migrate_contact_persons(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    ActionContactPerson = apps.get_model('actions', 'ActionContactPerson')
    for action in Action.objects.all():
        for idx, person in enumerate(action.contact_persons.all()):
            obj = ActionContactPerson(action=action, person=person, order=idx + 1)
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0022_add_through_table_for_contact_persons'),
    ]

    operations = [
        migrations.RunPython(migrate_contact_persons),
    ]
