# Generated by Django 2.2.4 on 2019-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_migrate_contact_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='contact_persons',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='contact_persons_ordered',
            new_name='contact_persons'
        ),
    ]
