# Generated by Django 2.2.4 on 2019-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0024_rename_contact_persons_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='official_name',
            field=models.CharField(blank=True, help_text='The name as approved by an official party', max_length=1000, null=True, verbose_name='official name'),
        ),
    ]
