# Generated by Django 3.2.12 on 2022-05-06 14:42

from django.db import migrations, models
import django.db.models.deletion


def migrate_related_actions(apps, schema_editor):
    RelatedAction = apps.get_model('actions', 'RelatedAction')
    for obj in RelatedAction.objects.all():
        if obj.action.id != obj.related_action.id and obj.related_action not in obj.action.related_actions_new.all():
            obj.action.related_actions_new.add(obj.related_action)
            # Django should add the reverse relationship as well since the ManyToManyField is assumed to be
            # symmetrical if it has `to='self'`. Note that the automatically generated migrations transform "self" into the
            # model name, so if we used that we'd have to manually add the reverse relationship.
            assert obj.action in obj.related_action.related_actions_new.all()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_add_plan_parent_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='related_actions_unordered',
        ),
        migrations.AddField(
            model_name='action',
            name='related_actions_new',
            field=models.ManyToManyField(blank=True, related_name='_actions_action_related_actions_+', to='self'),
            # field=models.ManyToManyField(blank=True, related_name='_actions_action_related_actions_+', to='actions.action'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_actions', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.RunPython(migrate_related_actions),
        migrations.DeleteModel(
            name='RelatedAction',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='related_actions_new',
            new_name='related_actions',
        ),
    ]
