# Generated by Django 2.2.4 on 2019-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_official_name_into_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='site URL'),
        ),
    ]
