# Generated by Django 2.2.4 on 2019-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0026_add_site_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontask',
            name='due_at',
            field=models.DateField(verbose_name='due date'),
        ),
    ]
