# Generated by Django 2.2.4 on 2019-09-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0027_make_actiontask_due_at_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstatus',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
    ]
