# Generated by Django 3.2.13 on 2022-06-29 14:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_common_categories'),
        ('wagtailsvg', '0004_remove_svg_edit_code'),
        ('actions', '0028_common_category_icon_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryicon',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.aplansimage'),
        ),
        migrations.AddField(
            model_name='categoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryicon',
            name='svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailsvg.svg'),
        ),
        migrations.AddField(
            model_name='commoncategoryicon',
            name='svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailsvg.svg'),
        ),
        migrations.AddField(
            model_name='commoncategoryicon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='actions.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='commoncategoryicon',
            name='common_category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='actions.commoncategory', verbose_name='common category'),
        ),
        migrations.AlterField(
            model_name='commoncategoryicon',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.aplansimage'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryicon',
            unique_together={('category', 'language')},
        ),
        migrations.RemoveField(
            model_name='categoryicon',
            name='data',
        ),
        migrations.AddConstraint(
            model_name='categoryicon',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('svg__isnull', True), ('image__isnull', False)), models.Q(('svg__isnull', False), ('image__isnull', True)), _connector='OR'), name='actions_categoryicon_svg_xor_image'),
        ),
        migrations.AddConstraint(
            model_name='commoncategoryicon',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('svg__isnull', True), ('image__isnull', False)), models.Q(('svg__isnull', False), ('image__isnull', True)), _connector='OR'), name='actions_commoncategoryicon_svg_xor_image'),
        ),
    ]
