# Generated by Django 2.2.4 on 2019-09-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0028_add_action_status_is_completed_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionresponsibleparty',
            old_name='org',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='action',
            name='responsible_parties',
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_parties', to='actions.Action', verbose_name='action'),
        ),
    ]
