# Generated by Django 3.2.13 on 2022-07-11 22:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_add_cached_normalized_values'),
        ('actions', '0029_refactor_category_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indicators.unit', verbose_name='Unit (only if format is numeric)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='related_actions',
            field=models.ManyToManyField(blank=True, related_name='_actions_action_related_actions_+', to='actions.Action', verbose_name='related actions'),
        ),
        migrations.AlterField(
            model_name='attributerichtext',
            name='type',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_text_attributes', to='actions.attributetype'),
        ),
    ]
