# Generated by Django 2.2.4 on 2019-10-02 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0029_action_responsible_parties_no_longer_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='contact_persons',
            new_name='contact_persons_unordered',
        ),
        migrations.AlterField(
            model_name='actioncontactperson',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='actions.Action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='organization',
            field=models.ForeignKey(limit_choices_to=models.Q(dissolution_date=None), on_delete=django.db.models.deletion.CASCADE, related_name='responsible_actions', to='django_orghierarchy.Organization', verbose_name='organization'),
        ),
    ]
