# Generated by Django 2.2.4 on 2019-10-12 10:21

from django.db import migrations


def migrate_contact_persons(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    for action in Action.objects.all():
        for task in action.tasks.all():
            if not task.comment:
                continue

            title = task.name
            if not task.completed_at:
                continue
            if 'yhteyshenkilö' in title.lower():
                continue
            date = task.completed_at
            if action.status_updates.filter(title=title, date=date).exists():
                continue
            action.status_updates.create(title=title, date=date, content=task.comment)


def nop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0031_add_action_status_update_model'),
    ]

    operations = [
        migrations.RunPython(migrate_contact_persons, nop),
    ]
