# Generated by Django 3.2.13 on 2022-08-08 17:42

import aplans.utils
from django.db import migrations, models
import kausal_common.i18n.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0031_add_common_category_type_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoncategory',
            options={'ordering': ('type', 'order')},
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default=kausal_common.i18n.helpers.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default=kausal_common.i18n.helpers.get_default_language, max_length=8),
        ),
    ]
