# Generated by Django 2.2.4 on 2019-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0032_migrate_task_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionstatusupdate',
            options={'ordering': ('-date',), 'verbose_name': 'action status update', 'verbose_name_plural': 'action status updates'},
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_images_for_actions',
            field=models.BooleanField(default=True, help_text='Should custom images for individual actions be allowed', verbose_name='allow images for actions'),
        ),
    ]
