# Generated by Django 3.2.13 on 2022-08-24 10:40

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0036_initialize_primary_classification_with_action_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='commoncategorytype',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English'), ('en-AU', 'Australian English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'short_description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='commoncategoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English'), ('en-AU', 'Australian English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'short_description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('en-AU', 'Australian English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('en-AU', 'Australian English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default=aplans.utils.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_action_classification',
            field=models.ForeignKey(blank=True, help_text='Used for primary navigation and grouping of actions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_with_primary_classification', to='actions.categorytype', verbose_name='The primary action classification'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('en-AU', 'Australian English'), ('sv', 'Swedish'), ('de', 'German'), ('da', 'Danish')], default=aplans.utils.get_default_language, max_length=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='secondary_action_classification',
            field=models.ForeignKey(blank=True, help_text='Leave empty unless specifically required. Actionfilters based on this category are displayed more prominently than filters of other categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_with_secondary_classification', to='actions.categorytype', verbose_name='A secondary action classification'),
        ),
    ]
