# Generated by Django 2.2.9 on 2019-12-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0036_support_merging_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='editable_for_actions',
            field=models.BooleanField(default=False, verbose_name='editable for actions'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='editable_for_indicators',
            field=models.BooleanField(default=False, verbose_name='editable for indicators'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='actions.CategoryType', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
