# Generated by Django 2.2.9 on 2020-01-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0037_make_categories_more_flexible'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='short description'),
        ),
    ]
