# Generated by Django 2.2.9 on 2020-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0038_add_category_short_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='short description'),
        ),
    ]
