# Generated by Django 2.2.9 on 2020-01-16 10:14

import actions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0040_implement_impact_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactgroup',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[actions.models.validate_hex_color], verbose_name='color'),
        ),
    ]
