# Generated by Django 2.2.11 on 2020-04-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0009_add_organization_distinct_name'),
        ('actions', '0042_add_monitoring_quality_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionresponsibleparty',
            unique_together={('action', 'organization')},
        ),
    ]
