# Generated by Django 3.2.13 on 2022-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0042_responsible_party_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeatures',
            name='enable_indicator_comparison',
            field=models.BooleanField(default=True, help_text='Set to enable comparing indicators between organizations', verbose_name='Enable indicator comparison'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='enable_search',
            field=models.BooleanField(default=True, help_text='Enable site-wide search functionality', verbose_name='Enable site search'),
        ),
    ]
