# Generated by Django 3.2.13 on 2022-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0043_make_certain_plan_features_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeatures',
            name='public_contact_persons',
            field=models.BooleanField(default=True, help_text='Set if the contact persons should be visible in the public UI', verbose_name='Contact persons public'),
        ),
    ]
