# Generated by Django 2.2.11 on 2020-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0044_make_action_task_name_longer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='internal_priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='internal priority'),
        ),
    ]
