# Generated by Django 3.0.6 on 2020-05-29 08:25

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0045_internal_priority_can_be_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='What does this action involve in more detail?', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_parties', to='actions.Action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='actions.Action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='comment',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
