# Generated by Django 3.0.6 on 2020-06-10 17:59

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('auth', '0011_update_proxy_permissions'),
        ('actions', '0046_add_i18n_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='admin_group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_for_plan', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='plan',
            name='contact_person_group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_person_for_plan', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='plan',
            name='root_collection',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailcore.Collection'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name'], required_languages=(), virtual_fields=True),
        ),
    ]
