# Generated by Django 3.0.6 on 2020-08-07 08:11

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


def forward_func(apps, schema_editor):
    ImpactGroupTranslation = apps.get_model('actions', 'ImpactGroupTranslation')
    MonitoringQualityPointTranslation = apps.get_model('actions', 'MonitoringQualityPointTranslation')

    for tobj in ImpactGroupTranslation.objects.filter(language_code='fi'):
        obj = tobj.master
        obj.name_t = tobj.name
        obj.save()

    for tobj in MonitoringQualityPointTranslation.objects.filter(language_code='fi'):
        obj = tobj.master
        obj.name_t = tobj.name
        obj.description_yes_t = tobj.description_yes
        obj.description_no_t = tobj.description_no
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('actions', '0047_add_root_collection_to_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoringqualitypointtranslation',
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name='impactgroup',
            options={'ordering': ('plan', '-weight'), 'verbose_name': 'impact group', 'verbose_name_plural': 'impact groups'},
        ),
        migrations.AddField(
            model_name='action',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'official_name', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='actiondecisionlevel',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='actionimpact',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='actionschedule',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='actionstatus',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='category',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'short_description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='impactgroup',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='impactgroup',
            name='name_t',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='monitoringqualitypoint',
            name='description_no_t',
            field=models.CharField(max_length=200, null=True, verbose_name="description when action doesn't fulfill criteria"),
        ),
        migrations.AddField(
            model_name='monitoringqualitypoint',
            name='description_yes_t',
            field=models.CharField(max_length=200, null=True, verbose_name='description when action fulfills criteria'),
        ),
        migrations.AddField(
            model_name='monitoringqualitypoint',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description_yes', 'description_no'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='monitoringqualitypoint',
            name='name_t',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='root_collection',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='wagtailcore.Collection'),
        ),
        migrations.RunPython(forward_func, None),
        migrations.DeleteModel(
            name='ImpactGroupTranslation',
        ),
        migrations.RemoveField(
            model_name='monitoringqualitypointtranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='MonitoringQualityPointTranslation',
        ),
        migrations.RenameField(
            model_name='impactgroup',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='monitoringqualitypoint',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='monitoringqualitypoint',
            old_name='description_yes_t',
            new_name='description_yes',
        ),
        migrations.RenameField(
            model_name='monitoringqualitypoint',
            old_name='description_no_t',
            new_name='description_no',
        ),
    ]
