# Generated by Django 3.2.13 on 2022-11-02 08:26

import aplans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0047_defer_attributetypechoiceoption_unique_together_type_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncategorytype',
            name='hide_category_identifiers',
            field=models.BooleanField(default=False, help_text='Set if the categories do not have meaningful identifiers', verbose_name='hide category identifiers'),
        ),
        migrations.AlterField(
            model_name='action',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='actions', to='actions.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-GB', 'English (United Kingdom)'), ('en-AU', 'English (Australia)'), ('fi', 'Finnish'), ('sv', 'Swedish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategoryicon',
            name='language',
            field=models.CharField(blank=True, choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-GB', 'English (United Kingdom)'), ('en-AU', 'English (Australia)'), ('fi', 'Finnish'), ('sv', 'Swedish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='primary_language',
            field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-GB', 'English (United Kingdom)'), ('en-AU', 'English (Australia)'), ('fi', 'Finnish'), ('sv', 'Swedish')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-GB', 'English (United Kingdom)'), ('en-AU', 'English (Australia)'), ('fi', 'Finnish'), ('sv', 'Swedish')], default=aplans.utils.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_language',
            field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-GB', 'English (United Kingdom)'), ('en-AU', 'English (Australia)'), ('fi', 'Finnish'), ('sv', 'Swedish')], default=aplans.utils.get_default_language, max_length=8),
        ),
    ]
