# Generated by Django 3.0.6 on 2020-08-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0048_add_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactgroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='monitoringqualitypoint',
            name='description_no',
            field=models.CharField(max_length=200, verbose_name="description when action doesn't fulfill criteria"),
        ),
        migrations.AlterField(
            model_name='monitoringqualitypoint',
            name='description_yes',
            field=models.CharField(max_length=200, verbose_name='description when action fulfills criteria'),
        ),
        migrations.AlterField(
            model_name='monitoringqualitypoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
