# Generated by Django 3.0.6 on 2020-08-07 08:44

import actions.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0049_remove_nullability'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='other_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default=actions.models.get_default_language, max_length=8), default=list, size=None),
        ),
        migrations.AddField(
            model_name='plan',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default=actions.models.get_default_language, max_length=8),
        ),
    ]
