# Generated by Django 3.0.9 on 2020-08-10 07:20

import actions.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('actions', '0051_start_using_wagtail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='site',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='wagtailcore.Site'),
        ),
        migrations.AlterField(
            model_name='actionimpact',
            name='plan',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_impacts', to='actions.Plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='actionschedule',
            name='plan',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_schedules', to='actions.Plan'),
        ),
        migrations.AlterField(
            model_name='actionstatus',
            name='plan',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_statuses', to='actions.Plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default=actions.models.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
    ]
