# Generated by Django 3.1 on 2020-08-17 10:42

import actions.models
import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0052_add_site_to_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiontask',
            options={'ordering': ('action', '-due_at'), 'verbose_name': 'action task', 'verbose_name_plural': 'action tasks'},
        ),
        migrations.AddField(
            model_name='categorytype',
            name='usable_for_actions',
            field=models.BooleanField(default=False, verbose_name='usable for action categorization'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='usable_for_indicators',
            field=models.BooleanField(default=False, verbose_name='usable for indicator categorization'),
        ),
        migrations.AlterField(
            model_name='actioncontactperson',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='actions.action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default=actions.models.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
    ]
