# Generated by Django 3.2.13 on 2022-11-29 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0052_add_instances_editable_by_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='settings_action_update_acceptable_interval',
            field=models.PositiveIntegerField(blank=True, help_text='A maximum time interval in days within which actions should always be updated. If you leave this blank the application will use the default value.', null=True, validators=[django.core.validators.MaxValueValidator(730), django.core.validators.MinValueValidator(1)], verbose_name='Acceptable interval in days to update actions'),
        ),
        migrations.AddField(
            model_name='plan',
            name='settings_action_update_target_interval',
            field=models.PositiveIntegerField(blank=True, help_text='A desirable time interval in days within which actions should be updated in the optimal case. If you leave this blank the application will use the default value.', null=True, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)], verbose_name='Target interval in days to update actions'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='action_days_until_considered_stale',
            field=models.PositiveIntegerField(blank=True, help_text='Actions not updated since this many days are considered stale. If you leave this blank the application will use the default value 180.', null=True, validators=[django.core.validators.MaxValueValidator(730)], verbose_name='Days until actions considered stale'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='secondary_action_classification',
            field=models.ForeignKey(blank=True, help_text='Leave empty unless specifically required. Action filters based on this category are displayed more prominently than filters of other categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_with_secondary_classification', to='actions.categorytype', verbose_name='A secondary action classification'),
        ),
    ]
