# Generated by Django 3.1 on 2020-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0053_add_category_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncontactperson',
            name='primary_contact',
            field=models.BooleanField(default=False, help_text='Is this person the primary contact person for the action?', verbose_name='primary contact person'),
        ),
    ]
