# Generated by Django 3.2.13 on 2022-11-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0054_alter_attributetype_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_types', to='actions.report', verbose_name='Report'),
        ),
    ]
