# Generated by Django 3.1 on 2020-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0009_add_organization_distinct_name'),
        ('actions', '0054_add_primary_contact_person_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='related_organizations',
            field=models.ManyToManyField(blank=True, related_name='related_plans', to='django_orghierarchy.Organization'),
        ),
    ]
