# Generated by Django 3.2.13 on 2022-11-24 16:57

import actions.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0055_attributetype_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fields',
            field=wagtail.core.fields.StreamField([('implementation_phase', actions.blocks.ActionImplementationPhaseReportFieldBlock()), ('text_attribute', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(heading='Name')), ('identifier', wagtail.core.blocks.CharBlock(heading='Identifier'))]))], blank=True, null=True),
        ),
    ]
