# Generated by Django 3.1 on 2020-08-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_orghierarchy', '0009_add_organization_distinct_name'),
        ('actions', '0055_add_related_organizations_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='django_orghierarchy.organization', verbose_name='main organization for the plan'),
        ),
    ]
