# Generated by Django 3.1 on 2020-09-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0056_add_organization_to_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='host name')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='actions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'plan domain',
                'verbose_name_plural': 'plan domains',
            },
        ),
    ]
