# Generated by Django 3.1 on 2020-09-23 10:02

import actions.models
import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0057_add_support_for_plan_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='accessibility_statement_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL to accessibility statement'),
        ),
        migrations.AlterField(
            model_name='action',
            name='plan',
            field=modelcluster.fields.ParentalKey(default=actions.models.latest_plan, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='actions.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish')], default=actions.models.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish')], default=actions.models.get_default_language, max_length=8),
        ),
        migrations.AlterField(
            model_name='plandomain',
            name='plan',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='actions.plan', verbose_name='plan'),
        ),
    ]
