# Generated by Django 3.1 on 2020-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0058_add_link_to_accessibility_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='manual_status',
            field=models.BooleanField(default=False, help_text='Set if you want to prevent the action status from being determined automatically', verbose_name='override status manually'),
        ),
        migrations.AddField(
            model_name='action',
            name='manual_status_reason',
            field=models.TextField(blank=True, help_text='Describe the reason why this action has the overridden status', null=True, verbose_name='reason for status override'),
        ),
    ]
