# Generated by Django 3.1 on 2020-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0059_manual_status_override_for_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cache_invalidated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
