# Generated by Django 3.1 on 2020-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0060_add_plan_cache_invalidated_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandomain',
            name='google_site_verification_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plandomain',
            name='matomo_analytics_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
