# Generated by Django 3.1 on 2020-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0061_add_analytics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='uses_wagtail',
            field=models.BooleanField(default=True),
        ),
    ]
