# Generated by Django 3.1 on 2020-11-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0062_add_plan_uses_wagtail_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='official_name',
            field=models.TextField(blank=True, help_text='The name as approved by an official party', null=True, verbose_name='official name'),
        ),
    ]
