# Generated by Django 3.1.3 on 2020-12-16 12:03

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0063_make_official_name_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='statuses_updated_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActionImplementationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('identifier', aplans.utils.IdentifierField(max_length=20, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('plan', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_implementation_phases', to='actions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'action implementation phase',
                'verbose_name_plural': 'action implementation phases',
                'ordering': ('plan', 'order'),
                'unique_together': {('plan', 'identifier')},
            },
        ),
        migrations.AddField(
            model_name='action',
            name='implementation_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.actionimplementationphase', verbose_name='implementation phase'),
        ),
    ]
