# Generated by Django 3.2.13 on 2023-01-03 20:11

from django.db import migrations, models

from actions.models import ActionStatus as _ActionStatus



class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0065_plandomain_publication_status_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstatus',
            name='identifier',
            field=models.CharField(choices=[('on_time', 'On time'), ('late', 'Late'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default=None, max_length=20, verbose_name='state'),
        ),
    ]
