# Generated by Django 3.1.5 on 2021-02-06 08:03

import actions.models
import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0066_add_category_level_and_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTypeMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('identifier', aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('format', models.CharField(choices=[('ordered_choice', 'Ordered choice'), ('rich_text', 'Rich text')], max_length=50, verbose_name='Format')),
                ('type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='actions.categorytype')),
            ],
            options={
                'verbose_name': 'category metadata',
                'verbose_name_plural': 'category metadatas',
                'unique_together': {('type', 'identifier'), ('type', 'order')},
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='plan',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='actions.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Set if the category has a theme color', max_length=50, null=True, validators=[actions.models.validate_css_color], verbose_name='theme color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='categorylevel',
            name='type',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='actions.categorytype', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='django_orghierarchy.organization', verbose_name='main organization for the plan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryTypeMetadataChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('identifier', aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('metadata', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='actions.categorytypemetadata')),
            ],
            options={
                'verbose_name': 'category type metadata choice',
                'verbose_name_plural': 'category type metadata choices',
                'ordering': ('metadata', 'order'),
                'unique_together': {('metadata', 'order'), ('metadata', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMetadataRichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.core.fields.RichTextField(verbose_name='Text')),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_richtexts', to='actions.category')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_richtexts', to='actions.categorytypemetadata')),
            ],
            options={
                'unique_together': {('category', 'metadata')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMetadataChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_choices', to='actions.category')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='actions.categorytypemetadatachoice')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_choices', to='actions.categorytypemetadata')),
            ],
            options={
                'unique_together': {('category', 'metadata')},
            },
        ),
    ]
