# Generated by Django 3.2.13 on 2023-01-17 14:12

from django.db import migrations
from django.utils import translation

from actions.models import Plan, Action, ActionStatus, ActionImplementationPhase


# Phase mappings here must be found in plan or
# actions.defaults.DEFAULT_ACTION_IMPLEMENTATION_PHASES
MAPPINGS = {
    'almost_late':        ('status', 'on_time'),
    'severely_late':      ('status', 'late'),
    'severly_late':       ('status', 'late'),
    'changed_responsib.': ('status', 'out_of_scope'),
    'not_started':        ('phase', 'not_started'),
    'completed':          ('phase', 'completed'),
    'in_progress':        ('phase', 'implementation'),
}


def _create_phase(plan, identifier):
    created, replacing_phase = ActionImplementationPhase.get_or_create_default(identifier, plan)
    if created:
        plan.action_implementation_phases.add(replacing_phase)
        plan.save()
    return replacing_phase


def _map_unallowed_action_statuses(apps, schema_editor):
    allowed_identifiers = list(i.value for i in ActionStatus.Identifier)
    # print('allowed', list(allowed_identifiers))
    debug = []
    # TODO. if no 'completed', add it as last for all plans
    for action_status in ActionStatus.objects.exclude(identifier__in=allowed_identifiers):
        plan = Plan.objects.get(pk=action_status.plan.pk)
        with translation.override(plan.primary_language):
            replacing_phase_identifier = None
            replacing_status = None
            mapping_type, identifier = MAPPINGS.get(action_status.identifier, (None, None))
            if mapping_type == 'phase':
                replacing_phase_identifier = identifier
            elif mapping_type == 'status':
                created, replacing_status = ActionStatus.get_or_create_default(identifier, plan)
                if created:
                    plan.action_statuses.add(replacing_status)
                    plan.save()
            for action in Action.objects.filter(status=action_status):
                old_status = action.status.identifier if action.status else None
                old_phase = action.implementation_phase.identifier if action.implementation_phase else None
                if replacing_phase_identifier and action.implementation_phase is None:
                    action.status = None
                    action.implementation_phase = _create_phase(plan, replacing_phase_identifier)
                elif replacing_status:
                    action.status = replacing_status
                else:
                    action.status = None
                action.save()
                phase_id = action.implementation_phase.identifier if action.implementation_phase else "[none]"
                debug.append("\n".join((
                    plan.name, action.identifier, action.name,
                    f'{old_status} > {action.status.identifier if action.status else "[none]"}',
                    f'{old_phase} > {phase_id}'
                )))
        action_status.delete()

    for action in Action.objects.filter(implementation_phase__isnull=True) \
                                .filter(status__identifier__in=('late', 'on_time')):
        plan = action.plan
        with translation.override(plan.primary_language):
            replacing_phase = _create_phase(plan, 'implementation')
            action.implementation_phase = replacing_phase
            action.save()
            phase_id = action.implementation_phase.identifier if action.implementation_phase else "[none]"
            debug.append("\n".join((
                plan.name,
                'NOREPLACE',
                action.identifier,
                action.name,
                f'NONE > {phase_id}')))

    return "\n\n".join(debug)


def map_unallowed_action_statuses(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    ActionStatus = apps.get_model('actions', 'ActionStatus')
    ActionImplementationPhase = apps.get_model('actions', 'ActionImplementationPhase')
    # Plan = apps.get_model('actions', 'Plan')
    _map_unallowed_action_statuses(Action, ActionStatus, ActionImplementationPhase)


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0066_alter_actionstatus_identifier'),
    ]

    operations = [
        migrations.RunPython(_map_unallowed_action_statuses)
    ]
