# Generated by Django 3.2.13 on 2023-01-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0067_country_and_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='daily_notifications_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
