# Generated by Django 3.1.5 on 2021-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0067_add_category_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image_was_migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='image_was_migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_was_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
