# Generated by Django 3.1.5 on 2021-02-09 11:23

from django.db import migrations
from django.db.models import Q

from actions.management.commands.migrate_images import HAS_IMAGE, HAS_MAIN_IMAGE


def abort_unless_data_migrated(apps, schema_editor):
    for model_name in 'Action', 'Category', 'Plan':
        old_model = apps.get_model('actions', model_name)
        has_unmigrated_image = HAS_IMAGE & ~HAS_MAIN_IMAGE & Q(image_was_migrated=False)
        if old_model.objects.filter(has_unmigrated_image).exists():
            raise Exception("There are unmigrated images. Please make sure all other apps are migrated, then run the "
                            "management command migrate_images and retry this migration. For the command to work, "
                            "you will need to check out the commit tagged with migrate-images.")


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('actions', '0068_add_image_was_migrated_field'),
    ]

    operations = [
        migrations.RunPython(abort_unless_data_migrated),
        migrations.RemoveField(
            model_name='action',
            name='image',
        ),
        migrations.RemoveField(
            model_name='action',
            name='image_cropping',
        ),
        migrations.RemoveField(
            model_name='action',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='action',
            name='image_width',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='action',
            name='image_was_migrated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_cropping',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_width',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_was_migrated',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image_cropping',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image_width',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='image_was_migrated',
        ),
    ]
