# Generated by Django 3.2.13 on 2023-02-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0068_plan_daily_notifications_triggered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='report_field',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
