# Generated by Django 3.1.6 on 2021-02-22 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0069_remove_old_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylevel',
            name='name_plural',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='plural name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='site_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(('http', 'https'))], verbose_name='site URL'),
        ),
    ]
