# Generated by Django 3.2.13 on 2023-03-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        ('actions', '0070_auto_fill_identifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_snapshots', to='reversion.version')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_snapshots', to='actions.report')),
            ],
            options={
                'verbose_name': 'action snapshot',
                'verbose_name_plural': 'action snapshots',
            },
        ),
    ]
