# Generated by Django 3.1.6 on 2021-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0070_add_category_level_plural_name_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='internal_priority_comment',
            new_name='internal_notes',
        ),
    ]
