# Generated by Django 3.1.5 on 2021-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0071_rename_internal_priority_comment_to_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='internal notes'),
        ),
        migrations.AlterField(
            model_name='action',
            name='manual_status_reason',
            field=models.TextField(blank=True, help_text='Describe the reason why this action has has this status', null=True, verbose_name='specifier for status'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytypemetadata',
            unique_together={('type', 'identifier')},
        ),
    ]
