# Generated by Django 3.2.13 on 2023-03-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('actions', '0072_remove_report_fks'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='ActionSnapshot',
                    table='reports_actionsnapshot',
                ),
                migrations.AlterModelTable(
                    name='Report',
                    table='reports_report',
                ),
                migrations.AlterModelTable(
                    name='ReportType',
                    table='reports_reporttype',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='attributetype',
                    name='report',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_types', to='reports.report', verbose_name='Report'),
                ),
                migrations.DeleteModel(
                    name='ActionSnapshot',
                ),
                migrations.DeleteModel(
                    name='Report',
                ),
                migrations.DeleteModel(
                    name='ReportType',
                ),
            ],
        ),
    ]
