# Generated by Django 3.1.7 on 2021-03-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0073_add_show_admin_link_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='contact_persons_private',
            field=models.BooleanField(default=False, help_text='Set if the contact persons should not be visible in the public UI', verbose_name='Contact persons private'),
        ),
    ]
