# Generated by Django 3.1.5 on 2021-04-12 08:13

from django.db import migrations, models


def mark_completed_if_completed_at(apps, schema_editor):
    ActionTask = apps.get_model('actions', 'ActionTask')
    for task in ActionTask.objects.filter(completed_at__isnull=False).exclude(state='completed'):
        task.state = 'completed'
        task.save(update_fields=['state'])


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0074_allow_hiding_contact_persons'),
    ]

    operations = [
        migrations.RunPython(mark_completed_if_completed_at),
        migrations.AddConstraint(
            model_name='actiontask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state='completed'), ('completed_at__isnull', False), _connector='OR'), name='actions_actiontask_completed_at_if_completed'),
        ),
        migrations.AddConstraint(
            model_name='actiontask',
            constraint=models.CheckConstraint(check=models.Q(('completed_at__isnull', True), ('state', 'completed'), _connector='OR'), name='actions_actiontask_completed_if_completed_at'),
        ),
    ]
