# Generated by Django 3.1.5 on 2021-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0075_add_action_completed_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('type', 'order'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='action',
            old_name='internal_notes',
            new_name='internal_admin_notes',
        ),
        migrations.AddField(
            model_name='action',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='internal notes'),
        ),
    ]
