# Generated by Django 3.2.13 on 2023-03-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0072_action_visibility'),
        ('actions', '0075_remove_attribute_type_links_to_reports'),
    ]

    operations = [
    ]
