# Generated by Django 3.1.5 on 2021-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0076_add_internal_notes_for_nonadmins'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_identifier',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='internal_admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='internal notes for plan administrators'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('type', 'external_identifier'), ('type', 'identifier')},
        ),
    ]
