# Generated by Django 3.1.5 on 2021-09-14 13:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0077_add_external_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytypemetadata',
            name='format',
            field=models.CharField(choices=[('ordered_choice', 'Ordered choice'), ('rich_text', 'Rich text'), ('numeric', 'Numeric')], max_length=50, verbose_name='Format'),
        ),
        migrations.CreateModel(
            name='CategoryMetadataNumericValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_numeric_values', to='actions.category')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_numeric_values', to='actions.categorytypemetadata')),
            ],
            options={
                'unique_together': {('category', 'metadata')},
            },
        ),
    ]
