# Generated by Django 3.2.13 on 2023-05-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0077_auto_non_schema_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='external_feedback_url',
            field=models.URLField(blank=True, help_text="If not empty, the system's built-in user feedback gathering functionality will be replaced by a link to an external feedback form available at this URL.", null=True, verbose_name='URL to external feedback statement'),
        ),
    ]
