# Generated by Django 3.1.5 on 2021-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0078_add_metadata_numeric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='hide_category_identifiers',
            field=models.BooleanField(default=False, help_text='Set if the categories do not have meaningful identifiers', verbose_name='hide category identifiers'),
        ),
        migrations.AddField(
            model_name='plan',
            name='hide_action_identifiers',
            field=models.BooleanField(default=False, help_text="Set if the plan doesn't have meaningful action identifiers", verbose_name='Hide action identifiers'),
        ),
    ]
