# Generated by Django 3.2.13 on 2023-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0079_implementation_phase_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstatus',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='color'),
        ),
    ]
