# Generated by Django 3.1.5 on 2021-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0079_allow_hiding_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='end_date',
            field=models.DateField(blank=True, help_text='The date when implementation of this action ends', null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='action',
            name='lead_paragraph',
            field=models.TextField(blank=True, verbose_name='Lead paragraph'),
        ),
        migrations.AddField(
            model_name='action',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date when implementation of this action starts', null=True, verbose_name='start date'),
        ),
    ]
