# Generated by Django 3.2.13 on 2023-06-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0080_actionstatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='minimal_statuses',
            field=models.BooleanField(default=False, help_text="Enable to prevent showing status-specific graphs and other elements if statuses aren't systematically used in this action plan", verbose_name='Do not assume that statuses are used for most actions'),
        ),
    ]
