# Generated by Django 3.1.5 on 2021-09-17 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0080_action_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('url', models.URLField(max_length=400, validators=[django.core.validators.URLValidator(('http', 'https'))], verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=254, verbose_name='title')),
                ('action', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='actions.action', verbose_name='action')),
            ],
            options={
                'verbose_name': 'action link',
                'verbose_name_plural': 'action links',
                'ordering': ['action', 'order'],
                'index_together': {('action', 'order')},
            },
        ),
    ]
