# Generated by Django 3.1.5 on 2021-09-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0081_actionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='hide_action_lead_paragraph',
            field=models.BooleanField(default=True, help_text="Set if the plan doesn't use the lead paragraph field", verbose_name='Hide lead paragraph'),
        ),
        migrations.AddField(
            model_name='plan',
            name='hide_action_official_name',
            field=models.BooleanField(default=False, help_text="Set if the plan doesn't use the official name field", verbose_name='Hide official name field'),
        ),
    ]
