# Generated by Django 3.1.5 on 2021-09-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_wagtail_editing'),
        ('actions', '0083_add_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionresponsibleparty',
            name='organization_new',
            field=models.ForeignKey(limit_choices_to=models.Q(dissolution_date=None), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_actions', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='plan',
            name='organization_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='orgs.organization', verbose_name='main organization for the plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='related_organizations_new',
            field=models.ManyToManyField(blank=True, related_name='related_plans', to='orgs.Organization'),
        ),
        migrations.AlterField(
            model_name='action',
            name='responsible_organizations',
            field=models.ManyToManyField(blank=True, related_name='responsible_for_actions', through='actions.ActionResponsibleParty', to='orgs.Organization', verbose_name='responsible organizations'),
        ),
        migrations.AlterUniqueTogether(
            name='actionresponsibleparty',
            unique_together={('action', 'organization_new')},
        ),
    ]
