# Generated by Django 3.2.16 on 2023-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0083_add_role_to_action_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='has_action_contact_person_roles',
            field=models.BooleanField(default=False, help_text='Set if there are separate contact persons with publishing rights and others who can only suggest changes', verbose_name='Action contact persons have different roles'),
        ),
    ]
