# Generated by Django 3.1.5 on 2021-09-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_wagtail_editing'),
        ('actions', '0084_new_organization_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='organization',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='plan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='orgs.organization', verbose_name='main organization for the plan'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='related_organizations',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='related_organizations_new',
            new_name='related_organizations',
        ),
        migrations.AlterField(
            model_name='plan',
            name='related_organizations',
            field=models.ManyToManyField(blank=True, related_name='related_plans', to='orgs.Organization'),
        ),
        migrations.RemoveField(
            model_name='actionresponsibleparty',
            name='organization',
        ),
        migrations.RenameField(
            model_name='actionresponsibleparty',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='actionresponsibleparty',
            name='organization',
            field=models.ForeignKey(limit_choices_to=models.Q(dissolution_date=None), on_delete=django.db.models.deletion.CASCADE, related_name='responsible_actions', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AlterUniqueTogether(
            name='actionresponsibleparty',
            unique_together={('action', 'organization')},
        ),
    ]
