# Generated by Django 3.2.16 on 2023-09-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_alter_organization_primary_language'),
        ('actions', '0088_wagtail_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='enable_moderation_workflow',
            field=models.BooleanField(default=False, help_text='Set to enable drafting and reviewing functionality', verbose_name='Enable moderation workflow'),
        ),
        migrations.AlterField(
            model_name='action',
            name='primary_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.organization', verbose_name='primary organization'),
        ),
    ]
