# Generated by Django 3.2.16 on 2023-10-26 07:53

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0096_add_i18n_to_action_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text'), required_languages=(), virtual_fields=True),
        ),
    ]
