# Generated by Django 3.2.16 on 2024-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0103_auto_20240220_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='allow_public_site_login',
            field=models.BooleanField(default=False, help_text='Should users be able to have authenticated sessions in the public UI', verbose_name='Allow logging in to the public website'),
        ),
    ]
