# Generated by Django 3.2.16 on 2024-02-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0105_add_workflow_to_plan_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeatures',
            name='enable_moderation_workflow',
        ),
    ]
