# Generated by Django 3.2.16 on 2024-02-25 14:17

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('actions', '0106_remove_planfeatures_enable_moderation_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='primary_language',
            field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-AU', 'English (Australia)'), ('en-GB', 'English (United Kingdom)'), ('es', 'Spanish'), ('es-US', 'Spanish (United States)'), ('fi', 'Finnish'), ('lv', 'Latvian'), ('sv', 'Swedish'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese (Brazil)')], default=aplans.utils.get_default_language, max_length=8),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='moderation_workflow',
            field=models.ForeignKey(blank=True, default=None, help_text='Set to enable drafting and reviewing functionality and choose the desired workflow for reviewing', null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailcore.workflow'),
        ),
    ]
