# Generated by Django 3.2.16 on 2024-02-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_remove_person_public_site_only'),
        ('actions', '0107_auto_20240225_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPublicSiteViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_with_public_site_access', to='people.person', verbose_name='person')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_site_viewers', to='actions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'public site viewer',
                'verbose_name_plural': 'public site viewers',
                'unique_together': {('plan', 'person')},
            },
        ),
    ]
