# Generated by Django 3.2.16 on 2024-03-14 13:40

from django.db import migrations, models


def rename_draft_to_internal(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    for a in Action.objects.all():
        if a.visibility == 'draft':
            a.visibility = 'internal'
            a.save(update_fields=['visibility'])


def rename_internal_to_draft(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    for a in Action.objects.all():
        if a.visibility == 'internal':
            a.visibility = 'draft'
            a.save(update_fields=['visibility'])


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0111_hide_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=20, verbose_name='visibility'),
        ),
        migrations.RunPython(rename_draft_to_internal, rename_internal_to_draft)
    ]
