# Generated by Django 3.2.16 on 2024-03-21 11:29

import aplans.utils
from django.db import migrations, models


def set_default_language_lowercase(apps, schema_editor):
    Models = [
        apps.get_model('actions', 'AttributeType'),
        apps.get_model('actions', 'CommonCategoryType'),
        apps.get_model('actions', 'Plan')
    ]
    for Model in Models:
        for instance in Model.objects.all():
            instance.primary_language_lowercase = instance.primary_language.lower()
            instance.save(update_fields=['primary_language_lowercase'])


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0114_add_dependency_role_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='primary_language_lowercase',
            field=models.CharField(default=aplans.utils.get_default_language_lowercase, max_length=8),
        ),
        migrations.AddField(
            model_name='commoncategorytype',
            name='primary_language_lowercase',
            field=models.CharField(default=aplans.utils.get_default_language_lowercase, max_length=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='primary_language_lowercase',
            field=models.CharField(default=aplans.utils.get_default_language_lowercase, max_length=8),
        ),
        migrations.RunPython(set_default_language_lowercase, migrations.RunPython.noop),
    ]
