# Generated by Django 3.2.16 on 2024-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0116_alter_plan_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='usage_status',
            field=models.CharField(choices=[('customer_use', 'Customer use'), ('sales', 'Sales and demos'), ('development', 'Internal testing, training, development or other non-public use'), ('customer_offboarding', 'Offboarding in progress'), ('inactive', 'Inactive, not in use currently'), ('deprecated', 'Deprecated, should be deleted')], default='customer_use', help_text='If unsure, use the default value representing customer use. For statistical purposes specify what the plan will be used for in order to differentiate between plans actually in use by customers and those created for some other reason.', max_length=30, verbose_name='Usage status'),
        ),
    ]
