# Generated by Django 3.2.16 on 2024-04-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0119_add_planfeatures_report_print_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='password_protected',
            field=models.BooleanField(default=False, help_text='Is this plan password protected?', verbose_name='Password protected'),
        ),
    ]
