# Generated by Django 5.0.4 on 2024-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0123_indicator_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeatures',
            name='indicator_ordering',
            field=models.CharField(choices=[('none', 'No ordering'), ('name', 'Order by name')], default='none', help_text='Choose how to order indicators in the action pages', max_length=50, verbose_name='Indicator order'),
        ),
    ]
