# Generated by Django 5.0.4 on 2024-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0124_alter_planfeatures_indicator_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='contact_persons_show_picture',
            field=models.BooleanField(default=True, help_text='Should profile pictures be shown for contact persons in the public UI?', verbose_name='Show profile pictures for contact persons'),
        ),
    ]
