# Generated by Django 5.0.6 on 2024-09-02 12:04

import actions.models.plan
import aplans.utils
from django.db import migrations, models
import kausal_common.i18n.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0129_migrate_dep_env_testing_to_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('el', 'Greek'), ('en', 'English (United States)'), ('en-AU', 'English (Australia)'), ('en-GB', 'English (United Kingdom)'), ('es', 'Spanish'), ('es-US', 'Spanish (United States)'), ('fi', 'Finnish'), ('lv', 'Latvian'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese (Brazil)'), ('sv', 'Swedish'), ('sv-FI', 'Swedish (Finland)')], max_length=8), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='other_languages',
            field=aplans.utils.ChoiceArrayField(base_field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('el', 'Greek'), ('en', 'English (United States)'), ('en-AU', 'English (Australia)'), ('en-GB', 'English (United Kingdom)'), ('es', 'Spanish'), ('es-US', 'Spanish (United States)'), ('fi', 'Finnish'), ('lv', 'Latvian'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese (Brazil)'), ('sv', 'Swedish'), ('sv-FI', 'Swedish (Finland)')], default=kausal_common.i18n.helpers.get_default_language, max_length=8), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='timezone',
            field=models.CharField(choices=actions.models.plan.get_timezones, default='UTC', max_length=64),
        ),
    ]
