# Generated by Django 5.0.6 on 2024-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0130_alter_attributetype_other_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kausal_paths_node_uuid',
            field=models.CharField(blank=True, default='', help_text='Kausal Paths node to link this category to', max_length=36, verbose_name='Kausal Paths node UUID'),
        ),
        migrations.AddField(
            model_name='commoncategory',
            name='kausal_paths_node_uuid',
            field=models.CharField(blank=True, default='', help_text='Kausal Paths node to link this category to', max_length=36, verbose_name='Kausal Paths node UUID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='kausal_paths_instance_uuid',
            field=models.CharField(blank=True, default='', help_text='UUID of the corresponding Kausal Paths instance for Kausal Paths integration', max_length=100, verbose_name='Kausal Paths instance UUID'),
        ),
    ]
