# Generated by Django 5.0.6 on 2024-09-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0132_planfeatures_admin_accessibility_conformance_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='short_identifier',
            field=models.CharField(blank=True, help_text='A unique short identifier for the plan to be shown in UI. Could be eg. a number or an abbreviation', max_length=3, null=True, verbose_name='short identifier'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('short_identifier', 'parent'), name='unique_short_identifier_within_parent'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('short_identifier', 'organization'), name='unique_short_identifier_for_top_level_plans'),
        ),
    ]
