# Generated by Django 5.0.6 on 2024-12-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0133_plan_short_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='expose_unpublished_plan_only_to_authenticated_user',
            field=models.BooleanField(default=False, help_text='Should the plan be exposed only to authenticated users if not published?', verbose_name='Expose unpublished plan only to authenticated users'),
        ),
        migrations.AlterField(
            model_name='action',
            name='manual_status_reason',
            field=models.TextField(blank=True, help_text='Describe the reason why this action has this status', null=True, verbose_name='specifier for status'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='admin_accessibility_conformance_level',
            field=models.CharField(choices=[('default', 'No extra accessibility fixes active'), ('high', 'This plan requires extra accessibility fixes')], default='default', max_length=50),
        ),
    ]
