# Generated by Django 5.0.6 on 2024-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0133_plan_short_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=20, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='action',
            name='manual_status_reason',
            field=models.TextField(blank=True, help_text='Describe the reason why this action has this status', null=True, verbose_name='specifier for status'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='admin_accessibility_conformance_level',
            field=models.CharField(choices=[('default', 'No extra accessibility fixes active'), ('high', 'This plan requires extra accessibility fixes')], default='default', max_length=50),
        ),
    ]
