# Generated by Django 5.0.6 on 2024-12-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0135_action_copy_of_plan_copy_of_and_more'),
        ('orgs', '0025_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='expose_unpublished_plan_only_to_authenticated_user',
            field=models.BooleanField(default=False, help_text='Should the plan be exposed only to authenticated users if not published?', verbose_name='Expose unpublished plan only to authenticated users'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='organization',
            field=models.ForeignKey(help_text='The main organization for the plan', on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='short_identifier',
            field=models.CharField(blank=True, help_text='A unique short identifier for the plan to be shown in the UI. Could be, e.g., a number or an abbreviation.', max_length=3, null=True, verbose_name='short identifier'),
        ),
    ]
