# Generated by Django 5.2 on 2025-10-06 09:57

import actions.models.plan
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0142_alter_plan_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandomain',
            name='redirect_to_hostname',
            field=models.CharField(blank=True, help_text='If this is set, the host name entered above must be redirected to the host name in this field in the UI.', max_length=200, null=True, validators=[actions.models.plan.is_valid_hostname], verbose_name='redirect to host name'),
        ),
        migrations.AlterField(
            model_name='plandomain',
            name='redirect_aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=[], help_text='Domain names that will be used to redirect to the main hostname. Multiple domains are separated by commas.', size=None, verbose_name='redirect aliases'),
        ),
    ]
