# Generated by Django 5.2 on 2025-11-04 06:38

import actions.models.plan
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0143_plandomain_redirect_to_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='actions', through='actions.ActionCategoryThrough', to='actions.category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='action',
            name='related_actions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='actions.RelatedActionsThrough', to='actions.action', verbose_name='related actions'),
        ),
        migrations.AlterField(
            model_name='plandomain',
            name='redirect_to_hostname',
            field=models.CharField(blank=True, help_text='The UI will redirect to this hostname if set.', max_length=200, null=True, validators=[actions.models.plan.is_valid_hostname], verbose_name='redirect to host name'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='allow_public_site_login',
            field=models.BooleanField(default=False, help_text='Should users be able to have authenticated sessions in the public UI?', verbose_name='Allow logging in to the public website'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='expose_unpublished_plan_only_to_authenticated_user',
            field=models.BooleanField(default=False, help_text='Should the plan be exposed only to authenticated users if not published?', verbose_name='Expose unpublished plan only to authenticated users'),
        ),
    ]
