# Generated by Django 5.2 on 2025-11-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0145_alter_category_kausal_paths_node_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='indicators_open_in_modal',
            field=models.BooleanField(default=False, help_text='Should indicators open only in a modal dialog in the public UI.', verbose_name='Indicators open in modal'),
        ),
    ]
