# Generated by Django 5.2 on 2025-11-24 15:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0147_indicatorcategoryrelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorcategoryrelationship",
            name="category",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicator_relationships",
                to="actions.category",
            ),
        ),
    ]
