# Generated by Django 5.2 on 2025-12-23 12:12

import django.db.models.deletion
import modeltrans.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0148_alter_indicatorcategoryrelationship_category"),
        ("indicators", "0041_alter_indicator_reference"),
        ("people", "0013_person_image_hash_person_image_msgraph_etag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionstatusupdate",
            options={
                "verbose_name": "action status update",
                "verbose_name_plural": "action status updates",
            },
        ),
        migrations.RenameField(
            model_name="actionstatusupdate",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="actionstatusupdate",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=["title", "content"], required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="actionstatusupdate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="actionstatusupdate",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="actionstatusupdate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.CreateModel(
            name="ActionChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="actions.action",
                        verbose_name="action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "action change log message",
                "verbose_name_plural": "action change log messages",
            },
        ),
        migrations.CreateModel(
            name="CategoryChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="actions.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "category change log message",
                "verbose_name_plural": "category change log messages",
            },
        ),
        migrations.CreateModel(
            name="IndicatorChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="indicators.indicator",
                        verbose_name="indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicator change log message",
                "verbose_name_plural": "indicator change log messages",
            },
        ),
    ]
