# Generated by Django 5.2 on 2025-12-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0150_planfeatures_enable_change_log_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionchangelogmessage',
            name='revision',
            field=models.ForeignKey(blank=True, help_text='The revision this change log message is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='revision'),
        ),
        migrations.AlterField(
            model_name='actionchangelogmessage',
            name='content',
            field=models.TextField(help_text='Summarize what was changed. This message will be displayed publicly.', verbose_name='change log message'),
        ),
        migrations.AlterField(
            model_name='categorychangelogmessage',
            name='content',
            field=models.TextField(help_text='Summarize what was changed. This message will be displayed publicly.', verbose_name='change log message'),
        ),
        migrations.AlterField(
            model_name='indicatorchangelogmessage',
            name='content',
            field=models.TextField(help_text='Summarize what was changed. This message will be displayed publicly.', verbose_name='change log message'),
        ),
    ]
