# Generated by Django 5.2 on 2025-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0150_alter_actionstatusupdate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatures",
            name="enable_change_log",
            field=models.BooleanField(
                default=False,
                help_text="Prompt users to add a change log message after editing actions, indicators, or categories.",
                verbose_name="Enable change log",
            ),
        ),
        migrations.AlterField(
            model_name="planfeatures",
            name="indicators_open_in_modal",
            field=models.BooleanField(
                default=False,
                help_text="Should indicators open only in a modal dialog in the public UI?",
                verbose_name="Indicators open in modal",
            ),
        ),
    ]
