# Generated by Django 5.2 on 2026-01-30 14:02

import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields
import uuid
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0157_alter_plandomain_redirect_aliases"),
        ("images", "0007_aplansimage_latest_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatures",
            name="enable_community_engagement",
            field=models.BooleanField(
                default=False,
                help_text="Enable community engagement features such as pledges for this plan.",
                verbose_name="Enable community engagement",
            ),
        ),
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=300, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier for this pledge, used in URLs",
                        max_length=100,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short description of the pledge",
                        max_length=300,
                        verbose_name="description",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("question_answer", 6), ("large_image", 9)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "title",
                                    "heading": "Title",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"heading": "Question"},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"heading": "Answer"},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 2), ("answer", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 1), ("questions", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            8: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("maximum", "Maximum"),
                                        ("fit_to_column", "Fit to column"),
                                    ],
                                    "label": "Width",
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 7), ("width", 8)]],
                                {},
                            ),
                        },
                        help_text="Detailed content about the pledge",
                        null=True,
                        verbose_name="body content",
                    ),
                ),
                (
                    "resident_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Choose a round number that makes the math easy but feels achievable (e.g., 50, 100, 200). This is used in the "If [X] residents commit..." messaging.',
                        null=True,
                        verbose_name="number of residents committed",
                    ),
                ),
                (
                    "impact_statement",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text='Describe the total environmental benefit if this many residents commit. Include specific numbers and units. Start with "We save" or "We reduce" for consistency. Example: "We save <b>9,200kg CO₂e</b> each year"',
                        max_length=120,
                        verbose_name="environmental impact at scale",
                    ),
                ),
                (
                    "local_equivalency",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text='Translate the environmental impact into something relatable and specific to your community. Use local landmarks, familiar distances, or everyday activities. Start with "That\'s equivalent to" or "That\'s like" for consistency. Example: "That\'s equivalent to avoiding <b>575 round trips</b> between City Hall and the waterfront"',
                        max_length=120,
                        verbose_name="local equivalency comparison",
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=(
                            "name",
                            "description",
                            "impact_statement",
                            "local_equivalency",
                        ),
                        required_languages=(),
                        virtual_fields=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.aplansimage",
                        verbose_name="image",
                    ),
                ),
                (
                    "plan",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to="actions.plan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "pledge",
                "verbose_name_plural": "pledges",
                "ordering": ["plan", "order"],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name="PledgeActionThrough",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="actions.action"
                    ),
                ),
                (
                    "pledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledge_action_through",
                        to="actions.pledge",
                    ),
                ),
            ],
            options={
                "verbose_name": "pledge action",
                "verbose_name_plural": "pledge actions",
                "db_table": "actions_pledge_actions",
                "unique_together": {("pledge", "action")},
            },
        ),
        migrations.AddField(
            model_name="pledge",
            name="actions",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Actions this pledge supports",
                through="actions.PledgeActionThrough",
                to="actions.action",
                verbose_name="actions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pledge",
            unique_together={("plan", "slug")},
        ),
    ]
