# Generated by Django 5.2 on 2026-02-02 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0158_add_community_engagement_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="PledgeUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Freeform key-value data about the user (e.g., zip_code)",
                        verbose_name="user data",
                    ),
                ),
            ],
            options={
                "verbose_name": "pledge user",
                "verbose_name_plural": "pledge users",
                "db_table": "actions_pledgeuser",
            },
        ),
    ]
