# Generated by Django 5.2 on 2026-02-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0159_add_pledgeuser_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PledgeCommitment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "pledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="actions.pledge",
                        verbose_name="pledge",
                    ),
                ),
                (
                    "pledge_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="actions.pledgeuser",
                        verbose_name="pledge user",
                    ),
                ),
            ],
            options={
                "verbose_name": "pledge commitment",
                "verbose_name_plural": "pledge commitments",
                "unique_together": {("pledge", "pledge_user")},
            },
        ),
    ]
