# Generated by Django 5.2 on 2026-02-12 16:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0161_add_pledge_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive plans are hidden from public view and most admin interfaces.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="attributetype",
            name="format",
            field=models.CharField(
                choices=[
                    ("ordered_choice", "Ordered choice"),
                    ("optional_choice", "Optional choice with optional text"),
                    ("unordered_choice", "Choice"),
                    ("text", "Text"),
                    ("rich_text", "Rich text"),
                    ("numeric", "Numeric"),
                    ("category_choice", "Category"),
                ],
                help_text="The format of the attributes with this type",
                max_length=50,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief description shown on pledge cards and at the top of the pledge page. Keep it under 2-3 sentences. Use the body content below for additional details.",
                max_length=300,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="impact_statement",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text='Describe the total environmental benefit if this many residents commit. Include specific numbers and units. Start with "We save" or "We reduce" for consistency. Example: "We save 9,200kg CO₂e each year."',
                max_length=150,
                verbose_name="environmental impact at scale",
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="local_equivalency",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text='Translate the environmental impact into something relatable and specific to your community. Use local landmarks, familiar distances, or everyday activities. Start with "That\'s equivalent to" or "That\'s like" for consistency. Example: "That\'s equivalent to avoiding 575 round trips between City Hall and the waterfront."',
                max_length=150,
                verbose_name="local equivalency comparison",
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="slug",
            field=models.SlugField(
                help_text="The unique part of the page's URL, usually based on the title. Use lowercase letters, numbers, and hyphens only (e.g., turn-off-electronics).",
                max_length=100,
                verbose_name="slug",
            ),
        ),
    ]
