# Generated by Django 6.0.2 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0163_merge_0162_add_plan_is_active_0162_attributetype_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributetype",
            name="format",
            field=models.CharField(
                choices=[
                    ("ordered_choice", "Ordered choice"),
                    ("optional_choice", "Optional choice with optional text"),
                    ("unordered_choice", "Choice"),
                    ("text", "Text"),
                    ("rich_text", "Rich text"),
                    ("numeric", "Numeric"),
                    ("category_choice", "Category"),
                ],
                help_text="The format of the fields with this type",
                max_length=50,
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive plans are only visible to superusers.",
                verbose_name="is active",
            ),
        ),
    ]
