# Generated by Django 6.0.2 on 2026-03-02 09:17

import modeltrans.fields
import re
from django.db import migrations


def rename_i18n_keys(apps, schema_editor):
    ActionTask = apps.get_model('actions', 'ActionTask')
    to_update = []
    for instance in ActionTask.objects.all():
        if instance.i18n:
            instance.i18n = {
                re.sub(r'^comment', 'details', k): v
                for k, v in instance.i18n.items()
            }
            to_update.append(instance)
    ActionTask.objects.bulk_update(to_update, ['i18n'])


def rename_i18n_keys_reverse(apps, schema_editor):
    ActionTask = apps.get_model('actions', 'ActionTask')
    to_update = []
    for instance in ActionTask.objects.all():
        if instance.i18n:
            instance.i18n = {
                re.sub(r'^details', 'comment', k): v
                for k, v in instance.i18n.items()
            }
            to_update.append(instance)
    ActionTask.objects.bulk_update(to_update, ['i18n'])


def rename_task_fields_in_revisions(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    Revision = apps.get_model('wagtailcore', 'Revision')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    action_ct = ContentType.objects.get_for_model(Action)
    revisions = Revision.objects.filter(content_type=action_ct).iterator()
    to_update = []
    for revision in revisions:
        tasks = revision.content.get('tasks')
        if not tasks:
            continue
        changed = False
        for task in tasks:
            renamed = {
                re.sub(r'^comment', 'details', k): v
                for k, v in task.items()
            }
            if task.get('i18n'):
                renamed['i18n'] = {
                    re.sub(r'^comment', 'details', k): v
                    for k, v in task['i18n'].items()
                }
            if renamed != task:
                task.clear()
                task.update(renamed)
                changed = True
        if changed:
            to_update.append(revision)
    Revision.objects.bulk_update(to_update, ['content'])


def rename_task_fields_in_revisions_reverse(apps, schema_editor):
    Action = apps.get_model('actions', 'Action')
    Revision = apps.get_model('wagtailcore', 'Revision')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    action_ct = ContentType.objects.get_for_model(Action)
    revisions = Revision.objects.filter(content_type=action_ct).iterator()
    to_update = []
    for revision in revisions:
        tasks = revision.content.get('tasks')
        if not tasks:
            continue
        changed = False
        for task in tasks:
            renamed = {
                re.sub(r'^details', 'comment', k): v
                for k, v in task.items()
            }
            if task.get('i18n'):
                renamed['i18n'] = {
                    re.sub(r'^details', 'comment', k): v
                    for k, v in task['i18n'].items()
                }
            if renamed != task:
                task.clear()
                task.update(renamed)
                changed = True
        if changed:
            to_update.append(revision)
    Revision.objects.bulk_update(to_update, ['content'])


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0164_alter_attributetype_format_alter_plan_is_active"),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiontask',
            old_name='comment',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'details'), required_languages=(), virtual_fields=True),
        ),
        migrations.RunPython(rename_i18n_keys, rename_i18n_keys_reverse),
        migrations.RunPython(rename_task_fields_in_revisions, rename_task_fields_in_revisions_reverse),
    ]
