# Generated by Django 6.0.2 on 2026-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0167_planfeatures_enable_action_pdf_export_in_public_ui"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatures",
            name="enable_indicator_factors",
            field=models.BooleanField(
                default=False,
                help_text="Enable computed factor values for indicators.",
                verbose_name="Enable indicator factors",
            ),
        ),
    ]
