# Generated by Django 6.0.2 on 2026-04-20 06:52

import aplans.utils
import django.db.models.deletion
import kausal_common.i18n.helpers
import modelcluster.fields
import uuid
from django.db import migrations, models


def assign_unique_translation_keys(apps, schema_editor):
    Pledge = apps.get_model('actions', 'Pledge')
    for pledge in Pledge.objects.all():
        pledge.translation_key = uuid.uuid4()
        pledge.save(update_fields=['translation_key'])


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0168_planfeatures_enable_indicator_factors"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pledge",
            unique_together={("plan", "slug")},
        ),
        migrations.AddField(
            model_name="pledge",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pledge",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="attributetype",
            name="other_languages",
            field=aplans.utils.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("da", "Danish"),
                        ("de", "German"),
                        ("de-CH", "German (Switzerland)"),
                        ("el", "Greek"),
                        ("en", "English (United States)"),
                        ("en-AU", "English (Australia)"),
                        ("en-GB", "English (United Kingdom)"),
                        ("es", "Spanish"),
                        ("es-US", "Spanish (United States)"),
                        ("fi", "Finnish"),
                        ("lv", "Latvian"),
                        ("mww", "Hmong (White)"),
                        ("pt", "Portuguese"),
                        ("pt-BR", "Portuguese (Brazil)"),
                        ("so", "Somali"),
                        ("sv", "Swedish"),
                        ("sv-FI", "Swedish (Finland)"),
                    ],
                    max_length=8,
                ),
                blank=True,
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="attributetype",
            name="primary_language",
            field=models.CharField(
                choices=[
                    ("da", "Danish"),
                    ("de", "German"),
                    ("de-CH", "German (Switzerland)"),
                    ("el", "Greek"),
                    ("en", "English (United States)"),
                    ("en-AU", "English (Australia)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("es", "Spanish"),
                    ("es-US", "Spanish (United States)"),
                    ("fi", "Finnish"),
                    ("lv", "Latvian"),
                    ("mww", "Hmong (White)"),
                    ("pt", "Portuguese"),
                    ("pt-BR", "Portuguese (Brazil)"),
                    ("so", "Somali"),
                    ("sv", "Swedish"),
                    ("sv-FI", "Swedish (Finland)"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="categoryicon",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("da", "Danish"),
                    ("de", "German"),
                    ("de-CH", "German (Switzerland)"),
                    ("el", "Greek"),
                    ("en", "English (United States)"),
                    ("en-AU", "English (Australia)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("es", "Spanish"),
                    ("es-US", "Spanish (United States)"),
                    ("fi", "Finnish"),
                    ("lv", "Latvian"),
                    ("mww", "Hmong (White)"),
                    ("pt", "Portuguese"),
                    ("pt-BR", "Portuguese (Brazil)"),
                    ("so", "Somali"),
                    ("sv", "Swedish"),
                    ("sv-FI", "Swedish (Finland)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commoncategoryicon",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("da", "Danish"),
                    ("de", "German"),
                    ("de-CH", "German (Switzerland)"),
                    ("el", "Greek"),
                    ("en", "English (United States)"),
                    ("en-AU", "English (Australia)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("es", "Spanish"),
                    ("es-US", "Spanish (United States)"),
                    ("fi", "Finnish"),
                    ("lv", "Latvian"),
                    ("mww", "Hmong (White)"),
                    ("pt", "Portuguese"),
                    ("pt-BR", "Portuguese (Brazil)"),
                    ("so", "Somali"),
                    ("sv", "Swedish"),
                    ("sv-FI", "Swedish (Finland)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commoncategorytype",
            name="primary_language",
            field=models.CharField(
                choices=[
                    ("da", "Danish"),
                    ("de", "German"),
                    ("de-CH", "German (Switzerland)"),
                    ("el", "Greek"),
                    ("en", "English (United States)"),
                    ("en-AU", "English (Australia)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("es", "Spanish"),
                    ("es-US", "Spanish (United States)"),
                    ("fi", "Finnish"),
                    ("lv", "Latvian"),
                    ("mww", "Hmong (White)"),
                    ("pt", "Portuguese"),
                    ("pt-BR", "Portuguese (Brazil)"),
                    ("so", "Somali"),
                    ("sv", "Swedish"),
                    ("sv-FI", "Swedish (Finland)"),
                ],
                default="en",
                max_length=20,
                verbose_name="primary language",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="identifier",
            field=aplans.utils.IdentifierField(
                help_text="A unique identifier for the plan used internally to distinguish between plans. This becomes part of the site URL used during onboarding. Use lowercase letters and dashes.",
                max_length=50,
                unique=True,
                validators=[aplans.utils.IdentifierValidator()],
                verbose_name="identifier",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="other_languages",
            field=aplans.utils.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("da", "Danish"),
                        ("de", "German"),
                        ("de-CH", "German (Switzerland)"),
                        ("el", "Greek"),
                        ("en", "English (United States)"),
                        ("en-AU", "English (Australia)"),
                        ("en-GB", "English (United Kingdom)"),
                        ("es", "Spanish"),
                        ("es-US", "Spanish (United States)"),
                        ("fi", "Finnish"),
                        ("lv", "Latvian"),
                        ("mww", "Hmong (White)"),
                        ("pt", "Portuguese"),
                        ("pt-BR", "Portuguese (Brazil)"),
                        ("so", "Somali"),
                        ("sv", "Swedish"),
                        ("sv-FI", "Swedish (Finland)"),
                    ],
                    default=kausal_common.i18n.helpers.get_default_language,
                    max_length=8,
                ),
                blank=True,
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="primary_language",
            field=models.CharField(
                choices=[
                    ("da", "Danish"),
                    ("de", "German"),
                    ("de-CH", "German (Switzerland)"),
                    ("el", "Greek"),
                    ("en", "English (United States)"),
                    ("en-AU", "English (Australia)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("es", "Spanish"),
                    ("es-US", "Spanish (United States)"),
                    ("fi", "Finnish"),
                    ("lv", "Latvian"),
                    ("mww", "Hmong (White)"),
                    ("pt", "Portuguese"),
                    ("pt-BR", "Portuguese (Brazil)"),
                    ("so", "Somali"),
                    ("sv", "Swedish"),
                    ("sv-FI", "Swedish (Finland)"),
                ],
                default=kausal_common.i18n.helpers.get_default_language,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="actions",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Actions this pledge supports",
                related_name="pledges",
                through="actions.PledgeActionThrough",
                to="actions.action",
                verbose_name="actions",
            ),
        ),
        migrations.RunPython(
            assign_unique_translation_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="pledge",
            unique_together={("plan", "slug"), ("translation_key", "locale")},
        ),
    ]
