# Generated by Django 6.0.2 on 2026-04-20 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


def assign_unique_translation_keys(apps, schema_editor):
    Pledge = apps.get_model('actions', 'Pledge')
    for pledge in Pledge.objects.all():
        pledge.translation_key = uuid.uuid4()
        pledge.save(update_fields=['translation_key'])


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0169_alter_attributetype_other_languages_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pledge",
            unique_together={("plan", "slug")},
        ),
        migrations.AddField(
            model_name="pledge",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pledge",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(
            assign_unique_translation_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="pledge",
            unique_together={("plan", "slug"), ("translation_key", "locale")},
        ),
    ]
