# Generated by Django 6.0.2 on 2026-04-20 07:45

from __future__ import annotations

import uuid
from typing import Any

from django.db import migrations


TRANSLATABLE_FIELDS = (
    'name',
    'description',
    'impact_statement',
    'local_equivalency',
)


def _normalize_language_code(language_code: str) -> str:
    """Normalize to Wagtail format: lowercase language, uppercase region, hyphen separator."""
    code = language_code.replace('_', '-')
    parts = code.split('-', 1)
    result = parts[0].lower()
    if len(parts) > 1:
        result += f'-{parts[1].upper()}'
    return result


def _get_or_create_locale(locale_model: type[Any], language_code: str) -> Any:
    normalized = _normalize_language_code(language_code)
    locale = locale_model.objects.filter(language_code__iexact=normalized).first()
    if locale is not None:
        return locale
    return locale_model.objects.create(language_code=normalized)


def _extract_translations(i18n_data: object) -> dict[str, dict[str, Any]]:
    translations_by_language: dict[str, dict[str, str]] = {}
    if not isinstance(i18n_data, dict):
        return translations_by_language

    for key, value in i18n_data.items():
        if value in (None, ''):
            continue
        for field_name in TRANSLATABLE_FIELDS:
            prefix = f'{field_name}_'
            if not key.startswith(prefix):
                continue
            language_code = _normalize_language_code(key[len(prefix):])
            if not language_code:
                continue
            translations_by_language.setdefault(language_code, {})[field_name] = value
            break

    return translations_by_language


def _copy_pledge_for_locale(pledge_model: type[Any], source_pledge: Any, locale: Any, translated_values: dict[str, Any]) -> Any:
    field_values: dict[str, Any] = {}
    for field in source_pledge._meta.concrete_fields:
        if field.primary_key or field.name in {'uuid', 'locale'}:
            continue
        field_values[field.attname] = getattr(source_pledge, field.attname)

    field_values['uuid'] = uuid.uuid4()
    field_values['locale_id'] = locale.id
    field_values['i18n'] = {}
    field_values.update(translated_values)
    return pledge_model.objects.create(**field_values)


def migrate_pledges_to_locale_copies(apps, schema_editor):  # noqa: C901
    Pledge = apps.get_model('actions', 'Pledge')
    Locale = apps.get_model('wagtailcore', 'Locale')

    pledge_groups: dict[tuple[int, uuid.UUID], list] = {}
    pledges = (
        Pledge.objects
        .select_related('plan', 'locale')
        .order_by('plan_id', 'translation_key', 'id')
    )
    for pledge in pledges:
        group_key = (pledge.plan_id, pledge.translation_key)
        pledge_groups.setdefault(group_key, []).append(pledge)

    for group in pledge_groups.values():
        source_pledge = group[0]
        plan = source_pledge.plan

        plan_language_codes = [plan.primary_language, *plan.other_languages]
        locale_by_language: dict[str, object] = {}
        for language_code in plan_language_codes:
            locale = _get_or_create_locale(Locale, language_code)
            locale_by_language[_normalize_language_code(language_code)] = locale

        primary_locale = locale_by_language[_normalize_language_code(plan.primary_language)]
        pledges_by_locale_id = {pledge.locale_id: pledge for pledge in group}

        primary_pledge = pledges_by_locale_id.get(primary_locale.id)
        if primary_pledge is None:
            primary_pledge = source_pledge
            if primary_pledge.locale_id != primary_locale.id:
                primary_pledge.locale_id = primary_locale.id
                primary_pledge.save(update_fields=['locale'])
            pledges_by_locale_id[primary_locale.id] = primary_pledge

        source_pledge = primary_pledge
        translated_values = _extract_translations(source_pledge.i18n)
        action_ids = list(source_pledge.actions.values_list('id', flat=True))

        for language_code, locale in locale_by_language.items():
            pledge = pledges_by_locale_id.get(locale.id)
            locale_translations = translated_values.get(language_code, {})

            if pledge is None:
                pledge = _copy_pledge_for_locale(Pledge, source_pledge, locale, locale_translations)
                if action_ids:
                    pledge.actions.set(action_ids)
                pledges_by_locale_id[locale.id] = pledge
                continue

            update_fields: list[str] = []
            if pledge.i18n:
                pledge.i18n = {}
                update_fields.append('i18n')
            for field_name, translated_value in locale_translations.items():
                if getattr(pledge, field_name) == translated_value:
                    continue
                setattr(pledge, field_name, translated_value)
                update_fields.append(field_name)
            if update_fields:
                pledge.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0169_alter_pledge_unique_together_pledge_locale_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pledge',
            unique_together={('plan', 'slug', 'locale'), ('translation_key', 'locale')},
        ),
        migrations.RunPython(
            migrate_pledges_to_locale_copies,
            migrations.RunPython.noop,
        ),
    ]
