# Generated by Django 6.0.2 on 2026-04-20 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0170_migrate_pledges_to_locale_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='i18n',
        ),
    ]
