# Generated by Django 6.0.2 on 2026-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0177_add_publicuser_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributetypechoiceoption",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
