# Generated by Django 6.0.2 on 2026-06-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0181_alter_planfeatures_allow_public_site_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicuser",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Set when the user signs up; used for PIN-based authentication.",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AddField(
            model_name="publicuser",
            name="marketing_consented_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="marketing consented at"
            ),
        ),
        migrations.AddField(
            model_name="publicuser",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="terms accepted at"
            ),
        ),
        migrations.CreateModel(
            name="PublicUserSignInAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin_hash", models.CharField(editable=False, max_length=64)),
                ("pin_salt", models.CharField(editable=False, max_length=32)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("anon_uuid", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "public_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_in_attempt",
                        to="actions.publicuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "public user sign-in attempt",
                "verbose_name_plural": "public user sign-in attempts",
            },
        ),
    ]
