# Generated by Django 6.0.2 on 2026-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0181_add_publicuser_email_and_signin_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicuser",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="email verified at"
            ),
        ),
    ]
