# Generated by Django 6.0.2 on 2026-06-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0182_add_publicuser_email_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicusersigninattempt",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="publicusersigninattempt",
            name="pending_marketing_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicusersigninattempt",
            name="pending_terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicusersigninattempt",
            name="public_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sign_in_attempt",
                to="actions.publicuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicusersigninattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("public_user__isnull", True)),
                fields=("email",),
                name="unique_pending_signup_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicusersigninattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_user__isnull", False),
                    models.Q(
                        ("email__isnull", False),
                        ("pending_terms_accepted_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="attempt_has_user_or_pending_signup",
            ),
        ),
    ]
