# Generated by Django 3.2.9 on 2022-01-17 15:11

import actions.models.plan
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_categorytype_select_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandomain',
            name='base_path',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message="Base path must begin with a '/' and not end with '/'", regex='^\\/[a-z_-]+')], verbose_name='base path'),
        ),
        migrations.AlterField(
            model_name='plandomain',
            name='hostname',
            field=models.CharField(db_index=True, max_length=200, validators=[actions.models.plan.is_valid_hostname], verbose_name='host name'),
        ),
        migrations.AlterUniqueTogether(
            name='plandomain',
            unique_together={('hostname', 'base_path')},
        ),
    ]
