# Generated by Django 3.2.12 on 2022-03-03 14:29

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_generalplanadmin_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
    ]
