# Generated by Django 3.2.12 on 2022-03-07 16:08

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_categorytype_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontask',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'comment'), required_languages=(), virtual_fields=True),
        ),
    ]
