# Generated by Django 3.2.13 on 2022-05-19 20:09

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_common_categories'),
        ('actions', '0026_symmetrical_related_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='related_actions',
            field=models.ManyToManyField(blank=True, related_name='_actions_action_related_actions_+', to='actions.Action'),
        ),
        migrations.CreateModel(
            name='CommonCategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('identifier', aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('usable_for_actions', models.BooleanField(default=False, verbose_name='usable for action categorization')),
                ('usable_for_indicators', models.BooleanField(default=False, verbose_name='usable for indicator categorization')),
                ('editable_for_actions', models.BooleanField(default=False, verbose_name='editable for actions')),
                ('editable_for_indicators', models.BooleanField(default=False, verbose_name='editable for indicators')),
                ('select_widget', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], max_length=30)),
                ('primary_language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default='en', max_length=20)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'common category type',
                'verbose_name_plural': 'common category types',
                'ordering': ('identifier',),
                'unique_together': {('identifier',)},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='common_category_types',
            field=models.ManyToManyField(blank=True, related_name='plans', to='actions.CommonCategoryType'),
        ),
        migrations.CreateModel(
            name='CommonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('identifier', aplans.utils.IdentifierField(max_length=50, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('short_description', models.TextField(blank=True, max_length=200, verbose_name='short description')),
                ('color', models.CharField(blank=True, help_text='Set if the category has a theme color', max_length=50, null=True, validators=[aplans.utils.validate_css_color], verbose_name='theme color')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name', 'short_description'), required_languages=(), virtual_fields=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.aplansimage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='actions.commoncategorytype', verbose_name='type')),
            ],
            options={
                'unique_together': {('type', 'identifier')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='common',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_instances', to='actions.commoncategory', verbose_name='common category'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='common',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_type_instances', to='actions.commoncategorytype', verbose_name='common category type'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='synchronize_with_pages',
            field=models.BooleanField(default=False, help_text='Set if categories of this type should be synchronized with pages', verbose_name='synchronize with pages'),
        ),
        migrations.CreateModel(
            name='CommonCategoryIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='actions.commoncategory', verbose_name='category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.aplansimage')),
            ],
            options={
                'unique_together': {('category', 'language')},
            },
        ),
    ]
