# Generated by Django 3.2.13 on 2022-08-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0034_alter_plan_action_days_until_considered_stale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='primary_action_classification',
            field=models.ForeignKey(blank=True, help_text='Used for primary navigation and grouping of actions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_with_primary_classification', to='actions.categorytype', verbose_name='The primary category type'),
        ),
        migrations.AddField(
            model_name='plan',
            name='secondary_action_classification',
            field=models.ForeignKey(blank=True, help_text='Action filters based on this category are displayed more prominently than filters of other categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_with_secondary_classification', to='actions.categorytype', verbose_name='A secondary category type'),
        ),
    ]
