# Generated by Django 3.2.13 on 2022-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0038_rename_category_short_description_to_lead_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='help_text',
            field=models.TextField(default='', verbose_name='help text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='help_text',
            field=models.TextField(default='', verbose_name='help text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytype',
            name='help_text',
            field=models.TextField(default='', verbose_name='help text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoncategory',
            name='help_text',
            field=models.TextField(default='', verbose_name='help text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoncategorytype',
            name='help_text',
            field=models.TextField(default='', verbose_name='help text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='lead_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='lead paragraph'),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='lead_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='lead paragraph'),
        ),
        migrations.AlterField(
            model_name='category',
            name='lead_paragraph',
            field=models.TextField(blank=True, max_length=200, verbose_name='lead paragraph'),
        ),
        migrations.AlterField(
            model_name='commoncategory',
            name='lead_paragraph',
            field=models.TextField(blank=True, max_length=200, verbose_name='lead paragraph'),
        ),
    ]
