# Generated by Django 3.2.13 on 2022-09-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0041_planfeatures_enable_indicator_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionresponsibleparty',
            name='role',
            field=models.CharField(blank=True, choices=[(None, 'Unspecified'), ('primary', 'Primary responsible party'), ('collaborator', 'Collaborator')], max_length=40, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='actionresponsibleparty',
            name='specifier',
            field=models.CharField(blank=True, help_text='The responsibility domain for the organization', max_length=255, verbose_name='specifier'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='enable_indicator_comparison',
            field=models.BooleanField(default=True, help_text='Set to enable comparing indicators between organizations', null=True, verbose_name='Enable indicator comparison'),
        ),
    ]
