# Generated by Django 3.2.13 on 2022-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0045_add_category_choice_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='has_zero_option',
            field=models.BooleanField(default=False, help_text='If the format is "ordered choice", determines whether the first option is displayed with zero bullets instead of one', verbose_name='has zero option'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='show_choice_names',
            field=models.BooleanField(default=True, help_text='If the format is "ordered choice", determines whether the choice names are displayed', verbose_name='show choice names'),
        ),
    ]
