# Generated by Django 3.2.13 on 2022-10-17 20:22

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0046_add_ordered_choice_attribute_type_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributetypechoiceoption',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attributetypechoiceoption',
            constraint=models.UniqueConstraint(fields=('type', 'identifier'), name='unique_identifier_per_type'),
        ),
        migrations.AddConstraint(
            model_name='attributetypechoiceoption',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('type', 'order'), name='unique_order_per_type'),
        ),
    ]
