# Generated by Django 3.2.13 on 2022-11-17 08:00

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0049_alter_category_type_select_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='commoncategory',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text'), required_languages=(), virtual_fields=True),
        ),
    ]
