# Generated by Django 3.2.13 on 2022-11-18 14:50

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0051_enlarge_category_lead_paragraph_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='instances_editable_by',
            field=models.CharField(blank=True, choices=[('not_editable', 'Not editable'), ('plan_admins', 'Plan admins'), ('contact_persons', 'Contact persons')], max_length=50, verbose_name='Edit rights'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='instances_editable_by',
            field=models.CharField(blank=True, choices=[('not_editable', 'Not editable'), ('plan_admins', 'Plan admins'), ('contact_persons', 'Contact persons')], max_length=50, verbose_name='Edit rights'),
        ),
        migrations.AlterField(
            model_name='category',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='select_widget',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', help_text='Choose "Multiple" only if more than one category can be selected at a time, otherwise choose "Single" which is the default.', max_length=30, verbose_name='single or multiple selection'),
        ),
        migrations.AlterField(
            model_name='commoncategory',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='select_widget',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', help_text='Choose "Multiple" only if more than one category can be selected at a time, otherwise choose "Single" which is the default.', max_length=30, verbose_name='single or multiple selection'),
        ),
    ]
