# Generated by Django 3.2.13 on 2022-11-24 16:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0053_report_reporttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='format',
            field=models.CharField(choices=[('ordered_choice', 'Ordered choice'), ('optional_choice', 'Optional choice with optional text'), ('text', 'Text'), ('rich_text', 'Rich text'), ('numeric', 'Numeric'), ('category_choice', 'Category')], max_length=50, verbose_name='Format'),
        ),
        migrations.CreateModel(
            name='AttributeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Text')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('type', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_attributes', to='actions.attributetype')),
            ],
            options={
                'unique_together': {('type', 'content_type', 'object_id')},
            },
        ),
    ]
