# Generated by Django 3.2.13 on 2022-11-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0053_add_action_update_interval_settings_to_plan'),
        ('actions', '0056_report_fields'),
    ]

    operations = [
    ]
