# Generated by Django 3.2.13 on 2022-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0060_planfeatures_show_action_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='version_name',
            field=models.CharField(blank=True, help_text='If this plan has multiple versions, name of this version', max_length=100, verbose_name='version name'),
        ),
    ]
