# Generated by Django 3.2.16 on 2023-12-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0099_make_category_identifier_longer'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='display_field_visibility_restrictions',
            field=models.BooleanField(default=False, help_text='For plans which have field-specific visibility restrictions, show to users which fields are public and which are restricted.', verbose_name='Display field visibility as a label in edit views'),
        ),
    ]
