# Generated by Django 3.2.16 on 2024-03-18 08:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0112_alter_action_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDependencyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('plan', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_dependency_roles', to='actions.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ActionDependencyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preceding_relationships', to='actions.action', verbose_name='Dependent action')),
                ('preceding', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_relationships', to='actions.action', verbose_name='Preceding action')),
                ('preceding_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='actions.actiondependencyrole', verbose_name='Preceding action role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actiondependencyrole',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_plan_order'),
        ),
        migrations.AddConstraint(
            model_name='actiondependencyrole',
            constraint=models.UniqueConstraint(fields=('plan', 'name'), name='unique_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='actiondependencyrelationship',
            constraint=models.UniqueConstraint(fields=('preceding', 'dependent'), name='unique_pairs'),
        ),
    ]
