# Generated by Django 5.0.4 on 2024-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0122_rename_action_plan_order_actions_act_plan_id_35d9e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='indicator_ordering',
            field=models.CharField(choices=[('none', 'No ordering'), ('name', 'Order by name')], default='none', help_text='Choose how to order Indicators in the public UI', max_length=50, verbose_name='Indicator order'),
        ),
    ]
