# Generated by Django 5.0.6 on 2024-08-13 09:20

from django.db import migrations

def update_deployment_environment(apps, schema_editor):
    PlanDomain = apps.get_model('actions', 'PlanDomain')
    PlanDomain.objects.filter(deployment_environment='testing').update(deployment_environment='preview')

class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0128_alter_deployment_environment_types'),
    ]

    operations = [
        migrations.RunPython(update_deployment_environment),
    ]
