# Generated by Django 5.0.6 on 2024-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0131_category_kausal_paths_node_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='admin_accessibility_conformance_level',
            field=models.CharField(choices=[('default', 'No extra accessibility fixes active'), ('high', 'This plan requires extra accessibility fixes')], default='default'),
        ),
    ]
