# Generated by Django 5.0.6 on 2024-12-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0134_create_equivalent_through_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="copy_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Set if this action has been created by copying another action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="actions.action",
                verbose_name="copy of",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="copy_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Set if this plan has been created by copying another plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="actions.plan",
                verbose_name="copy of",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="manual_status_reason",
            field=models.TextField(
                blank=True,
                help_text="Describe the reason why this action has this status",
                null=True,
                verbose_name="specifier for status",
            ),
        ),
        migrations.AlterField(
            model_name="planfeatures",
            name="admin_accessibility_conformance_level",
            field=models.CharField(
                choices=[
                    ("default", "No extra accessibility fixes active"),
                    ("high", "This plan requires extra accessibility fixes"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
