# Generated by Django 5.0.6 on 2025-02-11 15:54

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0136_alter_plan_organization_alter_plan_short_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="exclude_from_search",
            field=models.BooleanField(
                default=False,
                help_text="Should information related to the plan be excluded from search results?",
                verbose_name="exclude from search",
            ),
        ),
        migrations.AlterField(
            model_name="categorylevel",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "name_plural"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
