# Generated by Django 5.0.6 on 2025-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0137_plan_exclude_from_search_alter_categorylevel_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatures",
            name="expose_unpublished_plan_only_to_authenticated_user",
            field=models.BooleanField(
                default=False,
                help_text="Should the plan be exposed only to authenticated users if not published?",
                verbose_name="Expose unpublished plan only to authenticated users",
            ),
        ),
    ]
