# Generated by Django 5.2 on 2025-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0138_planfeatures_expose_unpublished_plan_only_to_authenticated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeatures',
            name='expose_unpublished_plan_only_to_authenticated_user',
            field=models.BooleanField(default=True, help_text='Should the plan be exposed only to authenticated users if not published?', verbose_name='Expose unpublished plan only to authenticated users'),
        ),
    ]
