# Generated by Django 5.2 on 2025-07-01 18:14

import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0139_alter_planfeatures_expose_unpublished_plan_only_to_authenticated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionimplementationphase',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='actionstatus',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', help_text='Set if the category has a theme color', max_length=50, verbose_name='theme color'),
        ),
        migrations.AlterField(
            model_name='commoncategory',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', help_text='Set if the category has a theme color', max_length=50, verbose_name='theme color'),
        ),
        migrations.AlterField(
            model_name='impactgroup',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', max_length=16, verbose_name='color'),
        ),
    ]
