# Generated by Django 5.2 on 2025-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0140_alter_actionimplementationphase_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeatures',
            name='allow_public_site_login',
            field=models.BooleanField(default=True, help_text='Should users be able to have authenticated sessions in the public UI?', verbose_name='Allow logging in to the public website'),
        ),
    ]
