# Generated by Django 5.2 on 2025-08-28 13:16

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0141_alter_planfeatures_allow_public_site_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
