# Generated by Django 5.2 on 2025-11-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0144_alter_action_categories_alter_action_related_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kausal_paths_node_uuid',
            field=models.CharField(blank=True, default='', help_text='Kausal Paths node to link this category to', max_length=200, verbose_name='Kausal Paths node UUID'),
        ),
        migrations.AlterField(
            model_name='commoncategory',
            name='kausal_paths_node_uuid',
            field=models.CharField(blank=True, default='', help_text='Kausal Paths node to link this category to', max_length=200, verbose_name='Kausal Paths node UUID'),
        ),
    ]
