# Generated by Django 5.2 on 2025-11-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0146_planfeatures_indicators_open_in_modal'),
        ('indicators', '0035_indicator_visualizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main_goal', 'Main goal'), ('secondary_goal', 'Secondary goal')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_relationships', to='actions.category')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relationships', to='indicators.indicator')),
            ],
            options={
                'verbose_name': 'indicator category relationship',
                'verbose_name_plural': 'indicator category relationships',
                'unique_together': {('indicator', 'category')},
            },
        ),
    ]
