# Generated by Django 5.2 on 2025-12-29 15:01

import django.db.models.deletion
import modeltrans.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0149_actiondecisionlevel_latest_revision_and_more"),
        ("indicators", "0043_indicatorgoal_latest_revision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatures",
            name="enable_change_log",
            field=models.BooleanField(
                default=False,
                help_text="Prompt users to add a public change log message after editing actions, indicators, or categories.",
                verbose_name="Enable change log",
            ),
        ),
        migrations.AlterField(
            model_name="planfeatures",
            name="indicators_open_in_modal",
            field=models.BooleanField(
                default=False,
                help_text="Should indicators open only in a modal dialog in the public UI?",
                verbose_name="Indicators open in modal",
            ),
        ),
        migrations.CreateModel(
            name="ActionChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Summarize what was changed. This message will be displayed publicly.",
                        verbose_name="content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="actions.action",
                        verbose_name="action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "action change log message",
                "verbose_name_plural": "action change log messages",
            },
        ),
        migrations.CreateModel(
            name="CategoryChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Summarize what was changed. This message will be displayed publicly.",
                        verbose_name="content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="actions.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "category change log message",
                "verbose_name_plural": "category change log messages",
            },
        ),
        migrations.CreateModel(
            name="IndicatorChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Summarize what was changed. This message will be displayed publicly.",
                        verbose_name="content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="indicators.indicator",
                        verbose_name="indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicator change log message",
                "verbose_name_plural": "indicator change log messages",
            },
        ),
    ]
