# Generated by Django 5.2 on 2025-12-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0151_add_revision_to_action_change_log_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionchangelogmessage",
            name="content",
            field=models.TextField(
                help_text="Summarize what was changed. This message will be displayed publicly.",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="categorychangelogmessage",
            name="content",
            field=models.TextField(
                help_text="Summarize what was changed. This message will be displayed publicly.",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorchangelogmessage",
            name="content",
            field=models.TextField(
                help_text="Summarize what was changed. This message will be displayed publicly.",
                verbose_name="content",
            ),
        ),
    ]
