# Generated by Django 5.2 on 2026-01-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0152_alter_actionchangelogmessage_content_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionchangelogmessage",
            options={
                "verbose_name": "action change history message",
                "verbose_name_plural": "action change history messages",
            },
        ),
        migrations.AlterModelOptions(
            name="categorychangelogmessage",
            options={
                "verbose_name": "category change history message",
                "verbose_name_plural": "category change history messages",
            },
        ),
        migrations.AlterModelOptions(
            name="indicatorchangelogmessage",
            options={
                "verbose_name": "indicator change history message",
                "verbose_name_plural": "indicator change history messages",
            },
        ),
        migrations.AlterField(
            model_name="actionchangelogmessage",
            name="content",
            field=models.TextField(
                help_text="Please summarize the change you made. This message will be displayed publicly.",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="actionchangelogmessage",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                help_text="The revision this change history message is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="revision",
            ),
        ),
        migrations.AlterField(
            model_name="categorychangelogmessage",
            name="content",
            field=models.TextField(
                help_text="Please summarize the change you made. This message will be displayed publicly.",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorchangelogmessage",
            name="content",
            field=models.TextField(
                help_text="Please summarize the change you made. This message will be displayed publicly.",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="planfeatures",
            name="enable_change_log",
            field=models.BooleanField(
                default=False,
                help_text="Prompt users to add a public change history message after editing actions, indicators, or categories.",
                verbose_name="Enable change history messages",
            ),
        ),
    ]
