# Generated by Django 5.2 on 2026-01-15 10:32

from django.db import migrations


def populate_plan_in_changelogmessages(apps, schema_editor):
    ActionChangeLogMessage = apps.get_model('actions', 'ActionChangeLogMessage')
    CategoryChangeLogMessage = apps.get_model('actions', 'CategoryChangeLogMessage')
    IndicatorChangeLogMessage = apps.get_model('actions', 'IndicatorChangeLogMessage')

    # Populate plan for ActionChangeLogMessage from action.plan
    for msg in ActionChangeLogMessage.objects.select_related('action').all():
        msg.plan = msg.action.plan
        msg.save(update_fields=['plan'])

    # Populate plan for CategoryChangeLogMessage from category.type.plan
    for msg in CategoryChangeLogMessage.objects.select_related('category__type').all():
        msg.plan = msg.category.type.plan
        msg.save(update_fields=['plan'])

    # Populate plan for IndicatorChangeLogMessage from first plan in indicator.plans
    for msg in IndicatorChangeLogMessage.objects.prefetch_related('indicator__plans').all():
        plan = msg.indicator.plans.first()
        if plan:
            msg.plan = plan
            msg.save(update_fields=['plan'])


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0154_add_plan_to_changelogmessages"),
    ]

    operations = [
        migrations.RunPython(populate_plan_in_changelogmessages, migrations.RunPython.noop),
    ]
