# Generated by Django 5.2 on 2026-01-28 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0156_make_plan_non_nullable_in_changelogmessages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandomain",
            name="redirect_aliases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=80),
                blank=True,
                default=list,
                help_text="Domain names that will be used to redirect to the main hostname. Multiple domains are separated by commas.",
                size=None,
                verbose_name="redirect aliases",
            ),
        ),
    ]
