# Generated by Django 5.2 on 2026-02-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0161_add_pledge_updated_at"),
        ("images", "0007_aplansimage_latest_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributetype",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.aplansimage",
                verbose_name="Icon",
            ),
        ),
    ]
