# Generated by Django 6.0.2 on 2026-02-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0162_add_plan_is_active"),
        ("actions", "0162_attributetype_icon"),
    ]

    operations = []
