# Generated by Django 6.0.2 on 2026-03-16 08:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0165_rename_actiontask_comment_to_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontask",
            name="details",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="details"
            ),
        ),
    ]
