# Generated by Django 6.0.2 on 2026-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0166_alter_actiontask_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="planfeatures",
            name="enable_action_pdf_export_in_public_ui",
            field=models.BooleanField(
                default=False,
                help_text="Enable users of the public UI to export actions to PDF.",
                verbose_name="Enable PDF export of actions in public UI",
            ),
        ),
    ]
