# Generated by Django 6.0.2 on 2026-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0172_remove_pledge_i18n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontask",
            name="name",
            field=models.CharField(max_length=500, verbose_name="name"),
        ),
    ]
