# Generated by Django 6.0.2 on 2026-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0173_alter_actiontask_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionstatus",
            name="name",
            field=models.CharField(max_length=70, verbose_name="name"),
        ),
    ]
