# Generated by Django 6.0.2 on 2026-06-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0174_alter_actionstatus_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PledgeUser",
            new_name="PublicUser",
        ),
        migrations.AlterModelOptions(
            name="publicuser",
            options={
                "verbose_name": "public user",
                "verbose_name_plural": "public users",
            },
        ),
    ]
