# Generated by Django 6.0.2 on 2026-06-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0179_set_default_country_for_plans"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("images", "0007_aplansimage_latest_revision"),
        ("orgs", "0030_alter_organization_abbreviation_and_more"),
        ("people", "0018_alter_person_image_cropping"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(("country", ""), _negated=True),
                name="plan_country_required",
            ),
        ),
    ]
