# Generated by Django 6.0.2 on 2026-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0180_plan_plan_country_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfeatures",
            name="allow_public_site_login",
            field=models.BooleanField(
                default=True,
                help_text="Should users be able to have authenticated sessions in the public UI?",
                verbose_name="Allow logging in to the public website",
            ),
        ),
        migrations.AlterField(
            model_name="planfeatures",
            name="expose_unpublished_plan_only_to_authenticated_user",
            field=models.BooleanField(
                default=True,
                help_text="Should the plan be exposed only to authenticated users if not published?",
                verbose_name="Expose unpublished plan only to authenticated users",
            ),
        ),
    ]
