# Generated by Django 6.1 on 2026-08-29 07:45

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0181_alter_planfeatures_allow_public_site_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='admin_help_text',
            field=models.TextField(blank=True, help_text='If set, this is shown to admin users instead of the help text', verbose_name='help text for the admin UI'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='admin_help_text',
            field=models.TextField(blank=True, help_text='If set, this is shown to admin users instead of the help text', verbose_name='help text for the admin UI'),
        ),
        migrations.AddField(
            model_name='commoncategorytype',
            name='admin_help_text',
            field=models.TextField(blank=True, help_text='If set, this is shown to admin users instead of the help text', verbose_name='help text for the admin UI'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'help_text', 'admin_help_text'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text', 'admin_help_text'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_paragraph', 'help_text', 'admin_help_text'), required_languages=(), virtual_fields=True),
        ),
    ]
