# Generated by Django 6.1 on 2026-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0183_restrict_action_category_editing_to_plan_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='hide_from_search_engines',
            field=models.BooleanField(default=False, help_text='If set, the public website will instruct search engines not to index any of its pages.', verbose_name='Hide from search engines'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='admin_help_text',
            field=models.TextField(blank=True, help_text='If set, these instructions are shown to admin users instead of the help text', verbose_name='help text for the admin UI'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='help_text',
            field=models.TextField(blank=True, help_text='A help text shown to visitors of the site', verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='admin_help_text',
            field=models.TextField(blank=True, help_text='If set, these instructions are shown to admin users instead of the help text', verbose_name='help text for the admin UI'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='help_text',
            field=models.TextField(blank=True, help_text='A help text shown to visitors of the site', verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='admin_help_text',
            field=models.TextField(blank=True, help_text='If set, these instructions are shown to admin users instead of the help text', verbose_name='help text for the admin UI'),
        ),
        migrations.AlterField(
            model_name='commoncategorytype',
            name='help_text',
            field=models.TextField(blank=True, help_text='A help text shown to visitors of the site', verbose_name='help text'),
        ),
    ]
