# Generated by Django 6.1 on 2026-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0184_planfeatures_hide_from_search_engines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='show_parent_plan_in_plan_switcher',
            field=models.BooleanField(default=False, help_text='By default, the plan switcher in the public UI lists all related plans except the parent plan. If set, the parent plan is shown as well.', verbose_name='Show the parent plan in the plan switcher'),
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='hide_from_search_engines',
            field=models.BooleanField(default=False, help_text='If set, the public production site of a published plan will instruct search engines not to index any of its pages. Unpublished plans and preview sites are always excluded from indexing regardless of this setting.', verbose_name='Hide published plan from search engines'),
        ),
    ]
