# Generated by Django 6.0.2 on 2026-08-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0184_publicusersigninattempt_email_and_more"),
        ("admin_site", "0018_clientplan_is_primary"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="publicusersigninattempt",
            name="unique_pending_signup_email",
        ),
        migrations.RemoveConstraint(
            model_name="publicusersigninattempt",
            name="attempt_has_user_or_pending_signup",
        ),
        migrations.AddField(
            model_name="publicuser",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this account belongs to. Required for authed rows; null for anonymous rows.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_users",
                to="admin_site.client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="publicusersigninattempt",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="admin_site.client",
            ),
        ),
        migrations.AlterField(
            model_name="publicuser",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Set when the user signs up; used for PIN-based authentication.",
                max_length=254,
                null=True,
                verbose_name="email",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email", "client"),
                name="unique_public_user_email_per_client",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", True), ("client__isnull", False), _connector="OR"
                ),
                name="public_user_email_requires_client",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicusersigninattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("public_user__isnull", True)),
                fields=("email", "client"),
                name="unique_pending_signup_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicusersigninattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_user__isnull", False),
                    models.Q(
                        ("email__isnull", False),
                        ("client__isnull", False),
                        ("pending_terms_accepted_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="attempt_has_user_or_pending_signup",
            ),
        ),
    ]
