# Generated by Django 6.1 on 2026-09-16 14:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0192_rename_present_plan_hierarchy_as_peers'),
        ('orgs', '0030_alter_organization_abbreviation_and_more'),
        ('people', '0018_alter_person_image_cropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaskContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_for_action_tasks', to='people.person', verbose_name='person')),
                ('task', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='actions.actiontask', verbose_name='action task')),
            ],
            options={
                'verbose_name': 'action task contact person',
                'verbose_name_plural': 'action task contact persons',
                'unique_together': {('task', 'person')},
            },
        ),
        migrations.CreateModel(
            name='ActionTaskResponsibleParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_action_tasks', to='orgs.organization', verbose_name='organization')),
                ('task', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_parties', to='actions.actiontask', verbose_name='action task')),
            ],
            options={
                'verbose_name': 'action task responsible party',
                'verbose_name_plural': 'action task responsible parties',
                'unique_together': {('task', 'organization')},
            },
        ),
    ]
