# Generated by Django 6.1 on 2026-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0193_actiontaskcontactperson_actiontaskresponsibleparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='has_action_task_assignees',
            field=models.BooleanField(default=False, help_text='Should the organizations and people responsible for an individual task be recorded? Off by default; the assignments are hidden everywhere while it is off, including in plans that already have some.', verbose_name='Assign responsible parties and contact persons to tasks'),
        ),
    ]
