# Generated by Django 6.1 on 2026-09-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0193_plan_visibility'),
        ('actions', '0194_planfeatures_has_action_task_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeatures',
            name='expose_unpublished_plan_only_to_authenticated_user',
        ),
    ]
