# Generated by Django 6.1 on 2026-09-30 13:34

import aplans.utils
import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0196_rename_show_login_link_in_public_ui'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                (
                    'identifier',
                    aplans.utils.IdentifierField(
                        help_text='The key under which answers are stored, e.g. postal_code. It cannot be changed after the field is saved.',
                        max_length=50,
                        validators=[aplans.utils.IdentifierValidator()],
                        verbose_name='identifier',
                    ),
                ),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='help text')),
                ('placeholder', models.CharField(blank=True, max_length=100, verbose_name='placeholder')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                (
                    'i18n',
                    modeltrans.fields.TranslationField(
                        fields=('label', 'help_text', 'placeholder'), required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    'plan',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pledge_form_fields',
                        to='actions.plan',
                        verbose_name='plan',
                    ),
                ),
            ],
            options={
                'verbose_name': 'pledge form field',
                'verbose_name_plural': 'pledge form fields',
                'ordering': ('plan', 'order'),
                'unique_together': {('plan', 'identifier')},
            },
        ),
    ]
