# Generated by Django 6.1 on 2026-09-25 10:23

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0196_rename_show_login_link_in_public_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='access_request_contact_email',
            field=models.EmailField(blank=True, db_default='', help_text='Where people whose access request was not approved can ask for more information.', max_length=254, verbose_name='Contact email for access requests'),
        ),
        migrations.AddField(
            model_name='plan',
            name='access_request_eligibility_text',
            field=models.TextField(blank=True, help_text='Shown to people requesting access, and in the email telling them their request was not approved. For example: "Access is only given to staff of the ministry."', null=True, verbose_name='Who may be given access'),
        ),
        migrations.AddField(
            model_name='planfeatures',
            name='enable_access_requests',
            field=models.BooleanField(db_default=False, default=False, help_text='Let visitors of an internal plan ask for access to its public site. Plan admins approve or reject the requests.', verbose_name='Enable access requests'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name', 'short_name', 'access_request_eligibility_text'], required_languages=(), virtual_fields=True),
        ),
    ]
