# Generated by Django 6.1 on 2026-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0198_pledge_form_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeatures',
            name='enable_community_engagement_accounts',
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text='Let people create an account with their email after committing to a pledge, so they can come back to their pledges. When off, everyone takes part anonymously.',
                verbose_name='Offer accounts for community engagement',
            ),
        ),
    ]
