# Generated by Django 6.0.2 on 2026-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0199_planfeatures_enable_community_engagement_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='version',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='Monotonic counter used as an optimistic-concurrency token for bulk edits. Bumped on every conflict-checked write; not meant for display.', verbose_name='version'),
        ),
    ]
