# Generated by Django 6.1 on 2026-10-05 11:57

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0200_action_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pledge_account_description',
            field=models.TextField(
                blank=True,
                help_text='Shown below the title. Leave empty to use "Save your pledges and come back to track your progress."',
                null=True,
                verbose_name='Account invitation text',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='pledge_account_title',
            field=models.CharField(
                blank=True,
                help_text='Shown when people are invited to create an account. Leave empty to use "Create an account".',
                max_length=100,
                null=True,
                verbose_name='Account invitation title',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='pledge_marketing_consent_label',
            field=models.CharField(
                blank=True,
                help_text='Label of an optional checkbox for agreeing to receive updates from the plan. Leave empty to not ask for marketing consent.',
                max_length=300,
                null=True,
                verbose_name='Marketing consent label',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='pledge_privacy_url',
            field=models.URLField(
                blank=True,
                help_text='Linked next to the terms of use when people create an account.',
                null=True,
                verbose_name='Link to privacy notice for pledge accounts',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='pledge_terms_url',
            field=models.URLField(
                blank=True,
                help_text='People must accept these terms when they create an account. Required before accounts can be offered.',
                null=True,
                verbose_name='Link to terms of use for pledge accounts',
            ),
        ),
        migrations.AlterField(
            model_name='plan',
            name='i18n',
            field=modeltrans.fields.TranslationField(
                fields=[
                    'name',
                    'short_name',
                    'access_request_eligibility_text',
                    'pledge_account_title',
                    'pledge_account_description',
                    'pledge_marketing_consent_label',
                ],
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
