# Generated by Django 5.2 on 2026-01-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0157_alter_plandomain_redirect_aliases"),
        ("documentation", "0002_documentationpage_css_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentationrootpage",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentation_root_pages",
                to="actions.plan",
            ),
        ),
    ]
