# Generated by Django 2.1.3 on 2018-11-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('time_resolution', models.CharField(choices=[('year', 'year')], default='year', max_length=50, verbose_name='time resolution')),
                ('categories', models.ManyToManyField(blank=True, to='actions.Category')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='actions.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('begins_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='indicators.Indicator', verbose_name='indicator')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='actions.Scenario', verbose_name='scenario')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='verbose name')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.Unit', verbose_name='unit'),
        ),
    ]
