# Generated by Django 2.1.3 on 2018-11-14 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import indicators.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('time_resolution', models.CharField(choices=[('year', 'year')], default='year', max_length=50, verbose_name='time resolution')),
                ('categories', models.ManyToManyField(blank=True, to='actions.Category')),
                ('plan', models.ForeignKey(default=indicators.models.latest_plan, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='actions.Plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'indicator',
                'verbose_name_plural': 'indicators',
            },
        ),
        migrations.CreateModel(
            name='IndicatorEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_low', models.FloatField(verbose_name='low estimate')),
                ('result_high', models.FloatField(verbose_name='high estimate')),
                ('begins_at', models.DateField(verbose_name='begins at')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='ends at')),
                ('rationale', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='indicators.Indicator', verbose_name='indicator')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='actions.Scenario', verbose_name='scenario')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'indicator estimate',
                'verbose_name_plural': 'indicator estimates',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='verbose name')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.Unit', verbose_name='unit'),
        ),
    ]
