# Generated by Django 3.1.5 on 2021-09-28 21:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('actions', '0001_initial'),
        ('indicators', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorcontactperson',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='person'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='categories',
            field=models.ManyToManyField(blank=True, to='actions.Category'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='common',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='indicators.commonindicator', verbose_name='common indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='contact_persons_unordered',
            field=models.ManyToManyField(blank=True, related_name='contact_for_indicators', through='indicators.IndicatorContactPerson', to='people.Person', verbose_name='contact persons'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='indicators.Dataset', verbose_name='datasets'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='latest_graph',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.indicatorgraph'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='latest_value',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.indicatorvalue'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='indicators', through='indicators.IndicatorLevel', to='actions.Plan', verbose_name='plans'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='quantity',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.quantity', verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.unit', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='frameworkindicator',
            name='common_indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='indicators.commonindicator', verbose_name='common indicator'),
        ),
        migrations.AddField(
            model_name='frameworkindicator',
            name='framework',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_indicators', to='indicators.framework', verbose_name='framework'),
        ),
        migrations.AddField(
            model_name='dimensioncategory',
            name='dimension',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='indicators.dimension'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.datasetlicense', verbose_name='license'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.organization', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='commonindicator',
            name='quantity',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_indicators', to='indicators.quantity', verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='commonindicator',
            name='unit',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_indicators', to='indicators.unit', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='actionindicator',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_indicators', to='actions.action', verbose_name='action'),
        ),
        migrations.AddField(
            model_name='actionindicator',
            name='indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_actions', to='indicators.indicator', verbose_name='indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedindicator',
            unique_together={('causal_indicator', 'effect_indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatorlevel',
            unique_together={('indicator', 'plan')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatorgoal',
            unique_together={('indicator', 'plan', 'scenario', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatordimension',
            unique_together={('indicator', 'dimension')},
        ),
        migrations.AlterIndexTogether(
            name='indicatordimension',
            index_together={('indicator', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatorcontactperson',
            unique_together={('indicator', 'person')},
        ),
        migrations.AlterIndexTogether(
            name='indicatorcontactperson',
            index_together={('indicator', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='actionindicator',
            unique_together={('action', 'indicator')},
        ),
    ]
