# Generated by Django 2.1.3 on 2018-12-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_add_fields_and_indicator_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('increases', 'increases'), ('decreases', 'decreases')], help_text='What type of causal effect is there between the indicators', max_length=40, verbose_name='effect type')),
                ('confidence_level', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], help_text='How confident we are that the causal effect is present', max_length=20, verbose_name='confidence level')),
            ],
            options={
                'verbose_name': 'related indicator',
                'verbose_name_plural': 'related indicators',
            },
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.CharField(blank=True, choices=[('strategic', 'strategic'), ('tactical', 'tactical'), ('operational', 'operational')], max_length=30, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='relatedindicator',
            name='causal_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_effects', to='indicators.Indicator', verbose_name='causal indicator'),
        ),
        migrations.AddField(
            model_name='relatedindicator',
            name='effect_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_causes', to='indicators.Indicator', verbose_name='effect indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedindicator',
            unique_together={('causal_indicator', 'effect_indicator')},
        ),
    ]
