# Generated by Django 2.1.3 on 2019-01-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_add_a_part_of_as_effect_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
