# Generated by Django 3.2.12 on 2022-04-20 08:59

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name', 'short_name', 'verbose_name', 'verbose_name_plural'], required_languages=(), virtual_fields=True),
        ),
    ]
