# Generated by Django 2.1.3 on 2019-01-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_add_action_updated_at'),
        ('indicators', '0006_add_indicator_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('increases', 'increases'), ('decreases', 'decreases'), ('part_of', 'is a part of')], help_text='What type of effect should the action cause?', max_length=40, verbose_name='effect type')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_indicators', to='actions.Action', verbose_name='action')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_actions', to='indicators.Indicator', verbose_name='indicator')),
            ],
            options={
                'verbose_name': 'action indicator',
                'verbose_name_plural': 'action indicators',
            },
        ),
        migrations.AlterUniqueTogether(
            name='actionindicator',
            unique_together={('action', 'indicator')},
        ),
    ]
