# Generated by Django 2.1.5 on 2019-02-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_fix_perm_typo'),
        ('indicators', '0007_add_action_indicator_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('strategic', 'strategic'), ('tactical', 'tactical'), ('operational', 'operational')], max_length=30, verbose_name='level')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='indicators.Indicator', verbose_name='indicator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_levels', to='actions.Plan', verbose_name='plan')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='plans',
            field=models.ManyToManyField(blank=True, through='indicators.IndicatorLevel', to='actions.Plan', verbose_name='plans'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorlevel',
            unique_together={('indicator', 'plan')},
        ),
    ]
