# Generated by Django 2.2 on 2019-04-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_add_indicator_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(verbose_name='time')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.Indicator', verbose_name='indicator')),
            ],
            options={
                'verbose_name': 'indicator value',
                'verbose_name_plural': 'indicator values',
                'ordering': ('indicator', 'time'),
                'get_latest_by': 'time',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='latest_value',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.IndicatorValue'),
        ),
    ]
