# Generated by Django 2.2 on 2019-04-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_alter_fields'),
        ('indicators', '0012_add_indicator_value_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together={('indicator', 'time')},
        ),
        migrations.CreateModel(
            name='IndicatorGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField(verbose_name='date')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='indicators.Indicator', verbose_name='indicator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_goals', to='actions.Plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'indicator goal',
                'verbose_name_plural': 'indicator goals',
                'ordering': ('indicator', 'date'),
                'get_latest_by': 'date',
                'unique_together': {('indicator', 'plan', 'date')},
            },
        ),
    ]
