# Generated by Django 2.2.4 on 2019-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_add_indicator_goal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='value',
            field=models.FloatField(verbose_name='value'),
        ),
    ]
