# Generated by Django 3.2.13 on 2022-09-07 14:39

from django.db import migrations


def migrate_indicatorgoal_plan(apps, schema_editor):
    IndicatorGoal = apps.get_model('indicators', 'IndicatorGoal')
    for goal in IndicatorGoal.objects.all():
        goal.plan = None
        goal.save()


def migrate_indicatorgoal_plan_reverse(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    for indicator in Indicator.objects.filter(goals__isnull=False):
        plan = indicator.plans.first()
        for goal in indicator.goals.all():
            goal.plan = plan
            goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_alter_indicatorgoal_plan'),
    ]

    operations = [
        migrations.RunPython(migrate_indicatorgoal_plan, migrate_indicatorgoal_plan_reverse)
    ]
