# Generated by Django 2.2.4 on 2019-09-20 14:38

from django.db import migrations
import pytz

LOCAL_TZ = pytz.timezone('Europe/Helsinki')


def migrate_indicator_values(apps, schema_editor):
    IndicatorValue = apps.get_model('indicators', 'IndicatorValue')
    for val in IndicatorValue.objects.all().select_related('indicator'):
        val.date = val.time.astimezone(LOCAL_TZ).date()
        ind = val.indicator
        if ind.time_resolution == 'year':
            val.date = val.date.replace(month=12, day=31)
        val.save(update_fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_add_indicatorvalue_date'),
    ]

    operations = [
        migrations.RunPython(migrate_indicator_values),
    ]
