# Generated by Django 2.2.4 on 2019-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_migrate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorvalue',
            options={'get_latest_by': 'date', 'ordering': ('indicator', 'date'), 'verbose_name': 'indicator value', 'verbose_name_plural': 'indicator values'},
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together={('indicator', 'date')},
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='time',
        ),
    ]
