# Generated by Django 3.2.13 on 2022-09-15 15:11

from django.db import migrations, models


def migrate_week_resolution(apps, schema_editor):
    # Change week resolution to day resolution.  Note, the week
    # resolution isn't currently used in production, this is just to
    # make sure migration result is valid in all environments.
    Indicator = apps.get_model('indicators', 'Indicator')
    for indicator in Indicator.objects.filter(time_resolution='week'):
        indicator.time_resolution = 'day'
        indicator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_remove_plan_and_scenario_from_indicatorgoal'),
    ]

    operations = [
        migrations.RunPython(migrate_week_resolution),
        migrations.AlterField(
            model_name='indicator',
            name='time_resolution',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day')], default='year', max_length=50, verbose_name='time resolution'),
        ),
    ]
