# Generated by Django 2.2.4 on 2019-09-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_remove_indicatorvalue_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'quantity',
                'verbose_name_plural': 'quantities',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.Unit', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.Quantity', verbose_name='quantity'),
        ),
    ]
