# Generated by Django 2.2.4 on 2019-10-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_add_person_title'),
        ('indicators', '0017_add_quantity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='indicators.Indicator', verbose_name='indicator')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'indicator contact person',
                'verbose_name_plural': 'indicator contact persons',
                'ordering': ['indicator', 'order'],
                'unique_together': {('indicator', 'person')},
                'index_together': {('indicator', 'order')},
            },
        ),
    ]
