# Generated by Django 2.2.4 on 2019-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_add_indicator_contact_person_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='verbose_name_plural',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='verbose name plural'),
        ),
    ]
