# Generated by Django 2.2.4 on 2019-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0019_add_more_unit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionindicator',
            name='indicates_action_progress',
            field=models.BooleanField(default=False, help_text='Set if the indicator should be used to determine action progress', verbose_name='indicates action progress'),
        ),
    ]
