# Generated by Django 3.2.16 on 2023-11-30 13:12

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_indicatorgoal_normalized_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonindicator',
            name='identifier',
            field=aplans.utils.IdentifierField(blank=True, max_length=70, null=True, validators=[aplans.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='indicatorgraph',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='relatedindicator',
            name='causal_indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_effects', to='indicators.indicator', verbose_name='causal indicator'),
        ),
        migrations.AlterField(
            model_name='relatedindicator',
            name='effect_indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_causes', to='indicators.indicator', verbose_name='effect indicator'),
        ),
    ]
