# Generated by Django 3.0.6 on 2020-06-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0047_add_root_collection_to_plan'),
        ('indicators', '0021_add_dataset_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'dataset', 'verbose_name_plural': 'datasets'},
        ),
        migrations.AlterModelOptions(
            name='datasetlicense',
            options={'verbose_name': 'dataset license', 'verbose_name_plural': 'dataset licenses'},
        ),
        migrations.AddField(
            model_name='indicatorgoal',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_goals', to='actions.Scenario', verbose_name='scenario'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorgoal',
            unique_together={('indicator', 'plan', 'scenario', 'date')},
        ),
    ]
