# Generated by Django 3.1 on 2020-08-20 07:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0022_add_scenario_to_indicator_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='quantity',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.quantity', verbose_name='quantity'),
        ),
    ]
