# Generated by Django 3.0.6 on 2020-05-18 13:43

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0022_add_indicator_dimensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'ordering': ('id',), 'verbose_name': 'quantity', 'verbose_name_plural': 'quantities'},
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='name',
            new_name='name_old',
        ),
        migrations.CreateModel(
            name='QuantityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.Quantity')),
            ],
            options={
                'verbose_name': 'quantity Translation',
                'db_table': 'indicators_quantity_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
