# Generated by Django 3.2.16 on 2024-04-02 12:11

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_remove_fk_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='internal notes'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reference',
            field=wagtail.fields.RichTextField(blank=True, help_text='What is the reference or source for this indicator?', max_length=255, null=True, verbose_name='reference'),
        ),
    ]
