# Generated by Django 3.0.6 on 2020-05-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_migrate_quantity_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='name_old',
        ),
    ]
