# Generated by Django 3.2.16 on 2024-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_reference_and_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='public', max_length=20, verbose_name='visibility'),
        ),
    ]
