# Generated by Django 3.1 on 2020-08-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_add_common_indicators_and_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='values', to='indicators.DimensionCategory', verbose_name='categories'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together=set(),
        ),
    ]
