# Generated by Django 5.0.6 on 2024-09-02 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_indicator_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionindicator',
            options={'ordering': ['indicator'], 'verbose_name': 'action indicator', 'verbose_name_plural': 'action indicators'},
        ),
        migrations.RenameIndex(
            model_name='commonindicatordimension',
            new_name='indicators__common__d5cb42_idx',
            old_fields=('common_indicator', 'order'),
        ),
        migrations.RenameIndex(
            model_name='indicatorcontactperson',
            new_name='indicators__indicat_b3fff3_idx',
            old_fields=('indicator', 'order'),
        ),
        migrations.RenameIndex(
            model_name='indicatordimension',
            new_name='indicators__indicat_3352ea_idx',
            old_fields=('indicator', 'order'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
