# Generated by Django 3.1 on 2020-10-19 08:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0059_manual_status_override_for_action'),
        ('people', '0008_add_participated_in_training_flag'),
        ('indicators', '0025_bind_indicator_values_to_dimension_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'verbose_name': 'dimension', 'verbose_name_plural': 'dimensions'},
        ),
        migrations.AlterModelOptions(
            name='dimensioncategory',
            options={'ordering': ['dimension', 'order'], 'verbose_name': 'dimension category', 'verbose_name_plural': 'dimension categories'},
        ),
        migrations.AlterModelOptions(
            name='indicatordimension',
            options={'ordering': ['indicator', 'order'], 'verbose_name': 'indicator dimension', 'verbose_name_plural': 'indicator dimensions'},
        ),
        migrations.AddField(
            model_name='indicator',
            name='contact_persons_unordered',
            field=models.ManyToManyField(blank=True, related_name='contact_for_indicators', through='indicators.IndicatorContactPerson', to='people.Person', verbose_name='contact persons'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='max_value',
            field=models.FloatField(help_text='What is the maximum value this indicator can reach? It is used in visualizations as the Y axis maximum.', null=True, verbose_name='maximum value'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='min_value',
            field=models.FloatField(help_text='What is the minimum value this indicator can reach? It is used in visualizations as the Y axis minimum.', null=True, verbose_name='minimum value'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='indicators', through='indicators.IndicatorLevel', to='actions.Plan', verbose_name='plans'),
        ),
        migrations.AlterField(
            model_name='indicatorcontactperson',
            name='indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='indicators.indicator', verbose_name='indicator'),
        ),
        migrations.AlterField(
            model_name='indicatorcontactperson',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator', verbose_name='indicator'),
        ),
    ]
