# Generated by Django 5.0.6 on 2024-09-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0027_indicator_show_trendline'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='desired_trend',
            field=models.CharField(blank=True, choices=[('increasing', 'increasing'), ('decreasing', 'decreasing'), ('', 'attempt to detect automatically')], default='', help_text="Which trend in the numerical values of this indicator's goals indicates improvement: when the values are increasing or decreasing?", max_length=20, verbose_name='desired trend'),
        ),
    ]
