# Generated by Django 5.0.6 on 2024-11-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0134_create_equivalent_through_models"),
        ("indicators", "0028_indicator_desired_trend"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name="IndicatorCategoryThrough",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "category",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="actions.category",
                        ),
                    ),
                    (
                        "indicator",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="indicator_category_through",
                            to="indicators.indicator",
                        ),
                    ),
                ],
                options={
                    "db_table": "indicators_indicator_categories",
                    "unique_together": {("indicator", "category")},
                },
            ),
            migrations.AlterField(
                model_name="indicator",
                name="categories",
                field=models.ManyToManyField(
                    blank=True,
                    related_name="indicators",
                    through="indicators.IndicatorCategoryThrough",
                    to="actions.category",
                ),
            ),
        ]),
    ]
