# Generated by Django 3.1.5 on 2021-09-21 15:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0084_new_organization_models'),
        ('orgs', '0002_wagtail_editing'),
        ('indicators', '0028_add_updated_values_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='owner_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.organization', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='organization_new',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='actionindicator',
            name='action',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_indicators', to='actions.action', verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='actionindicator',
            name='indicator',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_actions', to='indicators.indicator', verbose_name='indicator'),
        ),
    ]
