# Generated by Django 5.0.6 on 2024-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0029_create_equivalent_through_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='show_total_line',
            field=models.BooleanField(default=True, verbose_name='show total line'),
        ),
    ]
