# Generated by Django 3.1.5 on 2021-09-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_wagtail_editing'),
        ('indicators', '0029_new_organization_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='owner',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='owner_new',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.organization', verbose_name='owner'),
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='organization',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='orgs.organization', verbose_name='organization'),
        ),
    ]
