# Generated by Django 5.2 on 2025-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0030_indicator_show_total_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='data_categories_are_stackable',
            field=models.BooleanField(default=False, help_text='Data categories can be summed to form a total for the indicator (draw a stacked chart as default)'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ticks_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of steps on the y-axis', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ticks_rounding',
            field=models.PositiveIntegerField(blank=True, help_text='Number of significant digits on y-axis ticks', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='value_rounding',
            field=models.PositiveIntegerField(blank=True, help_text='Number of significant digits when displaying indicator values', null=True),
        ),
        migrations.AlterField(
            model_name='commonindicator',
            name='normalization_indicators',
            field=models.ManyToManyField(blank=True, related_name='normalizable_indicators', through='indicators.CommonIndicatorNormalizator', through_fields=('normalizable', 'normalizer'), to='indicators.commonindicator'),
        ),
    ]
