# Generated by Django 5.2 on 2025-11-24 15:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0148_alter_indicatorcategoryrelationship_category"),
        ("indicators", "0036_indicator_reference_value_and_more"),
        ("orgs", "0028_datamigration_organization_abbreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="indicators",
                through="indicators.IndicatorCategoryThrough",
                to="actions.category",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="organization",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="orgs.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorgoal",
            name="indicator",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="indicators.indicator",
                verbose_name="indicator",
            ),
        ),
    ]
