# Generated by Django 5.2 on 2025-11-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0148_alter_indicatorcategoryrelationship_category"),
        ("indicators", "0038_indicator_non_quantified_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="kausal_paths_node_uuid",
            field=models.CharField(
                blank=True,
                help_text="The node identifier of the node in Paths where this indicator's data is imported from.",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Node identifier",
            ),
        ),
        migrations.AlterField(
            model_name="indicatorcategorythrough",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicator_category_through",
                to="actions.category",
            ),
        ),
        migrations.CreateModel(
            name="IndicatorValuesImportLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[("kausal_paths", "Kausal Paths")], max_length=50
                    ),
                ),
                ("source_url", models.URLField()),
                ("import_parameters", models.JSONField(blank=True, default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values_import_logs",
                        to="indicators.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator values import log",
                "verbose_name_plural": "Indicator values import logs",
                "ordering": ["imported_at"],
            },
        ),
    ]
