# Generated by Django 5.2 on 2026-02-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0156_make_plan_non_nullable_in_changelogmessages"),
        ("indicators", "0043_indicatorgoal_latest_revision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancommonindicator",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_common_indicator_through",
                to="actions.plan",
            ),
        ),
        # Use SeparateDatabaseAndState because the table 'indicators_indicatorvalue_categories'
        # already exists (it was auto-generated by Django for the ManyToManyField).
        # We only need Django to update its internal state to recognize the explicit through model.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="IndicatorValueCategory",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "dimension_category",
                            models.ForeignKey(
                                db_column="dimensioncategory_id",
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="indicator_value_links",
                                to="indicators.dimensioncategory",
                            ),
                        ),
                        (
                            "indicator_value",
                            models.ForeignKey(
                                db_column="indicatorvalue_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="category_links",
                                to="indicators.indicatorvalue",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "indicator value category",
                        "verbose_name_plural": "indicator value categories",
                        "db_table": "indicators_indicatorvalue_categories",
                        "ordering": (
                            "indicator_value",
                            "dimension_category__dimension",
                            "dimension_category__order",
                        ),
                        "unique_together": {("indicator_value", "dimension_category")},
                    },
                ),
                migrations.AlterField(
                    model_name="indicatorvalue",
                    name="categories",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="values",
                        through="indicators.IndicatorValueCategory",
                        to="indicators.dimensioncategory",
                        verbose_name="categories",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
