# Generated by Django 5.2 on 2026-02-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0045_indicator_hide_indicator_graph_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicator",
            name="visualizations",
        ),
        migrations.AlterField(
            model_name="indicator",
            name="hide_indicator_graph",
            field=models.BooleanField(
                default=False,
                help_text="Do not show the graph for this indicator on the indicator's own page.",
                verbose_name="Hide graph",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="hide_indicator_table",
            field=models.BooleanField(
                default=False,
                help_text="Do not show this indicator's values in a table on the indicator's own page.",
                verbose_name="Hide table",
            ),
        ),
    ]
