# Generated by Django 6.0.2 on 2026-03-09 14:24

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0021_datapointcomment_is_soft_deleted_and_more"),
        ("indicators", "0048_add_dataset_metric_computation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorGoalDataPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last modified at"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of this data point in context of the dataset's time resolution",
                        verbose_name="date",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=16,
                        max_digits=32,
                        null=True,
                        verbose_name="value",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_data_points",
                        to="datasets.dataset",
                        verbose_name="dataset",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="datasets.datasetmetric",
                        verbose_name="metric",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicator goal data point",
                "verbose_name_plural": "indicator goal data points",
                "ordering": ("date", "id"),
            },
        ),
        migrations.CreateModel(
            name="IndicatorGoalDimensionCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="datasets.dimensioncategory",
                    ),
                ),
                (
                    "goal_data_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension_category_links",
                        to="indicators.indicatorgoaldatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicator goal dimension category",
                "verbose_name_plural": "indicator goal dimension categories",
                "unique_together": {("goal_data_point", "dimension_category")},
            },
        ),
        migrations.AddField(
            model_name="indicatorgoaldatapoint",
            name="dimension_categories",
            field=models.ManyToManyField(
                blank=True,
                through="indicators.IndicatorGoalDimensionCategory",
                to="datasets.dimensioncategory",
                verbose_name="dimension categories",
            ),
        ),
    ]
