# Generated by Django 6.0.2 on 2026-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0051_alter_indicator_bar_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorlevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("strategic", "strategic"),
                    ("tactical", "tactical"),
                    ("operational", "operational"),
                    ("unspecified", "unspecified"),
                ],
                default="unspecified",
                max_length=30,
                verbose_name="level",
            ),
        ),
    ]
