# Generated by ariadne-codegen
# Source: paths_integration/queries.graphql

from typing import List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class NodeValues(BaseModel):
    instance: "NodeValuesInstance"
    node: Optional["NodeValuesNode"]


class NodeValuesInstance(BaseModel):
    id: str
    name: str


class NodeValuesNode(BaseModel):
    typename__: Literal["ActionNode", "Node", "NodeInterface"] = Field(
        alias="__typename"
    )
    id: str
    name: str
    metric_dim: Optional["NodeValuesNodeMetricDim"] = Field(alias="metricDim")


class NodeValuesNodeMetricDim(BaseModel):
    id: str
    unit: "NodeValuesNodeMetricDimUnit"
    dimensions: List["NodeValuesNodeMetricDimDimensions"]
    years: List[int]
    values: List[float]
    forecast_from: Optional[int] = Field(alias="forecastFrom")


class NodeValuesNodeMetricDimUnit(BaseModel):
    short: str


class NodeValuesNodeMetricDimDimensions(BaseModel):
    id: str
    label: str
    categories: List["NodeValuesNodeMetricDimDimensionsCategories"]


class NodeValuesNodeMetricDimDimensionsCategories(BaseModel):
    id: str
    label: str


NodeValues.model_rebuild()
NodeValuesNode.model_rebuild()
NodeValuesNodeMetricDim.model_rebuild()
NodeValuesNodeMetricDimDimensions.model_rebuild()
