# Generated by Django 3.1.5 on 2021-09-28 21:37

import aplans.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('hostname', aplans.fields.HostnameField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('client', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('azure_ad_tenant_id', models.CharField(max_length=200)),
                ('login_header_text', models.CharField(max_length=200, verbose_name='login header text')),
                ('login_button_text', models.CharField(max_length=200, verbose_name='login button text')),
                ('i18n', modeltrans.fields.TranslationField(fields=['login_header_text', 'login_button_text'], required_languages=(), virtual_fields=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('domain', aplans.fields.HostnameField(max_length=254, unique=True)),
                ('client', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='admin_site.client')),
            ],
            options={
                'ordering': ('client', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='admin_site.client')),
                ('plan', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='actions.plan')),
            ],
        ),
    ]
