# Generated by Django 3.2.13 on 2023-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_add_client_use_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='google_login_enabled',
            field=models.BooleanField(default=False, verbose_name='Google login enabled'),
        ),
        migrations.AddField(
            model_name='client',
            name='google_login_button_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='login button text for google'),
        ),
    ]
