# Generated by Django 3.2.16 on 2024-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_built_in_field_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('', 'Only allow password login'), ('azure_ad', 'Microsoft Azure AD'), ('google-openidconnect', 'Google'), ('tunnistamo', 'Tunnistamo'), ('okta-openidconnect', 'OKTA'), ('adfs-openidconnect', 'ADFS OpenID Connect')], help_text="Login method that will be used for users that don't have a password set", max_length=30, verbose_name='login method'),
        ),
    ]
