# Generated by Django 6.1 on 2026-08-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0017_builtinfieldcustomization_latest_revision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builtinfieldcustomization',
            options={'ordering': ('content_type', 'field_name'), 'verbose_name': 'field customization', 'verbose_name_plural': 'field customizations'},
        ),
    ]
