from __future__ import annotations

from django.db.models.fields import Field
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.db.models.fields.reverse_related import ManyToOneRel

import pytest

from actions.action_fields import action_registry
from actions.models import Action

pytestmark = pytest.mark.django_db


def get_field_type(field):
    if isinstance(field, ForeignKey):
        return 'single'
    if isinstance(field, ManyToOneRel):
        return 'many'
    if isinstance(field, ManyToManyField):
        return 'many'
    if isinstance(field, Field):
        return 'primitive'
    raise TypeError('Unknown field', field)


def test_action_field_registry_validity():
    """
    Test that the action field register is consistent with the action model.

    The Wagtail Blocks cannot be generated by dynamic model
    introspection because the blocks are used in a context
    where the Django application registry is not fully initialized.

    Instead, we make sure the manually configured block fields
    in actions.action_fields make sense.

    We also raise warnings for any missing blocks.

    """

    public_fields = Action.public_fields
    for field in Action._meta.get_fields():
        if field.name not in public_fields:
            # Blocks for non-public fields are not allowed
            with pytest.raises(KeyError):
                action_registry[field.name]
            continue

        default_field_type = get_field_type(field)
        field_props = action_registry[field.name]
        if field_props.is_disabled():
            continue
        assert \
            field_props.field_type in ('custom', default_field_type), \
            f'Wrong type for field {field.name}'


# def test_disabled_fields_raise_for_blocks
