from __future__ import annotations

import warnings

from django.db.models.fields import Field
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.db.models.fields.reverse_related import ManyToOneRel

import pytest

from actions.action_fields import action_registry
from actions.models import Action


def get_field_type(field):
    if field.many_to_one or field.one_to_one:
        return 'single'
    if field.one_to_many or field.many_to_many:
        return 'many'
    if isinstance(field, Field):
        return 'primitive'
    raise TypeError('Unknown field', field)


@pytest.mark.parametrize('field', Action._meta.get_fields())
def test_action_field_registry_validity(field):
    """
    Test that the action field register is consistent with the action model.

    The Wagtail Blocks cannot be generated by dynamic model
    introspection because in Wagtail, the blocks are used in a context
    where the Django application registry is not fully initialized.

    Instead, we use introspection here to make sure the manually
    configured block fields in actions.action_fields make sense.

    We also raise errors for any missing blocks.

    Because reporting is used for Action dashboard CSV/Excel
    export, a warning is raised if a corresponding
    reporting block is not found for a dashboard block.

    """

    public_fields = Action.public_fields
    # for field in Action._meta.get_fields():
    if field.name not in public_fields:
        # Blocks for non-public fields are not allowed
        with pytest.raises(KeyError):
            action_registry[field.name]
        return

    try:
        field_props = action_registry[field.name]
    except KeyError:
        msg = (f'No blocks configured for public field "{field.name}" of Action. '
               'Please configure or disable blocks for that field in actions.action_fields.py')
        warnings.warn(msg, stacklevel=1)  # TODO: make this a test failure

    default_field_type = get_field_type(field)
    if field_props.is_disabled():
        return
    assert field_props.field_type in ('custom', default_field_type), (
        f'Wrong type for field {field.name}'
    )

    config = field_props.config
    assert config
    if config['dashboard'].has_block and not config['report'].has_block:
        msg = (f'No report block configured for public field "{field.name}" of Action '
               'even though a dashboard block exists for it.')
        warnings.warn(msg, stacklevel=1)  # TODO: make this a test failure
    return
