# Generated by Django 5.2 on 2025-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_aplansrendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplansimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
    ]
