# Generated by Django 3.1.13 on 2021-11-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationAdmin',
        ),
    ]
