# Generated by Django 3.2.13 on 2022-08-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_create_plan_link_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planlink',
            options={'ordering': ['plan', 'order'], 'verbose_name': 'external plan link', 'verbose_name_plural': 'external plan links'},
        ),
    ]
