# Generated by Django 3.2.13 on 2022-12-11 23:49

from django.db import migrations


def fill_maintenance_responsibility_paragraph(apps, schema_editor):
    AccessibilityStatementPage = apps.get_model('pages', 'AccessibilityStatementPage')
    for page in AccessibilityStatementPage.objects.all():
        for block in page.body.raw_data:
            if (block.get('type') == 'contact_information'
                    and 'maintenance_responsibility_paragraph' not in block['value']):
                block['value']['maintenance_responsibility_paragraph'] = ''
                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_children_use_secondary_navigation'),
    ]

    operations = [
        migrations.RunPython(fill_maintenance_responsibility_paragraph),
    ]
