# Generated by Django 3.2.16 on 2023-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_category_page_icon_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlistpage',
            name='display_insights',
            field=models.BooleanField(default=True, help_text='Should insight network be shown for indicators', verbose_name='Display insights'),
        ),
    ]
