# Generated by Django 3.2.16 on 2023-10-04 07:12

from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation


def delete_action_list_page_revisions(apps, schema_editor):
    # These page revisions have not been migrated in the past,
    # hence they are incompatible with this migration
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ActionListPage = apps.get_model('pages', 'ActionListPage')
    Revision = apps.get_model('wagtailcore', 'Revision')
    page_ct = ContentType.objects.get_for_model(ActionListPage)
    Revision.objects.filter(content_type=page_ct).delete()


class TransformResponsibleParties(BaseBlockOperation):
    def apply(self, block_value):
        if block_value is None:
            return {'heading': ''}
        return block_value

    @property
    def operation_name_fragment(self):
        return "make_responsible_party_block_value_valid"


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_indicatorlistpage_display_insights'),
    ]

    operations = [
        migrations.RunPython(delete_action_list_page_revisions, migrations.RunPython.noop),
        MigrateStreamData(
            app_name="pages",
            model_name="ActionListPage",
            field_name="details_aside",
            operations_and_block_paths=[
                (TransformResponsibleParties(), "responsible_parties")
            ]
        )
    ]
