# Generated by Django 3.2.16 on 2024-02-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0110_remove_fk_protection'),
        ('pages', '0029_add_actionlistpage_date_format_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pages', to='actions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categorytypepage',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type_pages', to='actions.categorytype', verbose_name='Category type'),
        ),
    ]
