# Generated by Django 3.2.16 on 2024-03-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_fk_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilitystatementpage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='actionlistpage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='categorypage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='emptypage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='impactgrouppage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='indicatorlistpage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='planrootpage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='link_in_all_child_plans',
            field=models.BooleanField(default=False, help_text='Should this additional link be displayed in child plans?', verbose_name='show link in child plans'),
        ),
    ]
