# Generated by Django 5.0.6 on 2024-10-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_actionlistpage_details_main_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlistpage',
            name='display_level',
            field=models.BooleanField(default=True, help_text='Should the indicator level be shown for indicators? (Displayed in the column "Type")', verbose_name='Display level'),
        ),
    ]
