# Generated by Django 5.0.6 on 2024-11-13 16:29

import actions.blocks.action_content_blocks
import actions.blocks.choosers
import reports.blocks.choosers
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0040_indicatorlistpage_include_related_plans_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlistpage",
            name="dashboard_columns",
            field=wagtail.fields.StreamField(
                [
                    (
                        "identifier",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "name",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "imact",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "implementation_phase",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "status",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "tasks",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "responsible_parties",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "updated_at",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "start_date",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "end_date",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "field",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribute_type",
                                    actions.blocks.choosers.ActionAttributeTypeChooserBlock(),
                                ),
                            ]
                        ),
                    ),
                    (
                        "indicators",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "organization",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_aside",
            field=wagtail.fields.StreamField(
                [
                    (
                        "schedule",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "contact_persons",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "responsible_parties",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "attribute",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "attribute_type",
                                    actions.blocks.choosers.ActionAttributeTypeChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "categories",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "category_type",
                                    actions.blocks.choosers.CategoryTypeChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_main_bottom",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("full-width", "Full width"),
                                            ("grid", "Grid"),
                                        ]
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        form_classname="full title",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.blocks.CharBlock(
                                        label="Help text", required=False
                                    ),
                                ),
                                (
                                    "blocks",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "attribute",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "attribute_type",
                                                            actions.blocks.choosers.ActionAttributeTypeChooserBlock(
                                                                required=True
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "categories",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "category_type",
                                                            actions.blocks.choosers.CategoryTypeChooserBlock(
                                                                required=True
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ],
                                        label="Blocks",
                                    ),
                                ),
                            ],
                            required=True,
                        ),
                    ),
                    (
                        "contact_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="", label="Heading", required=False
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        default="", label="Description", required=False
                                    ),
                                ),
                                (
                                    "feedback_visible",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Toggle visibility of the feedback field.",
                                        label="Feedback field visible",
                                        required=False,
                                    ),
                                ),
                                (
                                    "feedback_required",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Make the feedback field required when visible.",
                                        label="Feedback required",
                                        required=False,
                                    ),
                                ),
                                (
                                    "email_visible",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Toggle visibility of the email field.",
                                        label="Email field visible",
                                        required=False,
                                    ),
                                ),
                                (
                                    "email_required",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Make the email field required when visible.",
                                        label="Email required",
                                        required=False,
                                    ),
                                ),
                                (
                                    "fields",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "form_field",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "field_label",
                                                            wagtail.blocks.CharBlock(
                                                                label="Field Label",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "field_type",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("text", "Text"),
                                                                    (
                                                                        "checkbox",
                                                                        "Checkbox",
                                                                    ),
                                                                    (
                                                                        "dropdown",
                                                                        "Dropdown",
                                                                    ),
                                                                ],
                                                                label="Field Type",
                                                            ),
                                                        ),
                                                        (
                                                            "field_required",
                                                            wagtail.blocks.BooleanBlock(
                                                                label="Required",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "choices",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "choice_field",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "choice_label",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        label="Label",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "choice_value",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        label="Value",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    )
                                                                ],
                                                                label="Choices",
                                                                min_num=0,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="Form fields to be shown in addition to Name, Email and Comment fields",
                                        label="Additional form fields",
                                        min_num=0,
                                        required=False,
                                    ),
                                ),
                            ],
                            required=True,
                        ),
                    ),
                    (
                        "report_comparison",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "report_type",
                                    reports.blocks.choosers.ReportTypeChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "report_field",
                                    reports.blocks.choosers.ReportTypeFieldChooserBlock(
                                        label="UUID of report field", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "indicator_causal_chain",
                        actions.blocks.action_content_blocks.IndicatorCausalChainBlock(),
                    ),
                    (
                        "datasets",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="What heading should be used in the public UI for the Dataset?",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the Dataset to be shown in the public UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                                (
                                    "dataset_schema",
                                    actions.blocks.choosers.PlanDatasetSchemaChooserBlock(
                                        required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "lead_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "description",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "official_name",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="What label should be used in the public UI for the official name?",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Description to show after the field content",
                                        label="Caption",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "attribute",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "attribute_type",
                                    actions.blocks.choosers.ActionAttributeTypeChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "categories",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "category_type",
                                    actions.blocks.choosers.CategoryTypeChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "tasks",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "merged_actions",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "related_actions",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "dependencies",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "related_indicators",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_main_top",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("full-width", "Full width"),
                                            ("grid", "Grid"),
                                        ]
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        form_classname="full title",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.blocks.CharBlock(
                                        label="Help text", required=False
                                    ),
                                ),
                                (
                                    "blocks",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "attribute",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "attribute_type",
                                                            actions.blocks.choosers.ActionAttributeTypeChooserBlock(
                                                                required=True
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "categories",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "category_type",
                                                            actions.blocks.choosers.CategoryTypeChooserBlock(
                                                                required=True
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ],
                                        label="Blocks",
                                    ),
                                ),
                            ],
                            required=True,
                        ),
                    ),
                    (
                        "contact_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="", label="Heading", required=False
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        default="", label="Description", required=False
                                    ),
                                ),
                                (
                                    "feedback_visible",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Toggle visibility of the feedback field.",
                                        label="Feedback field visible",
                                        required=False,
                                    ),
                                ),
                                (
                                    "feedback_required",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Make the feedback field required when visible.",
                                        label="Feedback required",
                                        required=False,
                                    ),
                                ),
                                (
                                    "email_visible",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Toggle visibility of the email field.",
                                        label="Email field visible",
                                        required=False,
                                    ),
                                ),
                                (
                                    "email_required",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Make the email field required when visible.",
                                        label="Email required",
                                        required=False,
                                    ),
                                ),
                                (
                                    "fields",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "form_field",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "field_label",
                                                            wagtail.blocks.CharBlock(
                                                                label="Field Label",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "field_type",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("text", "Text"),
                                                                    (
                                                                        "checkbox",
                                                                        "Checkbox",
                                                                    ),
                                                                    (
                                                                        "dropdown",
                                                                        "Dropdown",
                                                                    ),
                                                                ],
                                                                label="Field Type",
                                                            ),
                                                        ),
                                                        (
                                                            "field_required",
                                                            wagtail.blocks.BooleanBlock(
                                                                label="Required",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "choices",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "choice_field",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "choice_label",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        label="Label",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "choice_value",
                                                                                    wagtail.blocks.CharBlock(
                                                                                        label="Value",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    )
                                                                ],
                                                                label="Choices",
                                                                min_num=0,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="Form fields to be shown in addition to Name, Email and Comment fields",
                                        label="Additional form fields",
                                        min_num=0,
                                        required=False,
                                    ),
                                ),
                            ],
                            required=True,
                        ),
                    ),
                    (
                        "report_comparison",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "report_type",
                                    reports.blocks.choosers.ReportTypeChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "report_field",
                                    reports.blocks.choosers.ReportTypeFieldChooserBlock(
                                        label="UUID of report field", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "indicator_causal_chain",
                        actions.blocks.action_content_blocks.IndicatorCausalChainBlock(),
                    ),
                    (
                        "datasets",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="What heading should be used in the public UI for the Dataset?",
                                        label="Heading",
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the Dataset to be shown in the public UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                                (
                                    "dataset_schema",
                                    actions.blocks.choosers.PlanDatasetSchemaChooserBlock(
                                        required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "lead_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "description",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "official_name",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="What label should be used in the public UI for the official name?",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Description to show after the field content",
                                        label="Caption",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "attribute",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "attribute_type",
                                    actions.blocks.choosers.ActionAttributeTypeChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "categories",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "category_type",
                                    actions.blocks.choosers.CategoryTypeChooserBlock(
                                        required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "tasks",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "merged_actions",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "related_actions",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "dependencies",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "related_indicators",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "field_label",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Heading to show instead of the default",
                                        label="Field label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "field_help_text",
                                    wagtail.blocks.CharBlock(
                                        default="",
                                        help_text="Help text for the field to be shown in the UI",
                                        label="Help text",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
