# Generated by Django 5.0.6 on 2024-12-01 13:29

import actions.blocks.choosers
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0042_alter_actionlistpage_details_main_bottom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlistpage",
            name="dashboard_columns",
            field=wagtail.fields.StreamField(
                [
                    (
                        "identifier",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "name",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "impact",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "implementation_phase",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "status",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "tasks",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "responsible_parties",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "updated_at",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "start_date",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "end_date",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "attribute",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                ),
                                (
                                    "attribute_type",
                                    actions.blocks.choosers.ActionAttributeTypeChooserBlock(),
                                ),
                            ]
                        ),
                    ),
                    (
                        "related_indicators",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "primary_org",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Label for the column to be used instead of the default",
                                        label="Label",
                                        required=False,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
