# Generated by Django 5.2 on 2025-12-22 16:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0048_indicatorlistpage_advanced_filters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("qa_section", 6),
                    ("indicator_group", 12),
                    ("related_indicators", 13),
                    ("category_list", 19),
                    ("action_list", 24),
                    ("embed", 29),
                    ("raw_visualization", 30),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 8), ("style", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("indicators", 11)]],
                        {},
                    ),
                    13: ("indicators.blocks.RelatedIndicatorsBlock", (), {}),
                    14: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 14),
                                ("category", 15),
                                ("heading", 16),
                                ("lead", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Action list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Action list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    22: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"label": "Filter on category"},
                    ),
                    23: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 20),
                                ("help_text", 21),
                                ("category_filter", 22),
                                ("group_by_category_level", 23),
                            ]
                        ],
                        {},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 25), ("height", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 27), ("full_width", 28)]],
                        {},
                    ),
                    30: ("pages.blocks.RawVisualizationBlock", (), {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indicatorlistpage",
            name="details_aside",
            field=wagtail.fields.StreamField(
                [
                    ("category", 3),
                    ("value_summary", 10),
                    ("name", 11),
                    ("description", 12),
                    ("organization", 13),
                    ("updated_at", 14),
                    ("level", 15),
                    ("reference", 16),
                    ("visualization", 17),
                    ("connected_actions", 18),
                    ("causality_nav", 19),
                    ("goal_description", 20),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("category_type", 2),
                            ]
                        ],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the value from the reference year.",
                            "label": "Show reference value",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "This can be set to override the default reference year.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show current value",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show goal value",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Default year to pick for the goal value.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the difference between the goal and the current value.",
                            "label": "Show goal gap",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("show_reference_value", 4),
                                ("reference_year", 5),
                                ("show_current_value", 6),
                                ("show_goal_value", 7),
                                ("default_goal_year", 8),
                                ("show_goal_gap", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "name"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "description"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "organization"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "updated_at"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "level"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "reference"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "visualization"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "connected_actions"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "causality_nav"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "goal_description"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indicatorlistpage",
            name="details_main_bottom",
            field=wagtail.fields.StreamField(
                [
                    ("category", 3),
                    ("value_summary", 10),
                    ("name", 11),
                    ("description", 12),
                    ("organization", 13),
                    ("updated_at", 14),
                    ("level", 15),
                    ("reference", 16),
                    ("visualization", 17),
                    ("connected_actions", 18),
                    ("causality_nav", 19),
                    ("goal_description", 20),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("category_type", 2),
                            ]
                        ],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the value from the reference year.",
                            "label": "Show reference value",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "This can be set to override the default reference year.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show current value",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show goal value",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Default year to pick for the goal value.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the difference between the goal and the current value.",
                            "label": "Show goal gap",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("show_reference_value", 4),
                                ("reference_year", 5),
                                ("show_current_value", 6),
                                ("show_goal_value", 7),
                                ("default_goal_year", 8),
                                ("show_goal_gap", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "name"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "description"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "organization"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "updated_at"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "level"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "reference"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "visualization"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "connected_actions"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "causality_nav"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "goal_description"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indicatorlistpage",
            name="details_main_top",
            field=wagtail.fields.StreamField(
                [
                    ("category", 3),
                    ("value_summary", 10),
                    ("name", 11),
                    ("description", 12),
                    ("organization", 13),
                    ("updated_at", 14),
                    ("level", 15),
                    ("reference", 16),
                    ("visualization", 17),
                    ("connected_actions", 18),
                    ("causality_nav", 19),
                    ("goal_description", 20),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("category_type", 2),
                            ]
                        ],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the value from the reference year.",
                            "label": "Show reference value",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "This can be set to override the default reference year.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show current value",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show goal value",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Default year to pick for the goal value.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the difference between the goal and the current value.",
                            "label": "Show goal gap",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("show_reference_value", 4),
                                ("reference_year", 5),
                                ("show_current_value", 6),
                                ("show_goal_value", 7),
                                ("default_goal_year", 8),
                                ("show_goal_gap", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "name"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "description"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "organization"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "updated_at"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "level"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "reference"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "visualization"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "connected_actions"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "causality_nav"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "goal_description"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indicatorlistpage",
            name="list_columns",
            field=wagtail.fields.StreamField(
                [
                    ("category", 4),
                    ("value", 9),
                    ("name", 10),
                    ("organization", 11),
                    ("level", 12),
                    ("unit", 13),
                    ("updated_at", 14),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label for the column to be used instead of the default",
                            "label": "Label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the column to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "append": "-value-category_type",
                            "label": "Category level",
                            "match": "^list_columns-\\d+",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_label", 0),
                                ("column_help_text", 1),
                                ("category_type", 2),
                                ("category_level", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("latest", "Latest value"),
                                ("earliest", "Earliest value"),
                                ("reference", "Reference value"),
                                ("goal", "Goal value"),
                            ]
                        },
                    ),
                    7: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Default value year to pick for this column",
                            "label": "Default year",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_label", 0),
                                ("column_help_text", 1),
                                ("is_normalized", 5),
                                ("value_type", 6),
                                ("reference_year", 7),
                                ("hide_unit", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "name"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "organization"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "level"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "unit"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "updated_at"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 4),
                    ("category_list", 8),
                    ("indicator_group", 14),
                    ("indicator_highlights", 15),
                    ("indicator_showcase", 20),
                    ("dashboard_row", 33),
                    ("action_highlights", 34),
                    ("related_plans", 35),
                    ("cards", 40),
                    ("action_links", 46),
                    ("text", 47),
                    ("action_status_graphs", 48),
                    ("category_tree_map", 51),
                    ("large_image", 53),
                    ("embed", 57),
                    ("paths_outcome", 61),
                    ("raw_visualization", 62),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Big image"),
                                ("small_image", "Small image"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("layout", 0), ("image", 1), ("heading", 2), ("lead", 3)]],
                        {},
                    ),
                    5: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 5),
                                ("category", 6),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    10: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 10), ("style", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("indicators", 13)]],
                        {},
                    ),
                    15: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("page", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("body", 16),
                                ("indicator", 10),
                                ("link_button", 18),
                                ("indicator_is_normalized", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    22: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    23: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 21),
                                ("indicator", 22),
                                ("dimension", 23),
                                ("bar_type", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 21),
                                ("indicator", 22),
                                ("dimension", 23),
                                ("show_total_line", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 21),
                                ("indicator", 22),
                                ("dimension", 23),
                                ("year", 28),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("indicator", 22)]], {}),
                    31: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    32: ("wagtail.blocks.StructBlock", [[("text", 31)]], {}),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 25),
                                ("line_chart", 27),
                                ("area_chart", 27),
                                ("pie_chart", 29),
                                ("indicator_summary", 30),
                                ("paragraph", 32),
                            ]
                        ],
                        {},
                    ),
                    34: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    35: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    36: ("wagtail.blocks.CharBlock", (), {}),
                    37: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 37), ("heading", 36), ("content", 9), ("link", 9)]],
                        {},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 36), ("lead", 9), ("cards", 39)]],
                        {},
                    ),
                    41: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    42: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    43: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("lead", 42), ("category", 43)]],
                        {},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {"label": "Links"}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 45)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    47: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    48: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    49: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    50: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 49),
                                ("value_attribute", 50),
                            ]
                        ],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 52)]],
                        {},
                    ),
                    54: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 54), ("height", 55)]],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 56), ("full_width", 19)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 58), ("help_text", 59), ("outcome_node_id", 60)]],
                        {},
                    ),
                    62: ("pages.blocks.RawVisualizationBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("qa_section", 6),
                    ("category_list", 12),
                    ("category_level_list", 19),
                    ("paths_outcome", 23),
                    ("indicator_group", 29),
                    ("dashboard_row", 42),
                    ("embed", 47),
                    ("category_tree_map", 49),
                    ("large_image", 52),
                    ("raw_visualization", 53),
                    ("cartography_visualisation_block", 57),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Paragraph"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    8: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 7),
                                ("category", 8),
                                ("heading", 9),
                                ("lead", 10),
                                ("style", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Category level list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Category level list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    15: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    16: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {"label": "Filter by level", "required": True},
                    ),
                    17: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths target node ID used to calculate action impacts. If not set, the default outcome node will be used.",
                            "max_length": 200,
                            "required": False,
                            "verbose_name": "Kausal Paths target node ID",
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("help_text", 14),
                                ("category_type", 15),
                                ("category_level", 16),
                                ("group_by_category_level", 17),
                                ("paths_target_node_id", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 20), ("help_text", 21), ("outcome_node_id", 22)]],
                        {},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    25: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 25), ("style", 26)]],
                        {},
                    ),
                    28: ("wagtail.blocks.ListBlock", (27,), {}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 24), ("indicators", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    31: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    32: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("bar_type", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("show_total_line", 35),
                            ]
                        ],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 30),
                                ("indicator", 31),
                                ("dimension", 32),
                                ("year", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("indicator", 31)]], {}),
                    40: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    41: ("wagtail.blocks.StructBlock", [[("text", 40)]], {}),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 34),
                                ("line_chart", 36),
                                ("area_chart", 36),
                                ("pie_chart", 38),
                                ("indicator_summary", 39),
                                ("paragraph", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 43), ("height", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 45), ("full_width", 46)]],
                        {},
                    ),
                    48: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 9),
                                ("lead", 10),
                                ("category_type", 15),
                                ("value_attribute", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 50), ("width", 51)]],
                        {},
                    ),
                    53: ("pages.blocks.RawVisualizationBlock", (), {}),
                    54: (
                        "pages.blocks.CartographyProviderCredentialsChooserBlock",
                        (),
                        {"label": "Map provider credentials"},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "choices": [],
                            "label": "Map style",
                            "required": True,
                            "validators": [],
                        },
                    ),
                    56: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Map labels", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("account", 54), ("style", 55), ("style_overrides", 56)]],
                        {"label": "Map visualization"},
                    ),
                },
                null=True,
            ),
        ),
    ]
