# Generated by Django 5.2 on 2026-01-08 08:48

import django.db.models.deletion
import modeltrans.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0051_alter_actionlistpage_details_aside_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageChangeLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Please summarize the change you made. This message will be displayed publicly.",
                        verbose_name="content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["content"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log_messages",
                        to="wagtailcore.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        help_text="The revision this change history message is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="revision",
                    ),
                ),
            ],
            options={
                "verbose_name": "page change history message",
                "verbose_name_plural": "page change history messages",
            },
        ),
    ]
