# Generated by Django 5.2 on 2026-01-13 09:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0052_pagechangelogmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("qa_section", 6),
                    ("indicator_group", 12),
                    ("related_indicators", 13),
                    ("dashboard_row", 26),
                    ("category_list", 32),
                    ("action_list", 37),
                    ("embed", 42),
                    ("raw_visualization", 43),
                    ("change_log_message", 46),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "heading": "Title",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"heading": "Question"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"heading": "Answer"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 2), ("answer", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("questions", 5)]],
                        {"icon": "help"},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 8), ("style", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("indicators", 11)]],
                        {},
                    ),
                    13: ("indicators.blocks.RelatedIndicatorsBlock", (), {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    15: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    16: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 14),
                                ("indicator", 15),
                                ("dimension", 16),
                                ("bar_type", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 14),
                                ("indicator", 15),
                                ("dimension", 16),
                                ("show_total_line", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 14),
                                ("indicator", 15),
                                ("dimension", 16),
                                ("year", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.StructBlock", [[("indicator", 15)]], {}),
                    24: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    25: ("wagtail.blocks.StructBlock", [[("text", 24)]], {}),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 18),
                                ("line_chart", 20),
                                ("area_chart", 20),
                                ("pie_chart", 22),
                                ("indicator_summary", 23),
                                ("paragraph", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    28: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 27),
                                ("category", 28),
                                ("heading", 29),
                                ("lead", 30),
                                ("style", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Action list?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Action list to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    35: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"label": "Filter on category"},
                    ),
                    36: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "help_text": "Use category level for tabbed grouping in the public UI",
                            "label": "Group by level",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 33),
                                ("help_text", 34),
                                ("category_filter", 35),
                                ("group_by_category_level", 36),
                            ]
                        ],
                        {},
                    ),
                    38: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 38), ("height", 39)]],
                        {},
                    ),
                    41: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 40), ("full_width", 41)]],
                        {},
                    ),
                    43: ("pages.blocks.RawVisualizationBlock", (), {}),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 44), ("field_help_text", 45)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
