# Generated by Django 5.2 on 2026-01-15 10:33

from django.db import migrations


def populate_plan_in_pagechangelogmessages(apps, schema_editor):
    PageChangeLogMessage = apps.get_model('pages', 'PageChangeLogMessage')
    Site = apps.get_model('wagtailcore', 'Site')
    Plan = apps.get_model('actions', 'Plan')

    for msg in PageChangeLogMessage.objects.select_related('page').all():
        page = msg.page

        # Find PlanRootPage ancestor by checking page path
        # In Wagtail's tree structure, we can traverse up by checking the path
        # PlanRootPage is the top-level page for a plan
        # We need to find the root page of the tree that this page belongs to
        site = Site.objects.filter(root_page__path=page.path[:8]).first()  # Wagtail paths use fixed-width segments
        if not site:
            # Try finding by going up the tree
            site = Site.objects.filter(root_page_id__in=page.get_ancestors(inclusive=True).values_list('id', flat=True)).first()

        if site:
            plan = Plan.objects.filter(site=site).first()
            if plan:
                msg.plan = plan
                msg.save(update_fields=['plan'])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0055_add_plan_to_changelogmessages"),
        ("actions", "0155_populate_plan_in_changelogmessages"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RunPython(populate_plan_in_pagechangelogmessages, migrations.RunPython.noop),
    ]
