# Generated by Django 5.2 on 2026-01-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0157_alter_plandomain_redirect_aliases"),
        ("pages", "0058_alter_planrootpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_pages",
                to="actions.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="categorytypepage",
            name="category_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_type_pages",
                to="actions.categorytype",
                verbose_name="Category type",
            ),
        ),
    ]
