# Generated by Django 5.2 on 2026-01-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_aplansimage_latest_revision"),
        ("pages", "0059_alter_categorypage_category_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PledgeListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("i18n", models.JSONField(blank=True, null=True)),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=False,
                        help_text="Should the page be shown in the footer?",
                        verbose_name="show in footer",
                    ),
                ),
                (
                    "show_in_additional_links",
                    models.BooleanField(
                        default=False,
                        help_text="Should the page be shown in the additional links?",
                        verbose_name="show in additional links",
                    ),
                ),
                (
                    "link_in_all_child_plans",
                    models.BooleanField(
                        default=False,
                        help_text="Should this additional link be displayed in child plans?",
                        verbose_name="show link in child plans",
                    ),
                ),
                (
                    "children_use_secondary_navigation",
                    models.BooleanField(
                        default=False,
                        help_text="Should subpages of this page use secondary navigation?",
                        verbose_name="children use secondary navigation",
                    ),
                ),
                (
                    "lead_content",
                    models.TextField(blank=True, verbose_name="lead content"),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.aplansimage",
                        verbose_name="Background image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pledge list page",
                "verbose_name_plural": "Pledge list pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
