# Generated by Django 6.0.2 on 2026-03-26 12:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0063_add_indicator_factor_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorlistpage",
            name="details_aside",
            field=wagtail.fields.StreamField(
                [
                    ("category", 3),
                    ("value_summary", 10),
                    ("description", 11),
                    ("organization", 12),
                    ("updated_at", 13),
                    ("level", 14),
                    ("reference", 15),
                    ("connected_actions", 16),
                    ("causality_nav", 17),
                    ("goal_description", 18),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("category_type", 2),
                            ]
                        ],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the value from the reference year.",
                            "label": "Show reference value",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "This can be set to override the default reference year.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show current value",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Show goal value",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Default year to pick for the goal value.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "This shows the difference between the goal and the current value.",
                            "label": "Show goal gap",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 0),
                                ("field_help_text", 1),
                                ("show_reference_value", 4),
                                ("reference_year", 5),
                                ("show_current_value", 6),
                                ("show_goal_value", 7),
                                ("default_goal_year", 8),
                                ("show_goal_gap", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "description"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "organization"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "updated_at"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "level"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "reference"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "connected_actions"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "causality_nav"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 0), ("field_help_text", 1)]],
                        {"field_name": "goal_description"},
                    ),
                },
                null=True,
            ),
        ),
    ]
