# Generated by Django 6.0.2 on 2026-04-20 11:50

import reports.report_formatters
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0065_alter_categorytypepagelevellayout_layout_main_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_main_bottom",
            field=wagtail.fields.StreamField(
                [
                    ("section", 10),
                    ("contact_form", 26),
                    ("report_comparison", 29),
                    ("indicator_causal_chain", 30),
                    ("datasets", 34),
                    ("change_log_message", 35),
                    ("lead_paragraph", 36),
                    ("description", 37),
                    ("official_name", 40),
                    ("attribute", 41),
                    ("categories", 42),
                    ("links", 43),
                    ("tasks", 44),
                    ("merged_actions", 45),
                    ("related_actions", 46),
                    ("dependencies", 47),
                    ("related_indicators", 48),
                    ("pledges", 49),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("full-width", "Full width"), ("grid", "Grid")]},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    5: (
                        "actions.blocks.choosers.ActionAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("attribute", 6), ("categories", 8)]],
                        {"label": "Blocks"},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("heading", 1),
                                ("help_text", 2),
                                ("blocks", 9),
                            ]
                        ],
                        {"required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Heading", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Description", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the feedback field.",
                            "label": "Feedback field visible",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the feedback field required when visible.",
                            "label": "Feedback required",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the email field.",
                            "label": "Email field visible",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the email field required when visible.",
                            "label": "Email required",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Field Label", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("checkbox", "Checkbox"),
                                ("dropdown", "Dropdown"),
                            ],
                            "label": "Field Type",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Label", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Value", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("choice_label", 20), ("choice_value", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("choice_field", 22)]],
                        {"label": "Choices", "min_num": 0, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 17),
                                ("field_type", 18),
                                ("field_required", 19),
                                ("choices", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [[("form_field", 24)]],
                        {
                            "help_text": "Form fields to be shown in addition to Name, Email and Comment fields",
                            "label": "Additional form fields",
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("description", 12),
                                ("feedback_visible", 13),
                                ("feedback_required", 14),
                                ("email_visible", 15),
                                ("email_required", 16),
                                ("fields", 25),
                            ]
                        ],
                        {"required": True},
                    ),
                    27: (
                        "reports.blocks.choosers.ReportTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "reports.blocks.choosers.ReportTypeFieldChooserBlock",
                        (),
                        {"label": "UUID of report field", "required": True},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("report_type", 27), ("report_field", 28)]],
                        {},
                    ),
                    30: (
                        "actions.blocks.action_content_blocks.IndicatorCausalChainBlock",
                        (),
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the dataset?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Dataset to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    33: (
                        "actions.blocks.choosers.PlanDatasetSchemaChooserBlock",
                        (),
                        {"required": True},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("help_text", 32), ("dataset_schema", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "lead_paragraph"},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "description"},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What label should be used in the public UI for the official name?",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Description to show after the field content",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 38),
                                ("field_help_text", 4),
                                ("caption", 39),
                            ]
                        ],
                        {"field_name": "official_name"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {
                            "field_name": "attribute",
                            "report_value_formatter_class": reports.report_formatters.ActionAttributeTypeReportFieldFormatter,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {
                            "field_name": "categories",
                            "report_value_formatter_class": reports.report_formatters.ActionCategoryReportFieldFormatter,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "links"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "tasks",
                            "report_value_formatter_class": reports.report_formatters.ActionTasksFormatter,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "merged_actions"},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "related_actions"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "dependencies"},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "related_indicators",
                            "report_value_formatter_class": reports.report_formatters.ActionIndicatorsFormatter,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "pledges"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionlistpage",
            name="details_main_top",
            field=wagtail.fields.StreamField(
                [
                    ("section", 10),
                    ("contact_form", 26),
                    ("report_comparison", 29),
                    ("indicator_causal_chain", 30),
                    ("datasets", 34),
                    ("change_log_message", 35),
                    ("lead_paragraph", 36),
                    ("description", 37),
                    ("official_name", 40),
                    ("attribute", 41),
                    ("categories", 42),
                    ("links", 43),
                    ("tasks", 44),
                    ("merged_actions", 45),
                    ("related_actions", 46),
                    ("dependencies", 47),
                    ("related_indicators", 48),
                    ("pledges", 49),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("full-width", "Full width"), ("grid", "Grid")]},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Help text", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    5: (
                        "actions.blocks.choosers.ActionAttributeTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("attribute", 6), ("categories", 8)]],
                        {"label": "Blocks"},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("heading", 1),
                                ("help_text", 2),
                                ("blocks", 9),
                            ]
                        ],
                        {"required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Heading", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Description", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the feedback field.",
                            "label": "Feedback field visible",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the feedback field required when visible.",
                            "label": "Feedback required",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Toggle visibility of the email field.",
                            "label": "Email field visible",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Make the email field required when visible.",
                            "label": "Email required",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Field Label", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Text"),
                                ("checkbox", "Checkbox"),
                                ("dropdown", "Dropdown"),
                            ],
                            "label": "Field Type",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Required", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Label", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Value", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("choice_label", 20), ("choice_value", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("choice_field", 22)]],
                        {"label": "Choices", "min_num": 0, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 17),
                                ("field_type", 18),
                                ("field_required", 19),
                                ("choices", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [[("form_field", 24)]],
                        {
                            "help_text": "Form fields to be shown in addition to Name, Email and Comment fields",
                            "label": "Additional form fields",
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("description", 12),
                                ("feedback_visible", 13),
                                ("feedback_required", 14),
                                ("email_visible", 15),
                                ("email_required", 16),
                                ("fields", 25),
                            ]
                        ],
                        {"required": True},
                    ),
                    27: (
                        "reports.blocks.choosers.ReportTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "reports.blocks.choosers.ReportTypeFieldChooserBlock",
                        (),
                        {"label": "UUID of report field", "required": True},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("report_type", 27), ("report_field", 28)]],
                        {},
                    ),
                    30: (
                        "actions.blocks.action_content_blocks.IndicatorCausalChainBlock",
                        (),
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the dataset?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Dataset to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    33: (
                        "actions.blocks.choosers.PlanDatasetSchemaChooserBlock",
                        (),
                        {"required": True},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("help_text", 32), ("dataset_schema", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "lead_paragraph"},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "description"},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What label should be used in the public UI for the official name?",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Description to show after the field content",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 38),
                                ("field_help_text", 4),
                                ("caption", 39),
                            ]
                        ],
                        {"field_name": "official_name"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("attribute_type", 5),
                            ]
                        ],
                        {
                            "field_name": "attribute",
                            "report_value_formatter_class": reports.report_formatters.ActionAttributeTypeReportFieldFormatter,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_label", 3),
                                ("field_help_text", 4),
                                ("category_type", 7),
                            ]
                        ],
                        {
                            "field_name": "categories",
                            "report_value_formatter_class": reports.report_formatters.ActionCategoryReportFieldFormatter,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "links"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "tasks",
                            "report_value_formatter_class": reports.report_formatters.ActionTasksFormatter,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "merged_actions"},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "related_actions"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "dependencies"},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {
                            "field_name": "related_indicators",
                            "report_value_formatter_class": reports.report_formatters.ActionIndicatorsFormatter,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 3), ("field_help_text", 4)]],
                        {"field_name": "pledges"},
                    ),
                },
                null=True,
            ),
        ),
    ]
