# Generated by Django 6.0.2 on 2026-06-03 12:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0068_alter_categorypage_body_alter_planrootpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrootpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("front_page_hero", 9),
                    ("category_list", 13),
                    ("indicator_group", 19),
                    ("indicator_highlights", 20),
                    ("indicator_showcase", 26),
                    ("dashboard_row", 41),
                    ("action_highlights", 42),
                    ("related_plans", 43),
                    ("cards", 48),
                    ("action_links", 54),
                    ("text", 55),
                    ("action_status_graphs", 56),
                    ("category_tree_map", 59),
                    ("large_image", 61),
                    ("embed", 67),
                    ("paths_outcome", 71),
                    ("change_log_message", 74),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("big_image", "Full-width: content over image"),
                                (
                                    "small_image",
                                    "Large image: image above, content below",
                                ),
                                (
                                    "side_by_side",
                                    "Side-by-side: image left, content right",
                                ),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Lead", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CSS colour value, e.g. #FFFFFF or rgb(255, 255, 255)",
                            "label": "Background colour",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show the image at its exact scaled dimensions; it will never be cropped",
                            "label": "Fit image without clipping",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Display a brand color accent bar below the image",
                            "label": "Show image accent",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Extend the background colour to cover the content below the image, not just the image area",
                            "label": "Background covers full block",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_colour", 4),
                                ("fit_image", 5),
                                ("show_image_accent", 6),
                                ("background_covers_full_section", 7),
                            ]
                        ],
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout", 0),
                                ("image", 1),
                                ("heading", 2),
                                ("lead", 3),
                                ("additional_settings", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": False},
                    ),
                    11: (
                        "actions.blocks.choosers.CategoryChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("cards", "Cards"), ("table", "Table")],
                            "label": "Style",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category_type", 10),
                                ("category", 11),
                                ("heading", 2),
                                ("lead", 3),
                                ("style", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    15: ("indicators.blocks.IndicatorChooserBlock", (), {}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("graph", "Graph"),
                                ("progress", "Progress"),
                                ("animated", "Animated"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("indicator", 15), ("style", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 14), ("indicators", 18)]],
                        {},
                    ),
                    20: ("indicators.blocks.IndicatorHighlightsBlock", (), {}),
                    21: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    22: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 14), ("page", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "How many significants digits to use for the values displayed",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    25: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("body", 21),
                                ("indicator", 15),
                                ("link_button", 23),
                                ("significant_digits", 24),
                                ("indicator_is_normalized", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the field to be shown in the UI",
                            "required": False,
                        },
                    ),
                    28: (
                        "indicators.blocks.IndicatorChooserBlock",
                        (),
                        {"help_text": "Choose the indicator for data visualization"},
                    ),
                    29: (
                        "indicators.blocks.DimensionChooserBlock",
                        (),
                        {
                            "help_text": "Choose the indicator dimension that will be used for categories in the visualization",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("stacked", "Stacked bars"),
                                ("grouped", "Grouped bars"),
                            ]
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 27),
                                ("indicator", 28),
                                ("dimension", 29),
                                ("bar_type", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show total line",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 27),
                                ("indicator", 28),
                                ("dimension", 29),
                                ("show_total_line", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Enter the year you want to visualize",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("help_text", 27),
                                ("indicator", 28),
                                ("dimension", 29),
                                ("year", 34),
                            ]
                        ],
                        {},
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("indicator", 28)]], {}),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    38: ("wagtail.blocks.StructBlock", [[("text", 37)]], {}),
                    39: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    40: ("wagtail.blocks.StructBlock", [[("text", 39)]], {}),
                    41: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("bar_chart", 31),
                                ("line_chart", 33),
                                ("area_chart", 33),
                                ("pie_chart", 35),
                                ("indicator_summary", 36),
                                ("header", 38),
                                ("paragraph", 40),
                            ]
                        ],
                        {},
                    ),
                    42: ("actions.blocks.action_list.ActionHighlightsBlock", (), {}),
                    43: ("actions.blocks.RelatedPlanListBlock", (), {}),
                    44: ("wagtail.blocks.CharBlock", (), {}),
                    45: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 45),
                                ("heading", 44),
                                ("content", 14),
                                ("link", 14),
                            ]
                        ],
                        {},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 44), ("lead", 14), ("cards", 47)]],
                        {},
                    ),
                    49: ("wagtail.blocks.CharBlock", (), {"label": "Heading"}),
                    50: ("wagtail.blocks.CharBlock", (), {"label": "Lead"}),
                    51: ("actions.blocks.choosers.CategoryChooserBlock", (), {}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 49), ("lead", 50), ("category", 51)]],
                        {},
                    ),
                    53: ("wagtail.blocks.ListBlock", (52,), {"label": "Links"}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("cards", 53)]],
                        {"label": "Links to actions in specific category"},
                    ),
                    55: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    56: ("pages.blocks.ActionStatusGraphsBlock", (), {}),
                    57: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    58: (
                        "actions.blocks.choosers.CategoryAttributeTypeChooserBlock",
                        (),
                        {"label": "Value field", "required": True},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("lead", 3),
                                ("category_type", 57),
                                ("value_attribute", 58),
                            ]
                        ],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("maximum", "Maximum"),
                                ("fit_to_column", "Fit to column"),
                            ],
                            "label": "Width",
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("width", 60)]],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers describe this embedded content",
                            "label": "Title",
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Helps screen readers understand what this embed shows",
                            "label": "Description",
                            "required": False,
                        },
                    ),
                    64: ("wagtail.blocks.CharBlock", (), {"label": "URL"}),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("s", "small"),
                                ("m", "medium"),
                                ("l", "large"),
                            ],
                            "label": "Size",
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 64), ("height", 65)]],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 62),
                                ("description", 63),
                                ("embed", 66),
                                ("full_width", 25),
                            ]
                        ],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "What heading should be used in the public UI for the Outcome?",
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the Outcome to be shown in the public UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kausal Paths outcome node to be used",
                            "max_length": 200,
                            "required": True,
                            "verbose_name": "Kausal Paths outcome node ID",
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 68), ("help_text", 69), ("outcome_node_id", 70)]],
                        {},
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Heading to show instead of the default",
                            "label": "Field label",
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Help text for the field to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("field_label", 72), ("field_help_text", 73)]],
                        {},
                    ),
                },
            ),
        ),
    ]
