# Generated by Django 6.0.2 on 2026-06-03 14:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0069_add_front_page_hero_additional_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorlistpage",
            name="list_columns",
            field=wagtail.fields.StreamField(
                [
                    ("category", 4),
                    ("value", 10),
                    ("name", 11),
                    ("organization", 12),
                    ("level", 13),
                    ("unit", 14),
                    ("updated_at", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label for the column to be used instead of the default",
                            "label": "Label",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Help text for the column to be shown in the UI",
                            "label": "Help text",
                            "required": False,
                        },
                    ),
                    2: (
                        "actions.blocks.choosers.CategoryTypeChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "actions.blocks.choosers.CategoryLevelChooserBlock",
                        (),
                        {
                            "append": "-value-category_type",
                            "label": "Category level",
                            "match": "^list_columns-\\d+",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_label", 0),
                                ("column_help_text", 1),
                                ("category_type", 2),
                                ("category_level", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("latest", "Latest value"),
                                ("earliest", "Earliest value"),
                                ("reference", "Reference value"),
                                ("goal", "Goal value"),
                            ]
                        },
                    ),
                    7: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Default value year to pick for this column",
                            "label": "Default year",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show a tick next to the latest value when the indicator has reached its goal.",
                            "label": "Highlight if goal is met",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_label", 0),
                                ("column_help_text", 1),
                                ("is_normalized", 5),
                                ("value_type", 6),
                                ("reference_year", 7),
                                ("hide_unit", 8),
                                ("highlight_goal_met", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "name"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "organization"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "level"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "unit"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("column_label", 0), ("column_help_text", 1)]],
                        {"field_name": "updated_at"},
                    ),
                },
                null=True,
            ),
        ),
    ]
