# Generated by Django 3.2.13 on 2023-03-04 12:44

import aplans.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import reports.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0072_remove_report_fks'),
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ReportType',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, verbose_name='name')),
                        ('fields', wagtail.core.fields.StreamField([('implementation_phase', reports.blocks.ActionImplementationPhaseReportFieldBlock()), ('text_attribute', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(heading='Name')), ('identifier', wagtail.core.blocks.CharBlock(heading='Identifier'))]))], blank=True, null=True)),
                        ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.plan')),
                    ],
                    options={
                        'verbose_name': 'report type',
                        'verbose_name_plural': 'report types',
                    },
                    bases=(models.Model, aplans.utils.PlanRelatedModel),
                ),
                migrations.CreateModel(
                    name='Report',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, verbose_name='name')),
                        ('identifier', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=('type',))),
                        ('start_date', models.DateField(verbose_name='start date')),
                        ('end_date', models.DateField(verbose_name='end date')),
                        ('fields', wagtail.core.fields.StreamField([('implementation_phase', reports.blocks.ActionImplementationPhaseReportFieldBlock()), ('text_attribute', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(heading='Name')), ('identifier', wagtail.core.blocks.CharBlock(heading='Identifier'))]))], blank=True, null=True)),
                        ('is_complete', models.BooleanField(default=False, help_text='Set if report cannot be changed anymore', verbose_name='complete')),
                        ('is_public', models.BooleanField(default=False, help_text='Set if report can be shown to the public', verbose_name='public')),
                        ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype')),
                    ],
                    options={
                        'verbose_name': 'report',
                        'verbose_name_plural': 'reports',
                    },
                ),
                migrations.CreateModel(
                    name='ActionSnapshot',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reversion.version')),
                        ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                    ],
                    options={
                        'verbose_name': 'action snapshot',
                        'verbose_name_plural': 'action snapshots',
                    },
                ),
            ],
        ),
    ]
