# Generated by Django 3.2.13 on 2023-03-08 16:36

import actions.blocks.choosers
from django.db import migrations, models
import django.db.models.deletion
import reports.blocks.action_content
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        ('actions', '0074_remove_attribute_type_links_to_reports'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionsnapshot',
            options={'get_latest_by': 'action_version__revision__date_created', 'verbose_name': 'action snapshot', 'verbose_name_plural': 'action snapshots'},
        ),
        migrations.AddField(
            model_name='actionsnapshot',
            name='created_explicitly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actionsnapshot',
            name='action_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_snapshots', to='reversion.version'),
        ),
        migrations.AlterField(
            model_name='actionsnapshot',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_snapshots', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fields',
            field=wagtail.core.fields.StreamField([('implementation_phase', reports.blocks.action_content.ActionImplementationPhaseReportFieldBlock()), ('attribute_type', wagtail.core.blocks.StructBlock([('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock(label='Attribute type', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.reporttype'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='fields',
            field=wagtail.core.fields.StreamField([('implementation_phase', reports.blocks.action_content.ActionImplementationPhaseReportFieldBlock()), ('attribute_type', wagtail.core.blocks.StructBlock([('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock(label='Attribute type', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_types', to='actions.plan'),
        ),
    ]
