# Generated by Django 3.2.16 on 2023-06-14 09:52

import actions.blocks.choosers
from django.db import migrations
import reports.blocks.action_content
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_migrate_legacy_reporting_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fields',
            field=wagtail.fields.StreamField([('implementation_phase', reports.blocks.action_content.ActionImplementationPhaseReportFieldBlock()), ('attribute_type', wagtail.blocks.StructBlock([('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock(label='Field', required=True))])), ('responsible_party', reports.blocks.action_content.ActionResponsiblePartyReportFieldBlock())], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='fields',
            field=wagtail.fields.StreamField([('implementation_phase', reports.blocks.action_content.ActionImplementationPhaseReportFieldBlock()), ('attribute_type', wagtail.blocks.StructBlock([('attribute_type', actions.blocks.choosers.ActionAttributeTypeChooserBlock(label='Field', required=True))])), ('responsible_party', reports.blocks.action_content.ActionResponsiblePartyReportFieldBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
