# Generated by Django 3.2.16 on 2024-03-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0119_add_planfeatures_report_print_layout'),
        ('reports', '0006_remove_fk_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActionPrintLayoutCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_columns', models.IntegerField(null=True)),
                ('approximate_chars_per_line', models.IntegerField(null=True)),
                ('approximate_lines_per_page', models.IntegerField(null=True)),
                ('min_split_chars', models.IntegerField(null=True)),
                ('width_needed', models.JSONField(null=True)),
                ('plan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='actions.plan')),
            ],
        ),
    ]
