# Generated by Django 5.0.6 on 2024-12-01 14:55

from django.db import migrations

from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import RenameStreamChildrenOperation


OPERATIONS_AND_BLOCK_PATHS = [
    (RenameStreamChildrenOperation(old_name='attribute_type', new_name='attribute'), ''),
    (RenameStreamChildrenOperation(old_name='responsible_party', new_name='responsible_parties'), ''),
    (RenameStreamChildrenOperation(old_name='category', new_name='categories'), ''),
]

class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_alter_report_fields_alter_reporttype_fields"),
    ]

    operations = [
        MigrateStreamData(
            app_name='reports',
            model_name='Report',
            field_name='fields',
            operations_and_block_paths=OPERATIONS_AND_BLOCK_PATHS,
        ),
        MigrateStreamData(
            app_name='reports',
            model_name='ReportType',
            field_name='fields',
            operations_and_block_paths=OPERATIONS_AND_BLOCK_PATHS,
        )
    ]
