# Generated by Django 5.0.6 on 2025-01-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_report_fields_block_datamigration_for_renaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='only_plan_admins_can_mark_actions_as_complete',
            field=models.BooleanField(default=False, help_text='Only plan admins can mark actions as complete for reports of this type'),
        ),
    ]
