# Generated by Django 5.2 on 2025-11-04 06:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_reporttype_only_plan_admins_can_mark_actions_as_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fields',
            field=wagtail.fields.StreamField([], null=True),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='fields',
            field=wagtail.fields.StreamField([], null=True),
        ),
    ]
