# Generated by Django 3.1.5 on 2021-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplansimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aplansimage',
            name='image_credit',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
