# Generated by Django 5.0.6 on 2024-09-02 12:04

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_fk_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplansrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
