FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.3
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install \
    https://github.com/EvidentSolutions/elasticsearch-analysis-raudikko/releases/download/v0.1.1/elasticsearch-analysis-raudikko-0.1.1-es7.16.3.zip
