# Generated by Django 5.2 on 2026-01-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="modellogentry_migration_instance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.modellogentry",
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="pagelogentry_migration_instance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.pagelogentry",
            ),
        ),
    ]
