# Generated by Django 5.2 on 2026-01-16 07:15

from django.db import migrations


def copy_ptr_to_migration_instance(apps, schema_editor):
    PlanScopedModelLogEntry = apps.get_model('audit_logging', 'PlanScopedModelLogEntry')
    PlanScopedPageLogEntry = apps.get_model('audit_logging', 'PlanScopedPageLogEntry')

    # Copy modellogentry_ptr_id to modellogentry_migration_instance_id
    for entry in PlanScopedModelLogEntry.objects.all():
        entry.modellogentry_migration_instance_id = entry.modellogentry_ptr_id
        entry.save(update_fields=['modellogentry_migration_instance_id'])

    # Copy pagelogentry_ptr_id to pagelogentry_migration_instance_id
    for entry in PlanScopedPageLogEntry.objects.all():
        entry.pagelogentry_migration_instance_id = entry.pagelogentry_ptr_id
        entry.save(update_fields=['pagelogentry_migration_instance_id'])


def reverse_copy(apps, schema_editor):
    PlanScopedModelLogEntry = apps.get_model('audit_logging', 'PlanScopedModelLogEntry')
    PlanScopedPageLogEntry = apps.get_model('audit_logging', 'PlanScopedPageLogEntry')

    # Clear the migration instance fields
    PlanScopedModelLogEntry.objects.all().update(modellogentry_migration_instance_id=None)
    PlanScopedPageLogEntry.objects.all().update(pagelogentry_migration_instance_id=None)


class Migration(migrations.Migration):

    dependencies = [
        (
            'audit_logging',
            '0002_planscopedmodellogentry_modellogentry_migration_instance_and_more',
        ),
    ]

    operations = [
        migrations.RunPython(copy_ptr_to_migration_instance, reverse_copy),
    ]
