# Generated by Django 5.2 on 2026-01-16 07:42

from django.db import migrations, models

from audit_logging.migration_operations import SetModelBasesOptionOperation


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0003_copy_ptr_to_migration_instance"),
    ]

    operations = [
        SetModelBasesOptionOperation(
            name='PlanScopedModelLogEntry',
            bases=(models.Model,),
        ),
        SetModelBasesOptionOperation(
            name='PlanScopedPageLogEntry',
            bases=(models.Model,),
        ),
        migrations.AlterModelOptions(
            name="planscopedmodellogentry",
            options={},
        ),
        migrations.AlterModelOptions(
            name="planscopedpagelogentry",
            options={},
        ),
        migrations.RemoveField(
            model_name="planscopedmodellogentry",
            name="modellogentry_ptr",
        ),
        migrations.RemoveField(
            model_name="planscopedpagelogentry",
            name="pagelogentry_ptr",
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
