# Generated by Django 5.2 on 2026-01-16 08:08

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0004_alter_planscopedmodellogentry_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="action",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="content_changed",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="deleted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="object_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="timestamp (UTC)"
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planscopedmodellogentry",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Log entries that happened as part of the same user action are assigned the same UUID",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="action",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="content_changed",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="deleted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="page",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="timestamp (UTC)"
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planscopedpagelogentry",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Log entries that happened as part of the same user action are assigned the same UUID",
                null=True,
            ),
        ),
    ]
