# Generated by Django 5.2 on 2026-01-16 12:27

import datetime
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit_logging",
            "0008_remove_planscopedmodellogentry_modellogentry_migration_instance_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planscopedmodellogentry",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
            },
        ),
        migrations.AlterModelOptions(
            name="planscopedpagelogentry",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
            },
        ),
        migrations.AlterField(
            model_name="planscopedmodellogentry",
            name="action",
            field=models.CharField(
                blank=True, db_index=True, default="ERROR", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planscopedmodellogentry",
            name="content_changed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="planscopedmodellogentry",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="planscopedmodellogentry",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="planscopedmodellogentry",
            name="label",
            field=models.TextField(default="ERROR"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planscopedmodellogentry",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.UTC),
                verbose_name="timestamp (UTC)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planscopedpagelogentry",
            name="action",
            field=models.CharField(
                blank=True, db_index=True, default="ERROR", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planscopedpagelogentry",
            name="content_changed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="planscopedpagelogentry",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="planscopedpagelogentry",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="planscopedpagelogentry",
            name="label",
            field=models.TextField(default="ERROR"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planscopedpagelogentry",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.UTC),
                verbose_name="timestamp (UTC)",
            ),
            preserve_default=False,
        ),
    ]
