# Generated by Django 5.2 on 2026-01-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0010_make_object_id_and_page_non_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planscopedmodellogentry",
            options={
                "ordering": ["-timestamp", "-id"],
                "verbose_name": "plan scoped model log entry",
                "verbose_name_plural": "plan scoped model log entries",
            },
        ),
        migrations.AlterModelOptions(
            name="planscopedpagelogentry",
            options={
                "ordering": ["-timestamp", "-id"],
                "verbose_name": "plan scoped page log entry",
                "verbose_name_plural": "plan scoped page log entries",
            },
        ),
    ]
