# Generated by Django 6.1 on 2026-09-25 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0196_rename_show_login_link_in_public_ui'),
        ('people', '0018_alter_person_image_cropping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='people.person', verbose_name='person')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='actions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'access request',
                'verbose_name_plural': 'access requests',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('plan', 'email'), name='access_request_one_pending_per_email')],
            },
        ),
    ]
