# Generated by Django 3.2.13 on 2022-12-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0061_plan_version_name'),
        ('feedback', '0002_alter_userfeedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='actions.plan'),
        ),
    ]
