# Generated by Django 5.0.6 on 2024-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_latest_revision_and_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='page_id',
            field=models.CharField(blank=True, null=True, verbose_name='page id'),
        ),
    ]
