# Generated by Django 5.2 on 2025-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_aplansdocument_uploaded_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplansdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
