# Generated by Django 3.2.16 on 2024-04-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_log', '0002_alter_loggedrequest_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedrequest',
            name='impersonator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_impersonated_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
