# Generated by Django 2.2.4 on 2019-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_change_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
