# Generated by Django 3.2.13 on 2022-06-13 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_person_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_for_actions_unordered',
            field=models.ManyToManyField(blank=True, through='actions.ActionContactPerson', to='actions.Action', verbose_name='contact for actions'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
