# Generated by Django 2.2.4 on 2019-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_local_avatar_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
