# Generated by Django 3.2.16 on 2024-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='public_site_only',
            field=models.BooleanField(default=False, help_text='Set to enable read-only access to public site', verbose_name='Restrict access to public site'),
        ),
    ]
