# Generated by Django 3.1.5 on 2021-09-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_wagtail_editing'),
        ('people', '0009_person_organization_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organization_new',
            field=models.ForeignKey(help_text="What is this person's organization", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='orgs.organization', verbose_name='organization'),
        ),
    ]
