# Generated by Django 3.2.16 on 2024-02-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_person_public_site_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='public_site_only',
        ),
    ]
