# Generated by Django 3.1.5 on 2021-09-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_wagtail_editing'),
        ('people', '0010_person_organization_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(help_text="What is this person's organization", on_delete=django.db.models.deletion.PROTECT, related_name='people', to='orgs.organization', verbose_name='organization'),
        ),
    ]
