# Generated by Django 5.0.6 on 2024-12-19 11:56

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_remove_fk_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '360x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
    ]
