# Generated by Django 5.2 on 2025-10-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_person_image_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='image_msgraph_etag',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
