# Generated by Django 5.2 on 2025-11-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0028_datamigration_organization_abbreviation"),
        ("people", "0013_person_image_hash_person_image_msgraph_etag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="orgs.organization",
                verbose_name="organization",
            ),
        ),
    ]
