# Generated by Django 5.2 on 2026-01-15 09:51

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0015_person_latest_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image_cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "1280x720",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="image cropping",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Job title or role of this person",
                max_length=100,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
