# Generated by Django 5.2 on 2026-01-20 14:25

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0016_alter_person_image_cropping_alter_person_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image_cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "360x360",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="image cropping",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="participated_in_training",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Set to keep track who have attended training sessions",
                null=True,
                verbose_name="participated in training",
            ),
        ),
    ]
