# Generated by Django 3.2.9 on 2022-02-15 13:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_user'),
        ('orgs', '0005_add_logo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMetadataAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='person')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='metadata_admins',
            field=models.ManyToManyField(blank=True, related_name='metadata_adminable_organizations', through='orgs.OrganizationMetadataAdmin', to='people.Person'),
        ),
        migrations.AddConstraint(
            model_name='organizationmetadataadmin',
            constraint=models.UniqueConstraint(fields=('organization', 'person'), name='unique_organization_metadata_admin'),
        ),
    ]
