# Generated by Django 3.2.9 on 2022-02-17 11:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_update_languages'),
        ('people', '0002_person_user'),
        ('orgs', '0006_create_organization_metadata_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationAdmin',
            new_name='OrganizationPlanAdmin',
        ),
        migrations.AlterField(
            model_name='organizationplanadmin',
            name='organization',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_plan_admins', to='orgs.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='organizationplanadmin',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_plan_admins', to='people.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='organizationplanadmin',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_plan_admins', to='actions.plan', verbose_name='plan'),
        ),
        migrations.RemoveConstraint(
            model_name='organizationplanadmin',
            name='unique_organization_admin',
        ),
        migrations.AddConstraint(
            model_name='organizationplanadmin',
            constraint=models.UniqueConstraint(fields=('organization', 'plan', 'person'), name='unique_organization_plan_admin'),
        ),
    ]
