# Generated by Django 3.2.13 on 2022-06-15 12:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_organization_primary_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organizationmetadataadmin',
            options={'verbose_name': 'metadata admin', 'verbose_name_plural': 'metadata admins'},
        ),
        migrations.AlterModelOptions(
            name='organizationplanadmin',
            options={'verbose_name': 'plan admin', 'verbose_name_plural': 'plan admins'},
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='A commonly used abbreviation', max_length=50, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='An organization category, e.g. committee', null=True, on_delete=django.db.models.deletion.PROTECT, to='orgs.organizationclass', verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='An optional logo for this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.aplansimage'),
        ),
        migrations.AlterField(
            model_name='organizationmetadataadmin',
            name='organization',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_metadata_admins', to='orgs.organization', verbose_name='organization'),
        ),
    ]
