# Generated by Django 3.2.13 on 2022-06-20 09:33

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_add_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
