# Generated by Django 3.2.16 on 2024-02-25 14:17

import kausal_common.i18n.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_alter_organization_primary_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('en', 'English (United States)'), ('en-AU', 'English (Australia)'), ('en-GB', 'English (United Kingdom)'), ('es', 'Spanish'), ('es-US', 'Spanish (United States)'), ('fi', 'Finnish'), ('lv', 'Latvian'), ('sv', 'Swedish'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese (Brazil)')], default=kausal_common.i18n.helpers.get_default_language, max_length=8),
        ),
    ]
