# Generated by Django 5.0.6 on 2024-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_organization_primary_language_lowercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=[('da', 'Danish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('el', 'Greek'), ('en', 'English (United States)'), ('en-AU', 'English (Australia)'), ('en-GB', 'English (United Kingdom)'), ('es', 'Spanish'), ('es-US', 'Spanish (United States)'), ('fi', 'Finnish'), ('lv', 'Latvian'), ('pt', 'Portuguese'), ('pt-BR', 'Portuguese (Brazil)'), ('sv', 'Swedish'), ('sv-FI', 'Swedish (Finland)')], max_length=8, verbose_name='primary language'),
        ),
    ]
