# Generated by Django 5.0.6 on 2024-09-18 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_aplansrendition_file'),
        ('orgs', '0024_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ForeignKey(blank=True, help_text="Organization logo. Please provide a square image (min. 250x250px). The logo used for the organization's social media often works best.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.aplansimage'),
        ),
    ]
