# Generated by Django 5.2 on 2025-08-07 14:17

import kausal_common.i18n.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=kausal_common.i18n.helpers.get_supported_languages, max_length=8, verbose_name='primary language'),
        ),
    ]
