# Generated by Django 5.2 on 2025-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_alter_organization_primary_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='A simplified short version of name for the general public', max_length=50, null=True, verbose_name='Short name'),
        ),
    ]
