# Generated by Django 5.2 on 2025-08-12 06:02

from django.db import migrations


def null_to_empty_str(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    for row in Organization.objects.all():
        if row.abbreviation is None:
            row.abbreviation = ''
        row.save(update_fields=['abbreviation'])


def empty_str_to_null(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    for row in Organization.objects.all():
        if row.abbreviation == '':
            row.abbreviation = None
        row.save(update_fields=['abbreviation'])


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_alter_organization_abbreviation'),
    ]

    operations = [
        migrations.RunPython(empty_str_to_null, null_to_empty_str)
    ]
