# Generated by Django 6.1 on 2026-09-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0030_alter_organization_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['path'], 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
    ]
