# Generated by Django 3.0.6 on 2020-08-07 08:44

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0050_add_supported_languages_to_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('azure_ad_tenant_id', models.CharField(max_length=200)),
                ('login_header_text', models.CharField(max_length=200, verbose_name='login header text')),
                ('login_button_text', models.CharField(max_length=200, verbose_name='login button text')),
                ('i18n', modeltrans.fields.TranslationField(fields=['login_header_text', 'login_button_text'], required_languages=(), virtual_fields=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='admin_site.Client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='actions.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='AdminHostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_hostnames', to='admin_site.Client')),
            ],
        ),
    ]
