# Generated by Django 3.0.6 on 2020-08-05 11:04

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0047_add_root_collection_to_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('azure_ad_tenant_id', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='admin_site.Client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='actions.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='AdminHostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_hostnames', to='admin_site.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('login_header_text', models.CharField(max_length=200, verbose_name='login header text')),
                ('login_button_text', models.CharField(max_length=200, verbose_name='login button text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='admin_site.Client')),
            ],
            options={
                'verbose_name': 'client Translation',
                'db_table': 'admin_site_client_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
