# Generated by Django 3.1.5 on 2021-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_auto_20210929_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='use_id_token_email_field',
            field=models.BooleanField(default=False, verbose_name='use email field of ID Token'),
        ),
        migrations.AlterField(
            model_name='client',
            name='azure_ad_tenant_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
