# Generated by Django 3.1 on 2020-11-10 12:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0063_make_official_name_text_field'),
        ('admin_site', '0002_add_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhostname',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='adminhostname',
            name='client',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_hostnames', to='admin_site.client'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='client',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='admin_site.client'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='plan',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='actions.plan'),
        ),
    ]
