# Generated by Django 3.2.13 on 2023-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_add_client_use_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhostname',
            name='clients',
            field=models.ManyToManyField(to='admin_site.Client'),
        ),
    ]
