# Generated by Django 3.2.12 on 2022-03-21 14:57

import aplans.fields
from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_add_client_use_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='primary_language',
            field=aplans.fields.LanguageChoiceField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German')], default=aplans.fields.get_default_language, max_length=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='i18n',
            field=i18n.fields.TranslationField(fields=['login_header_text', 'login_button_text'], required_languages=(), virtual_fields=True),
        ),
    ]
