# Generated by Django 3.2.16 on 2023-06-29 22:53

from django.db import migrations, models


def set_auth_backend(apps, schema_editor):
    Client = apps.get_model('admin_site', 'Client')
    for client in Client.objects.all():
        if client.google_login_enabled:
            client.auth_backend = 'google-openidconnect'
        elif client.azure_ad_tenant_id:
            client.auth_backend = 'azure_ad'
        if client.auth_backend:
            client.save(update_fields=['auth_backend'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_add_google_login_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('', 'Only allow password login'), ('azure_ad', 'Microsoft Azure AD'), ('google-openidconnect', 'Google')], help_text="Login method that will be used for users that don't have a password set", max_length=30, verbose_name='login method'),
        ),
        migrations.RunPython(set_auth_backend),
        migrations.RemoveField(
            model_name='client',
            name='azure_ad_tenant_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='google_login_button_text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='google_login_enabled',
        ),
        migrations.RemoveField(
            model_name='client',
            name='i18n',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_button_text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_header_text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='use_id_token_email_field',
        ),
    ]
