# Generated by Django 3.2.16 on 2023-06-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_add_google_login_to_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='azure_ad_tenant_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='google_login_button_text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='google_login_enabled',
        ),
        migrations.RemoveField(
            model_name='client',
            name='i18n',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_button_text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_header_text',
        ),
        migrations.RemoveField(
            model_name='client',
            name='use_id_token_email_field',
        ),
    ]
