# Generated by Django 3.2.13 on 2023-03-21 16:18

from django.db import migrations


def single_client_to_many(apps, schema_editor):
    AdminHostname = apps.get_model('admin_site', 'AdminHostname')
    for ahn in AdminHostname.objects.all():
        ahn.clients.add(ahn.client)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_adminhostname_clients'),
    ]

    operations = [
        migrations.RunPython(single_client_to_many, reverse_code=migrations.RunPython.noop),
    ]
