# Generated by Django 3.2.13 on 2023-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_migrate_hostname_client_to_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminhostname',
            options={},
        ),
        migrations.RemoveField(
            model_name='adminhostname',
            name='client',
        ),
        migrations.AlterField(
            model_name='adminhostname',
            name='clients',
            field=models.ManyToManyField(related_name='admin_hostnames', to='admin_site.Client'),
        ),
    ]
