# Generated by Django 3.2.16 on 2023-09-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_force_light_mode_for_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplan',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='client',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('', 'Only allow password login'), ('azure_ad', 'Microsoft Azure AD'), ('google-openidconnect', 'Google'), ('tunnistamo', 'Tunnistamo')], help_text="Login method that will be used for users that don't have a password set", max_length=30, verbose_name='login method'),
        ),
    ]
