# Generated by Django 3.2.13 on 2023-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_adminhostname_remove_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhostname',
            name='login_header_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='login header text'),
        ),
    ]
