# Generated by Django 3.2.13 on 2023-03-21 17:52

from django.db import migrations


def copy_client_login_header_to_hostname_login_header(apps, schema_editor):
    AdminHostname = apps.get_model('admin_site', 'AdminHostname')
    for ahn in AdminHostname.objects.all():
        c = ahn.clients.first()
        ahn.login_header_text = c.login_header_text
        ahn.save()
        if ahn.clients.count() == 1:
            c.login_header_text = None


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_adminhostname_login_header_text'),
    ]

    operations = [
        migrations.RunPython(copy_client_login_header_to_hostname_login_header, reverse_code=migrations.RunPython.noop)
    ]
