# Generated by Django 3.2.16 on 2023-09-07 10:33

from django.db import migrations


def ensure_unique_ordering(apps, schema_editor):
    ClientPlan = apps.get_model('admin_site', 'ClientPlan')
    Plan = apps.get_model('actions', 'Plan')
    for plan in Plan.objects.all():
        if plan.clients.count() < 2:
            continue
        order = 0
        for client in plan.clients.all().order_by('client__pk'):
            client.order = order
            order += 1
            client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0088_auto_20230907_1333'),
        ('admin_site', '0007_make_plan_clients_ordered'),
    ]

    operations = [
        migrations.RunPython(
            ensure_unique_ordering, migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name='clientplan',
            options={'ordering': ('plan', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='clientplan',
            unique_together={('plan', 'order')},
        ),
    ]
