# Generated by Django 3.2.16 on 2023-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_temporary_client_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Name of the customer organization administering the plan', max_length=100, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='AdminHostname',
        ),
    ]
