# Generated by Django 3.2.16 on 2023-11-08 14:22

import aplans.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0098_built_in_field_customization'),
        ('admin_site', '0010_delete_admin_hostname_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('', 'Only allow password login'), ('azure_ad', 'Microsoft Azure AD'), ('google-openidconnect', 'Google'), ('tunnistamo', 'Tunnistamo'), ('okta-openidconnect', 'OKTA')], help_text="Login method that will be used for users that don't have a password set", max_length=30, verbose_name='login method'),
        ),
        migrations.CreateModel(
            name='BuiltInFieldCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instances_editable_by', models.CharField(choices=[('authenticated', 'Authenticated users'), ('contact_persons', 'Contact persons'), ('moderators', 'Contact persons with moderator permissions'), ('plan_admins', 'Plan admins'), ('not_editable', 'Not editable')], default='authenticated', max_length=50, verbose_name='Edit rights')),
                ('instances_visible_for', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated users'), ('contact_persons', 'Contact persons'), ('moderators', 'Contact persons with "moderator" role'), ('plan_admins', 'Plan admins')], default='public', max_length=50, verbose_name='Visibility')),
                ('field_name', models.CharField(max_length=80, verbose_name='field')),
                ('help_text_override', models.TextField(blank=True, verbose_name='help text')),
                ('label_override', models.TextField(blank=True, verbose_name='label')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_in_action_attribute_types', to='actions.plan')),
            ],
            bases=(models.Model, aplans.utils.PlanRelatedModel),
        ),
        migrations.AddConstraint(
            model_name='builtinfieldcustomization',
            constraint=models.UniqueConstraint(fields=('plan', 'content_type', 'field_name'), name='unique_field_customization_per_plan'),
        ),
    ]
