# Generated by Django 5.0.6 on 2024-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_site", "0013_alter_client_locked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="expire_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="expired",
        ),
        migrations.RemoveField(
            model_name="client",
            name="first_published_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="go_live_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="has_unpublished_changes",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_published_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="latest_revision",
        ),
        migrations.RemoveField(
            model_name="client",
            name="live",
        ),
        migrations.RemoveField(
            model_name="client",
            name="live_revision",
        ),
        migrations.RemoveField(
            model_name="client",
            name="locked",
        ),
        migrations.RemoveField(
            model_name="client",
            name="locked_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="locked_by",
        ),
    ]
