# Generated by Django 5.0.6 on 2024-12-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0136_alter_plan_organization_alter_plan_short_identifier'),
        ('admin_site', '0014_remove_client_expire_at_remove_client_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfieldcustomization',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_in_field_customizations', to='actions.plan'),
        ),
    ]
