# Generated by Django 5.2 on 2025-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_alter_builtinfieldcustomization_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth_backend',
            field=models.CharField(blank=True, choices=[('', 'Only allow password login'), ('azure_ad', 'Microsoft Azure AD'), ('google-openidconnect', 'Google'), ('okta-openidconnect', 'OKTA'), ('adfs-openidconnect', 'ADFS OpenID Connect'), ('single_tenant_backend', 'Tenant-specific Entra ID Backend [do not use]')], help_text="Login method that will be used for users that don't have a password set", max_length=30, verbose_name='login method'),
        ),
    ]
