# Generated by Django 2.2.4 on 2019-09-17 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0028_add_action_status_is_completed_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, verbose_name='slug')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='actions.Plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ('plan', '-published_at'),
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('slug', models.CharField(blank=True, max_length=30, verbose_name='slug')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.StaticPage', verbose_name='parent page')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_pages', to='actions.Plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'content page',
                'verbose_name_plural': 'content pages',
                'unique_together': {('plan', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('title', models.CharField(max_length=150, verbose_name='question title')),
                ('answer', models.TextField(verbose_name='answer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='actions.Plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('plan', 'order'),
                'unique_together': {('plan', 'title')},
            },
        ),
    ]
