# Generated by Django 2.2.4 on 2019-09-18 20:13

import aplans.model_images
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('page', 'order'), 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=aplans.model_images.image_upload_path, verbose_name='image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1280x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.StaticPage', verbose_name='page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to=aplans.model_images.image_upload_path, verbose_name='image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1280x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticpage',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('page', 'title')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='plan',
        ),
    ]
