# Generated by Django 2.2.4 on 2019-09-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
    ]
