# Generated by Django 2.2.4 on 2019-10-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0033_add_field_allow_images_for_actions'),
        ('content', '0003_static_page_content_can_be_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGeneralContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=150, verbose_name='site title')),
                ('hero_content', models.TextField(blank=True)),
                ('official_name_description', models.CharField(blank=True, help_text='The text to show when displaying official content', max_length=200, verbose_name='official name description')),
                ('copyright_text', models.CharField(blank=True, max_length=150, verbose_name='copyright text')),
                ('creative_commons_license', models.CharField(blank=True, default='CC BY 4.0', help_text='If the site is under a Creative Commons license, which CC license it is', max_length=150, verbose_name='creative commons license')),
                ('github_api_repository', models.URLField(blank=True, verbose_name='Link to GitHub repository for API')),
                ('github_ui_repository', models.URLField(blank=True, verbose_name='Link to GitHub repository for UI')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_content', to='actions.Plan', verbose_name='plan')),
            ],
        ),
    ]
