# Generated by Django 2.2.8 on 2019-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_add_list_lead_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='footer',
            field=models.BooleanField(default=True, verbose_name='visible in page footer'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='top_menu',
            field=models.BooleanField(default=True, verbose_name='visible in top menu'),
        ),
    ]
