# Generated by Django 3.2.13 on 2022-10-04 18:42

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitegeneralcontent_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegeneralcontent',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['site_title', 'site_description', 'official_name_description', 'copyright_text', 'creative_commons_license', 'owner_name', 'owner_url'], required_languages=(), virtual_fields=True),
        ),
    ]
