# Generated by Django 2.2.9 on 2020-01-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_top_menu_and_footer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='action_short_description',
            field=models.TextField(blank=True, verbose_name='Short description for what actions are'),
        ),
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='indicator_short_description',
            field=models.TextField(blank=True, verbose_name='Short description for what indicators are'),
        ),
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of the owner of the site'),
        ),
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='owner_url',
            field=models.URLField(blank=True, verbose_name='URL for the owner of the site'),
        ),
    ]
