# Generated by Django 3.0.9 on 2020-08-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('content', '0009_add_dashboard_lead_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.AplansImage'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.AplansImage'),
        ),
    ]
