# Generated by Django 3.2.16 on 2023-12-21 14:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_sitegeneralcontent_organization_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegeneralcontent',
            name='sitewide_announcement',
            field=wagtail.fields.RichTextField(blank=True, help_text='A message prominently displayed in a banner at the top of every page on the public website', null=True, verbose_name='Sitewide announcement'),
        ),
    ]
