# Generated by Django 3.1.5 on 2021-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_use_wagtail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='was_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
