# Generated by Django 3.1.5 on 2021-02-02 10:17

from django.db import migrations


def abort_unless_data_migrated(apps, schema_editor):
    OldStaticPage = apps.get_model('content', 'StaticPage')
    if OldStaticPage.objects.filter(was_migrated=False).exists():
        raise Exception("There are unmigrated static pages. Please make sure all other apps are migrated, then run the "
                        "management command migrate_static_pages and retry this migration. For the command to work, "
                        "you will need to check out a version of the code where the models in the content app still "
                        "exist.")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_was_migrated_field'),
    ]

    operations = [
        migrations.RunPython(abort_unless_data_migrated),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
