# Generated by Django 3.1.5 on 2021-03-01 12:00

from django.db import migrations


def abort_unless_data_migrated(apps, schema_editor):
    SiteGeneralContent = apps.get_model('content', 'SiteGeneralContent')
    if SiteGeneralContent.objects.filter(migrated_data_to_pages_app=False).exists():
        raise Exception("There are unmigrated model instances. Please make sure all other apps are migrated, then run "
                        "the management command migrate_site_general_content_data_to_pages_app and retry this migration. "
                        "For the command to work, you will need to check out the commit tagged with "
                        "migrate-site-general-content-data-to-pages-app.")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_add_migrated_data_to_pages_app_field'),
    ]

    operations = [
        migrations.RunPython(abort_unless_data_migrated),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='action_short_description',
        ),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='hero_content',
        ),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='indicator_short_description',
        ),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='migrated_data_to_pages_app',
        ),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='action_list_lead_content',
        ),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='indicator_list_lead_content',
        ),
        migrations.RemoveField(
            model_name='sitegeneralcontent',
            name='dashboard_lead_content',
        ),
    ]
