# Generated by Django 3.2.16 on 2023-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedrequest',
            name='path',
            field=models.CharField(max_length=2000),
        ),
    ]
