# Generated by Django 5.2 on 2026-01-16 11:22

from django.db import migrations


def copy_data_from_parent_tables(apps, schema_editor):
    PlanScopedModelLogEntry = apps.get_model('audit_logging', 'PlanScopedModelLogEntry')
    PlanScopedPageLogEntry = apps.get_model('audit_logging', 'PlanScopedPageLogEntry')

    # Copy data for PlanScopedModelLogEntry
    for entry in PlanScopedModelLogEntry.objects.all():
        if not entry.modellogentry_migration_instance:
            raise ValueError(f'PlanScopedModelLogEntry {entry.id} has no modellogentry_migration_instance')
        parent = entry.modellogentry_migration_instance
        # Copy ModelLogEntry fields
        entry.object_id = parent.object_id
        # Copy BaseLogEntry fields from the parent
        entry.content_type_id = parent.content_type_id
        entry.label = parent.label
        entry.action = parent.action
        entry.data = parent.data
        entry.timestamp = parent.timestamp
        entry.uuid = parent.uuid
        entry.user_id = parent.user_id
        entry.revision_id = parent.revision_id
        entry.content_changed = parent.content_changed
        entry.deleted = parent.deleted
        entry.save()

    # Copy data for PlanScopedPageLogEntry
    for entry in PlanScopedPageLogEntry.objects.all():
        if not entry.pagelogentry_migration_instance:
            raise ValueError(f'PlanScopedPageLogEntry {entry.id} has no pagelogentry_migration_instance')
        parent = entry.pagelogentry_migration_instance
        # Copy PageLogEntry fields
        entry.page_id = parent.page_id
        # Copy BaseLogEntry fields from the parent
        entry.content_type_id = parent.content_type_id
        entry.label = parent.label
        entry.action = parent.action
        entry.data = parent.data
        entry.timestamp = parent.timestamp
        entry.uuid = parent.uuid
        entry.user_id = parent.user_id
        entry.revision_id = parent.revision_id
        entry.content_changed = parent.content_changed
        entry.deleted = parent.deleted
        entry.save()


def reverse_copy(apps, schema_editor):
    PlanScopedModelLogEntry = apps.get_model('audit_logging', 'PlanScopedModelLogEntry')
    PlanScopedPageLogEntry = apps.get_model('audit_logging', 'PlanScopedPageLogEntry')

    # Clear the copied fields
    PlanScopedModelLogEntry.objects.all().update(
        object_id=None,
        content_type_id=None,
        label=None,
        action=None,
        data=None,
        timestamp=None,
        uuid=None,
        user_id=None,
        revision_id=None,
        content_changed=None,
        deleted=None,
    )

    PlanScopedPageLogEntry.objects.all().update(
        page_id=None,
        content_type_id=None,
        label=None,
        action=None,
        data=None,
        timestamp=None,
        uuid=None,
        user_id=None,
        revision_id=None,
        content_changed=None,
        deleted=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logging', '0005_planscopedmodellogentry_action_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_data_from_parent_tables, reverse_copy),
    ]
