# Generated by Django 5.2 on 2026-01-16 12:11

from django.db import migrations


def delete_old_parent_instances(apps, schema_editor):
    PlanScopedModelLogEntry = apps.get_model('audit_logging', 'PlanScopedModelLogEntry')
    PlanScopedPageLogEntry = apps.get_model('audit_logging', 'PlanScopedPageLogEntry')
    ModelLogEntry = apps.get_model('wagtailcore', 'ModelLogEntry')
    PageLogEntry = apps.get_model('wagtailcore', 'PageLogEntry')

    # Collect IDs of parent instances to delete
    model_log_entry_ids = list(
        PlanScopedModelLogEntry.objects.filter(
            modellogentry_migration_instance__isnull=False
        ).values_list('modellogentry_migration_instance_id', flat=True)
    )

    page_log_entry_ids = list(
        PlanScopedPageLogEntry.objects.filter(
            pagelogentry_migration_instance__isnull=False
        ).values_list('pagelogentry_migration_instance_id', flat=True)
    )

    # Delete the old parent instances
    if model_log_entry_ids:
        ModelLogEntry.objects.filter(id__in=model_log_entry_ids).delete()

    if page_log_entry_ids:
        PageLogEntry.objects.filter(id__in=page_log_entry_ids).delete()


def reverse_delete(apps, schema_editor):
    # Cannot reverse deletion - would need to recreate parent instances
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logging', '0006_copy_data_from_parent_tables'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RunPython(delete_old_parent_instances, reverse_delete),
    ]
