# Generated by Django 5.2 on 2026-01-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0007_delete_old_parent_instances"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planscopedmodellogentry",
            name="modellogentry_migration_instance",
        ),
        migrations.RemoveField(
            model_name="planscopedpagelogentry",
            name="pagelogentry_migration_instance",
        ),
    ]
