# Generated by Django 5.2 on 2026-01-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logging', '0009_alter_planscopedmodellogentry_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planscopedmodellogentry',
            name='object_id',
            field=models.CharField(db_index=True, default='ERROR_NULL_OBJECT_ID', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planscopedpagelogentry',
            name='page',
            field=models.ForeignKey(
                db_constraint=False,
                default=1,  # Error marker - use root page id
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='wagtailcore.page',
            ),
            preserve_default=False,
        ),
    ]
