# Generated by Django 6.0.2 on 2026-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logging", "0011_alter_planscopedmodellogentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planscopedmodellogentry",
            options={
                "ordering": ["-timestamp", "-id"],
                "verbose_name": "plan-scoped model log entry",
                "verbose_name_plural": "plan-scoped model log entries",
            },
        ),
        migrations.AlterModelOptions(
            name="planscopedpagelogentry",
            options={
                "ordering": ["-timestamp", "-id"],
                "verbose_name": "plan-scoped page log entry",
                "verbose_name_plural": "plan-scoped page log entries",
            },
        ),
    ]
