# Generated by Django 3.1.5 on 2021-09-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('images', '0001_initial'),
        ('people', '0001_initial'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentnotification',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people.person'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='base',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.basetemplate'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='base',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='notifications.basetemplate'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Do not set if content block is used in multiple templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='notifications.notificationtemplate', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.aplansimage'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_base_template', to='actions.plan', verbose_name='plan'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('base', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('base', 'template', 'identifier')},
        ),
    ]
