# Generated by Django 2.2.8 on 2019-12-06 13:51

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('base', 'type')},
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='identifier')),
                ('base', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='notifications.BaseTemplate')),
                ('template', models.ForeignKey(blank=True, help_text='Do not set if content block is used in multiple templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='notifications.NotificationTemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'content block',
                'verbose_name_plural': 'content blocks',
                'unique_together': {('base', 'template', 'identifier')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentBlockTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('content', models.TextField(help_text='HTML content for the block', verbose_name='content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.ContentBlock')),
            ],
            options={
                'verbose_name': 'content block Translation',
                'db_table': 'notifications_contentblock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
