# Generated by Django 3.2.12 on 2022-02-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_content_block_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetemplate',
            name='i18n',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='i18n',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='i18n',
        ),
    ]
