# Generated by Django 3.1 on 2020-10-08 10:35

from django.db import migrations


def forward_func(apps, schema_editor):
    NTT = apps.get_model('notifications', 'NotificationTemplateTranslation')
    CBT = apps.get_model('notifications', 'ContentBlockTranslation')

    for tobj in NTT.objects.filter(language_code='fi'):
        obj = tobj.master
        obj.subject_t = tobj.subject
        obj.html_body_t = tobj.html_body
        obj.save()

    for tobj in CBT.objects.filter(language_code='fi'):
        obj = tobj.master
        obj.name_t = tobj.name
        obj.content_t = tobj.content
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_start_removing_parler'),
    ]

    operations = [
        migrations.RunPython(forward_func, None),
    ]
