# Generated by Django 3.1 on 2020-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_parler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.TextField(help_text='HTML content for the block', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='html_body',
            field=models.TextField(help_text='HTML body for email notifications', verbose_name='HTML body'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(help_text='Subject for email notifications', max_length=200, verbose_name='subject'),
        ),
    ]
