# Generated by Django 3.1 on 2020-10-08 11:50

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetemplate',
            name='from_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email From address'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='from_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email From name'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['from_name'], required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['name', 'content'], required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['subject', 'html_body'], required_languages=(), virtual_fields=True),
        ),
    ]
