# Generated by Django 3.2.13 on 2022-08-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_contentblock_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Do not set if content block is used in multiple templates', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_blocks', to='notifications.notificationtemplate', verbose_name='template'),
        ),
    ]
