# Generated by Django 3.1.3 on 2020-11-24 12:04

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('notifications', '0007_add_email_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetemplate',
            name='html_body',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='html_body',
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='brand_dark_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Brand dark color'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='font_css_url',
            field=models.URLField(blank=True, null=True, verbose_name='Font CSS style URL'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='font_family',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Font family'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.aplansimage'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='reply_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Reply-To address'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='identifier',
            field=models.CharField(choices=[('intro', 'Introduction block'), ('motivation', 'Motivation block'), ('outro', 'Contact information block')], max_length=50, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=['subject'], required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks")], max_length=100, verbose_name='type'),
        ),
    ]
