# Generated by Django 3.2.13 on 2022-08-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_contentblock_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetemplate',
            options={'verbose_name': 'notification settings', 'verbose_name_plural': 'notification settings'},
        ),
    ]
