# Generated by Django 3.1.5 on 2021-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_migrate_schema_to_mjml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon')], max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon')], max_length=100, verbose_name='type'),
        ),
    ]
