# Generated by Django 3.2.13 on 2023-02-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_add_created_by_field'),
        ('notifications', '0010_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Overrides the default recipients for this template', max_length=254, verbose_name='recipient email address'),
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='email',
            field=models.EmailField(blank=True, help_text='Set if the notification was set to an email address instead of a person', max_length=254),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='sentnotification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('person__isnull', True), models.Q(('email', ''), _negated=True)), models.Q(('person__isnull', False), ('email', '')), _connector='OR'), name='person_xor_email'),
        ),
    ]
