# Generated by Django 5.0.4 on 2024-05-29 15:40

import django.db.models.deletion
import modelcluster.fields
import notifications.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_fk_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentnotification',
            name='type',
            field=models.CharField(choices=[('task_late', 'Task is late'), ('task_due_soon', 'Task is due soon'), ('action_not_updated', 'Action metadata has not been updated recently'), ('not_enough_tasks', "Action doesn't have enough in-progress tasks"), ('updated_indicator_values_late', 'Updated indicator values are late'), ('updated_indicator_values_due_soon', 'Updated indicator values are due soon'), ('user_feedback_received', 'User feedback received'), ('manually_scheduled', 'Manually scheduled notification')], max_length=100, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='ManuallyScheduledNotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject for email notifications', max_length=200, verbose_name='subject')),
                ('custom_email', models.EmailField(blank=True, help_text='Email address used when "send to custom email address" is checked', max_length=254, verbose_name='custom email address')),
                ('send_to_plan_admins', models.BooleanField(default=True, verbose_name='send to plan admins')),
                ('send_to_custom_email', models.BooleanField(default=False, verbose_name='send to custom email address')),
                ('type', models.CharField(db_default='manually_scheduled', default='manually_scheduled', editable=False, max_length=100, verbose_name='type')),
                ('date', models.DateField()),
                ('content', wagtail.fields.RichTextField(help_text='The content of the notification', verbose_name='content')),
                ('send_to_action_contact_persons', models.BooleanField(default=True, verbose_name='send to action contact persons')),
                ('send_to_indicator_contact_persons', models.BooleanField(default=True, verbose_name='send to indicator contact persons')),
                ('send_to_organization_admins', models.BooleanField(default=True, verbose_name='send to organization admins')),
                ('base', modelcluster.fields.ParentalKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='manually_scheduled_notification_templates', to='notifications.basetemplate')),
            ],
            options={
                'verbose_name': 'scheduled notification',
                'verbose_name_plural': 'scheduled notifications',
                'ordering': ('date', 'subject'),
                'abstract': False,
            },
            bases=(models.Model, notifications.models.IndirectPlanRelatedModel),
        ),
        migrations.AddConstraint(
            model_name='manuallyschedulednotificationtemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('custom_email', ''), ('send_to_custom_email', False)), models.Q(models.Q(('custom_email', ''), _negated=True), ('send_to_custom_email', True)), _connector='OR'), name='custom_email_iff_send_to_custom_email_the_sequel'),
        ),
        migrations.AlterUniqueTogether(
            name='manuallyschedulednotificationtemplate',
            unique_together={('base', 'date', 'subject')},
        ),
    ]
