# Generated by Django 6.0.2 on 2026-08-12 11:43

from django.db import migrations, models


NEW_TYPE = 'pledge_participant_signup'


def seed_pledge_signup_template(apps, schema_editor):
    """
    Add a pledge-signup template row for every existing community-engagement plan.

    Only plans with enable_community_engagement=True get the row; other plans
    would see it as inert clutter in the notification-templates admin. Defaults
    for subject and intro come from NotificationType so both this migration
    and initialize_notifications use the same source of truth.
    """
    from django.utils import translation

    from notifications.notifications import NotificationType

    BaseTemplate = apps.get_model('notifications', 'BaseTemplate')
    AutomaticNotificationTemplate = apps.get_model('notifications', 'AutomaticNotificationTemplate')
    bases = BaseTemplate.objects.filter(plan__features__enable_community_engagement=True).select_related('plan')
    for base in bases:
        with translation.override(base.plan.primary_language):
            default_subject = NotificationType.PLEDGE_PARTICIPANT_SIGNUP.default_subject
        AutomaticNotificationTemplate.objects.get_or_create(
            base=base,
            type=NEW_TYPE,
            defaults={'subject': default_subject, 'send_to_plan_admins': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0017_automaticnotificationtemplate_latest_revision_and_more",
        ),
        ("actions", "0158_add_community_engagement_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticnotificationtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_late", "Task is late"),
                    ("task_due_soon", "Task is due soon"),
                    (
                        "action_not_updated",
                        "Action metadata has not been updated recently",
                    ),
                    (
                        "not_enough_tasks",
                        "Action doesn't have enough in-progress tasks",
                    ),
                    (
                        "updated_indicator_values_late",
                        "Updated indicator values are late",
                    ),
                    (
                        "updated_indicator_values_due_soon",
                        "Updated indicator values are due soon",
                    ),
                    ("user_feedback_received", "User feedback received"),
                    ("pledge_participant_signup", "Pledge participant signed up"),
                ],
                max_length=100,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="sentnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_late", "Task is late"),
                    ("task_due_soon", "Task is due soon"),
                    (
                        "action_not_updated",
                        "Action metadata has not been updated recently",
                    ),
                    (
                        "not_enough_tasks",
                        "Action doesn't have enough in-progress tasks",
                    ),
                    (
                        "updated_indicator_values_late",
                        "Updated indicator values are late",
                    ),
                    (
                        "updated_indicator_values_due_soon",
                        "Updated indicator values are due soon",
                    ),
                    ("user_feedback_received", "User feedback received"),
                    ("pledge_participant_signup", "Pledge participant signed up"),
                    ("manually_scheduled", "Manually scheduled notification"),
                ],
                max_length=100,
                verbose_name="type",
            ),
        ),
        migrations.RunPython(seed_pledge_signup_template, reverse_code=migrations.RunPython.noop),
    ]
