name: reviewdog
on:
  pull_request:
  push:

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements-lint.txt
            requirements-kausal.txt
            requirements.txt
            pyproject.toml

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
          key: ${{ runner.os }}-${{ hashFiles('requirements-lint.txt', 'requirements-kausal.txt', 'requirements.txt', 'pyproject.toml') }}

      - name: Set up Python
        run: uv python install

      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libproj-dev libgdal-dev
      #     version: 1.0
      #     execute_install_scripts: true

      - name: Install gdal dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y libproj-dev libgdal-dev

      - name: Install Python dependencies
        env:
          EXTRA_PYPI_INDEX: ${{ secrets.EXTRA_PYPI_INDEX }}
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -r requirements-lint.txt -r requirements.txt -r requirements-kausal.txt --extra-index-url "$EXTRA_PYPI_INDEX"

      - name: Get push diff
        if: github.event_name == 'push' && github.event.before
        id: push_diff
        run: |
          # Check if the "before" hash exists
          if [ "$(git cat-file -t ${{ github.event.before }})" = "commit" ] ; then
            echo Diffing ${{ github.event.before }}..${{ github.sha }}
            git diff --find-renames --submodule=diff ${{ github.event.before }} ${{ github.sha }} > ${{ runner.temp }}/changes.diff
            echo has_diff=true >> $GITHUB_OUTPUT
          else
            echo Commit ${{ github.event.before }} does not exist -- skipping reviewdog
            echo has_diff=false >> $GITHUB_OUTPUT
          fi
        shell: bash

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      - name: Run reviewdog for push
        if: github.event_name == 'push' && steps.push_diff.outputs.has_diff == 'true'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . .venv/bin/activate
          REVIEWDOG_ARGS="-reporter=github-check -fail-level=error -diff 'cat ${{ runner.temp }}/changes.diff'"
          echo running reviewdog
          reviewdog -runners=ruff -filter-mode=added $REVIEWDOG_ARGS
          echo running mypy
          mypy . > ${{ runner.temp }}/mypy-output.txt || mypy_exit=$?
          if [[ $mypy_exit -ne 0 && $mypy_exit -ne 1 ]]; then
            echo "mypy failed with exit code $mypy_exit"
            cat ${{ runner.temp }}/mypy-output.txt
            exit $mypy_exit
          fi
          cat ${{ runner.temp }}/mypy-output.txt | mypy-baseline filter --hide-stats > ${{ runner.temp }}/mypy-baselined-output.txt || baseline_exit=$?
          echo running reviewdog again for mypy
          reviewdog -f=mypy -name=mypy -filter-mode=nofilter $REVIEWDOG_ARGS < ${{ runner.temp }}/mypy-baselined-output.txt

      - name: Run reviewdog for PR
        if: github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEWDOG_ARGS="-reporter=github-pr-check -fail-level=error"
          echo running reviewdog
          reviewdog -runners=ruff -filter-mode=added $REVIEWDOG_ARGS
          echo running mypy
          mypy . > ${{ runner.temp }}/mypy-output.txt || mypy_exit=$?
          if [[ $mypy_exit -ne 0 && $mypy_exit -ne 1 ]]; then
            echo "mypy failed with exit code $mypy_exit"
            cat ${{ runner.temp }}/mypy-output.txt
            exit $mypy_exit
          fi
          echo filtering suppressed errors
          cat ${{ runner.temp }}/mypy-output.txt | mypy-baseline filter --hide-stats > ${{ runner.temp }}/mypy-baselined-output.txt || baseline_exit=$?
          echo running reviewdog again for mypy reporting
          reviewdog -f=mypy -name=mypy -filter-mode=nofilter $REVIEWDOG_ARGS < ${{ runner.temp }}/mypy-baselined-output.txt
          exit $baseline_exit
