name: reviewdog
on:
  pull_request:
  push:

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
          prune-cache: false

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
          key: ${{ runner.os }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}

      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libproj-dev libgdal-dev
      #     version: 1.0
      #     execute_install_scripts: true

      - name: Install gdal dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y libproj-dev libgdal-dev

      - name: Install Python dependencies
        env:
          EXTRA_PYPI_INDEX: ${{ secrets.EXTRA_PYPI_INDEX }}
        run: |
          uv sync --index ${EXTRA_PYPI_INDEX} --group lint --extra kausal

      - name: Get push diff
        if: github.event_name == 'push' && github.event.before
        id: push_diff
        run: |
          # Check if the "before" hash exists
          if [ "$(git cat-file -t ${{ github.event.before }})" = "commit" ] ; then
            echo Diffing ${{ github.event.before }}..${{ github.sha }}
            git diff --find-renames --submodule=diff ${{ github.event.before }} ${{ github.sha }} > ${{ runner.temp }}/changes.diff
            echo has_diff=true >> $GITHUB_OUTPUT
          else
            echo Commit ${{ github.event.before }} does not exist -- skipping reviewdog
            echo has_diff=false >> $GITHUB_OUTPUT
          fi
        shell: bash

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.20.3 # Optional. [latest,nightly,v.X.Y.Z]

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEWDOG_ARGS="-reporter=${{ steps.reviewdog_context.outputs.reviewdog_reporter }} -fail-level=error"
          diff_file=${{ steps.reviewdog_context.outputs.reviewdog_diff_file }}
          if [ -n "$diff_file" ] ; then
            REVIEWDOG_ARGS="$REVIEWDOG_ARGS -diff 'cat $diff_file'"
          fi
          echo running ruff
          reviewdog -runners=ruff -filter-mode=added $REVIEWDOG_ARGS
          echo running mypy
          mypy . > ${{ runner.temp }}/mypy-output.txt || mypy_exit=$?
          if [[ $mypy_exit -ne 0 && $mypy_exit -ne 1 ]]; then
            echo "mypy failed with exit code $mypy_exit"
            cat ${{ runner.temp }}/mypy-output.txt
            exit $mypy_exit
          fi
          echo filtering suppressed mypy errors
          cat ${{ runner.temp }}/mypy-output.txt | mypy-baseline filter --hide-stats > ${{ runner.temp }}/mypy-baselined-output.txt || baseline_exit=$?
          echo running reviewdog again for mypy reporting
          reviewdog -f=mypy -name=mypy -filter-mode=nofilter $REVIEWDOG_ARGS < ${{ runner.temp }}/mypy-baselined-output.txt
          exit $baseline_exit
